# Generated by Django 5.1.6 on 2025-09-02 17:33

from django.db import migrations
from pgvector.django import VectorExtension

class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [VectorExtension()]