# Generated by Django 5.1.6 on 2026-02-09 21:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualityreports',
            name='operator',
        ),
        migrations.AddField(
            model_name='qualityreports',
            name='operators',
            field=models.ManyToManyField(blank=True, help_text='Operators running the process when defect occurred (for root cause)', related_name='defects_during_operation', to=settings.AUTH_USER_MODEL),
        ),
    ]
