# Generated by Django 5.1.6 on 2026-02-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0002_remove_qualityreports_operator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityreports',
            name='is_first_piece',
            field=models.BooleanField(default=False, help_text='If True, this inspection is a First Piece Inspection (FPI) for setup verification'),
        ),
        migrations.AddField(
            model_name='steps',
            name='requires_first_piece_inspection',
            field=models.BooleanField(default=False, help_text='If True, first part of each work order at this step requires FPI before others can proceed'),
        ),
    ]
