# Generated by Django 5.1.6 on 2026-02-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0003_add_first_piece_inspection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workorder',
            options={'ordering': ['priority', '-created_at'], 'verbose_name': 'Work Order', 'verbose_name_plural': 'Work Orders'},
        ),
        migrations.AddField(
            model_name='workorder',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Urgent'), (2, 'High'), (3, 'Normal'), (4, 'Low')], default=3, help_text='Work order priority. Lower number = higher priority for scheduling.'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['priority', 'workorder_status'], name='workorder_priority_status_idx'),
        ),
    ]
