# Generated by Django 5.1.6 on 2026-02-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0004_add_workorder_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='threedmodel',
            name='face_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of triangles in processed mesh', null=True),
        ),
        migrations.AddField(
            model_name='threedmodel',
            name='final_size_bytes',
            field=models.PositiveIntegerField(blank=True, help_text='Final GLB file size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='threedmodel',
            name='original_filename',
            field=models.CharField(blank=True, help_text='Original uploaded filename', max_length=255),
        ),
        migrations.AddField(
            model_name='threedmodel',
            name='original_format',
            field=models.CharField(blank=True, help_text="Original file format (e.g., 'step', 'stl', 'obj')", max_length=20),
        ),
        migrations.AddField(
            model_name='threedmodel',
            name='original_size_bytes',
            field=models.PositiveIntegerField(blank=True, help_text='Original file size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='threedmodel',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='When processing completed', null=True),
        ),
        migrations.AddField(
            model_name='threedmodel',
            name='processing_error',
            field=models.TextField(blank=True, help_text='Error message if processing failed'),
        ),
        migrations.AddField(
            model_name='threedmodel',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current processing state', max_length=20),
        ),
        migrations.AddField(
            model_name='threedmodel',
            name='vertex_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of vertices in processed mesh', null=True),
        ),
        migrations.AlterField(
            model_name='threedmodel',
            name='file_type',
            field=models.CharField(blank=True, help_text="Output format after processing (always 'glb')", max_length=50),
        ),
    ]
