# Generated by Django 5.1.6 on 2026-02-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0005_add_3d_model_processing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='allowed_domains',
            field=models.JSONField(blank=True, default=list, help_text="Email domains for automatic SSO tenant matching, e.g. ['acme.com', 'acme.co.uk']"),
        ),
    ]
