# Generated by Django 5.1.6 on 2026-02-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0006_add_tenant_allowed_domains'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='address',
            field=models.TextField(blank=True, help_text='Organization mailing address'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Primary contact email for the organization', max_length=254),
        ),
        migrations.AddField(
            model_name='tenant',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Primary contact phone number', max_length=30),
        ),
        migrations.AddField(
            model_name='tenant',
            name='default_timezone',
            field=models.CharField(default='UTC', help_text="Default timezone for the organization (IANA format, e.g., 'America/New_York')", max_length=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, help_text='Organization logo (recommended: 200x200 PNG)', null=True, upload_to='tenant_logos/'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='website',
            field=models.URLField(blank=True, help_text='Organization website URL'),
        ),
    ]
