# Generated by Django 5.1.6 on 2026-02-19
# Step Completion & Workflow Preparation Migration
# Fixes current validation/cascade bugs AND prepares schema for future workflow engine integration

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def uuid7():
    """Generate a UUIDv7 for primary keys."""
    import time
    import random

    timestamp_ms = int(time.time() * 1000)
    timestamp_bytes = timestamp_ms.to_bytes(6, 'big')
    random_bytes = random.getrandbits(74).to_bytes(10, 'big')

    uuid_bytes = bytearray(16)
    uuid_bytes[0:6] = timestamp_bytes
    uuid_bytes[6] = (uuid_bytes[6] & 0x0F) | 0x70  # Version 7
    uuid_bytes[6:8] = random_bytes[0:2]
    uuid_bytes[8] = (random_bytes[2] & 0x3F) | 0x80  # Variant
    uuid_bytes[8:16] = random_bytes[2:10]

    return uuid.UUID(bytes=bytes(uuid_bytes))


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0007_tenant_address_tenant_contact_email_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # =====================================================================
        # STEP EXECUTION - New fields for workflow tracking
        # =====================================================================
        migrations.AddField(
            model_name='stepexecution',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When work actually started on this step', null=True),
        ),
        migrations.AddField(
            model_name='stepexecution',
            name='needs_reassignment',
            field=models.BooleanField(default=False, help_text='Flag indicating operator reassignment is needed'),
        ),
        migrations.AddField(
            model_name='stepexecution',
            name='is_fpi',
            field=models.BooleanField(default=False, help_text='Whether this execution is a First Piece Inspection'),
        ),
        migrations.AddField(
            model_name='stepexecution',
            name='fpi_status',
            field=models.CharField(
                choices=[
                    ('not_required', 'Not Required'),
                    ('pending', 'Pending'),
                    ('passed', 'Passed'),
                    ('failed', 'Failed'),
                    ('waived', 'Waived'),
                ],
                default='not_required',
                help_text='First Piece Inspection status for this execution',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='stepexecution',
            name='subject_content_type',
            field=models.ForeignKey(
                blank=True,
                help_text='Content type for polymorphic subject (future workflow engine)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='contenttypes.contenttype',
            ),
        ),
        migrations.AddField(
            model_name='stepexecution',
            name='subject_id',
            field=models.UUIDField(blank=True, help_text='ID of the polymorphic subject', null=True),
        ),
        # Update status choices to include 'claimed' and 'cancelled'
        migrations.AlterField(
            model_name='stepexecution',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('claimed', 'Claimed'),
                    ('in_progress', 'In Progress'),
                    ('completed', 'Completed'),
                    ('skipped', 'Skipped'),
                    ('cancelled', 'Cancelled'),
                ],
                default='pending',
                max_length=20,
            ),
        ),

        # =====================================================================
        # STEPS - New fields for workflow configuration
        # =====================================================================
        migrations.AddField(
            model_name='steps',
            name='fpi_scope',
            field=models.CharField(
                choices=[
                    ('per_workorder', 'Per Work Order'),
                    ('per_shift', 'Per Shift'),
                    ('per_equipment', 'Per Equipment'),
                    ('per_operator', 'Per Operator'),
                ],
                default='per_workorder',
                help_text='Scope at which FPI applies (work order, shift, equipment, or operator)',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='steps',
            name='block_on_measurement_failure',
            field=models.BooleanField(
                default=False,
                help_text='If True, parts cannot advance if any measurement is out of spec',
            ),
        ),
        migrations.AddField(
            model_name='steps',
            name='override_expiry_hours',
            field=models.PositiveIntegerField(
                default=24,
                help_text='Hours until an override expires and must be re-approved',
            ),
        ),
        migrations.AddField(
            model_name='steps',
            name='undo_window_minutes',
            field=models.PositiveIntegerField(
                default=15,
                help_text='Minutes during which a step completion can be undone',
            ),
        ),
        migrations.AddField(
            model_name='steps',
            name='rollback_requires_approval',
            field=models.BooleanField(
                default=True,
                help_text='Whether rolling back this step requires supervisor approval',
            ),
        ),
        migrations.AddField(
            model_name='steps',
            name='requires_batch_completion',
            field=models.BooleanField(
                default=False,
                help_text='If True, all parts in batch must be ready before any can advance',
            ),
        ),

        # =====================================================================
        # PROCESSES - Category field for workflow engine
        # =====================================================================
        migrations.AddField(
            model_name='processes',
            name='category',
            field=models.CharField(
                choices=[
                    ('manufacturing', 'Manufacturing'),
                    ('quality', 'Quality'),
                    ('maintenance', 'Maintenance'),
                    ('npi', 'New Product Introduction'),
                    ('document', 'Document Control'),
                ],
                default='manufacturing',
                help_text='Process category for workflow engine routing',
                max_length=20,
            ),
        ),

        # =====================================================================
        # PROCESS STEP - New fields for workflow configuration
        # =====================================================================
        migrations.AddField(
            model_name='processstep',
            name='is_exit_point',
            field=models.BooleanField(
                default=False,
                help_text='If True, this step can exit the process early (e.g., early ship)',
            ),
        ),
        migrations.AddField(
            model_name='processstep',
            name='auto_advance',
            field=models.BooleanField(
                default=True,
                help_text='If True, parts auto-advance when step requirements are met',
            ),
        ),

        # =====================================================================
        # PARTS - FPI candidate tracking
        # =====================================================================
        migrations.AddField(
            model_name='parts',
            name='is_fpi_candidate',
            field=models.BooleanField(
                default=False,
                help_text='Whether this part is designated as a First Piece Inspection candidate',
            ),
        ),
        migrations.AddField(
            model_name='parts',
            name='fpi_override_reason',
            field=models.CharField(
                blank=True,
                help_text='Reason if FPI was overridden or waived',
                max_length=200,
            ),
        ),

        # =====================================================================
        # SCHEDULE SLOT - Operator assignment
        # =====================================================================
        migrations.AddField(
            model_name='scheduleslot',
            name='assigned_operator',
            field=models.ForeignKey(
                blank=True,
                help_text='Operator assigned to this schedule slot',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='assigned_slots',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='scheduleslot',
            name='needs_reassignment',
            field=models.BooleanField(
                default=False,
                help_text='Flag indicating operator reassignment is needed',
            ),
        ),

        # =====================================================================
        # PARTS STATUS - Add additional terminal statuses
        # =====================================================================
        # Note: PartsStatus is a TextChoices enum, we'll update it in model code
        # The database already supports any string value up to 50 chars

        # =====================================================================
        # NEW MODEL: StepRequirement
        # =====================================================================
        migrations.CreateModel(
            name='StepRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid7, editable=False, primary_key=True, serialize=False)),
                ('tenant', models.ForeignKey(blank=True, db_index=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('requirement_type', models.CharField(
                    choices=[
                        ('measurement', 'Measurement'),
                        ('document', 'Document'),
                        ('signoff', 'Signoff'),
                        ('equipment_check', 'Equipment Check'),
                        ('material_scan', 'Material Scan'),
                        ('training_valid', 'Training Valid'),
                        ('calibration_valid', 'Calibration Valid'),
                        ('fpi_passed', 'FPI Passed'),
                        ('qa_approval', 'QA Approval'),
                        ('custom', 'Custom'),
                    ],
                    help_text='Type of requirement',
                    max_length=30,
                )),
                ('name', models.CharField(help_text='Short name for the requirement', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the requirement')),
                ('is_mandatory', models.BooleanField(default=True, help_text='Whether this requirement must be satisfied to advance')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within step')),
                ('config', models.JSONField(default=dict, help_text='Type-specific configuration (e.g., measurement IDs, document types)')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='Tracker.steps')),
            ],
            options={
                'verbose_name': 'Step Requirement',
                'verbose_name_plural': 'Step Requirements',
                'ordering': ['step', 'order'],
            },
        ),

        # =====================================================================
        # NEW MODEL: FPIRecord
        # =====================================================================
        migrations.CreateModel(
            name='FPIRecord',
            fields=[
                ('id', models.UUIDField(default=uuid7, editable=False, primary_key=True, serialize=False)),
                ('tenant', models.ForeignKey(blank=True, db_index=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('shift_date', models.DateField(blank=True, help_text='Date of the shift for per-shift FPI', null=True)),
                ('status', models.CharField(
                    choices=[
                        ('pending', 'Pending'),
                        ('in_progress', 'In Progress'),
                        ('passed', 'Passed'),
                        ('failed', 'Failed'),
                        ('waived', 'Waived'),
                    ],
                    default='pending',
                    help_text='Current status of the FPI',
                    max_length=20,
                )),
                ('result', models.CharField(
                    blank=True,
                    choices=[
                        ('pass', 'Pass'),
                        ('fail', 'Fail'),
                        ('conditional', 'Conditional Pass'),
                    ],
                    help_text='Final result of the FPI',
                    max_length=20,
                )),
                ('inspected_at', models.DateTimeField(blank=True, help_text='When inspection was completed', null=True)),
                ('waived', models.BooleanField(default=False, help_text='Whether FPI requirement was waived')),
                ('waive_reason', models.TextField(blank=True, help_text='Reason for waiving FPI requirement')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fpi_records', to='Tracker.workorder')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fpi_records', to='Tracker.steps')),
                ('part_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fpi_records', to='Tracker.parttypes')),
                ('designated_part', models.ForeignKey(blank=True, help_text='The part designated for FPI', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fpi_records', to='Tracker.parts')),
                ('equipment', models.ForeignKey(blank=True, help_text='Equipment being used (for per-equipment FPI)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fpi_records', to='Tracker.equipments')),
                ('inspected_by', models.ForeignKey(blank=True, help_text='User who performed the inspection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fpi_inspections', to=settings.AUTH_USER_MODEL)),
                ('waived_by', models.ForeignKey(blank=True, help_text='User who waived the FPI', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FPI Record',
                'verbose_name_plural': 'FPI Records',
                'ordering': ['-created_at'],
            },
        ),

        # =====================================================================
        # NEW MODEL: StepOverride
        # =====================================================================
        migrations.CreateModel(
            name='StepOverride',
            fields=[
                ('id', models.UUIDField(default=uuid7, editable=False, primary_key=True, serialize=False)),
                ('tenant', models.ForeignKey(blank=True, db_index=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('block_type', models.CharField(
                    choices=[
                        ('qa_signoff', 'QA Signoff Required'),
                        ('fpi_required', 'FPI Required'),
                        ('measurement_failed', 'Measurement Failed'),
                        ('quarantine', 'Part Quarantined'),
                        ('sampling_required', 'Sampling Required'),
                        ('batch_incomplete', 'Batch Incomplete'),
                        ('training_expired', 'Training Expired'),
                        ('calibration_expired', 'Calibration Expired'),
                        ('regulatory_hold', 'Regulatory Hold'),
                        ('other', 'Other'),
                    ],
                    help_text='Type of block being overridden',
                    max_length=30,
                )),
                ('requested_at', models.DateTimeField(auto_now_add=True, help_text='When override was requested')),
                ('reason', models.TextField(help_text='Justification for the override')),
                ('approved_at', models.DateTimeField(blank=True, help_text='When override was approved', null=True)),
                ('status', models.CharField(
                    choices=[
                        ('pending', 'Pending'),
                        ('approved', 'Approved'),
                        ('rejected', 'Rejected'),
                        ('expired', 'Expired'),
                    ],
                    default='pending',
                    help_text='Current status of the override request',
                    max_length=20,
                )),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this override expires', null=True)),
                ('used', models.BooleanField(default=False, help_text='Whether this override has been used')),
                ('used_at', models.DateTimeField(blank=True, help_text='When this override was used', null=True)),
                ('step_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='Tracker.stepexecution')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='override_requests', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, help_text='User who approved/rejected the override', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='override_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Step Override',
                'verbose_name_plural': 'Step Overrides',
                'ordering': ['-requested_at'],
            },
        ),

        # =====================================================================
        # NEW MODEL: StepExecutionMeasurement
        # =====================================================================
        migrations.CreateModel(
            name='StepExecutionMeasurement',
            fields=[
                ('id', models.UUIDField(default=uuid7, editable=False, primary_key=True, serialize=False)),
                ('tenant', models.ForeignKey(blank=True, db_index=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=4, help_text='Numeric measurement value', max_digits=12, null=True)),
                ('string_value', models.CharField(blank=True, help_text='String value for pass/fail or text measurements', max_length=100)),
                ('is_within_spec', models.BooleanField(help_text='Whether measurement is within specification (auto-calculated)', null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, help_text='When measurement was recorded')),
                ('step_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='Tracker.stepexecution')),
                ('measurement_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execution_measurements', to='Tracker.measurementdefinition')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_measurements', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(blank=True, help_text='Equipment used for measurement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='step_measurements', to='Tracker.equipments')),
            ],
            options={
                'verbose_name': 'Step Execution Measurement',
                'verbose_name_plural': 'Step Execution Measurements',
                'ordering': ['step_execution', 'recorded_at'],
            },
        ),

        # =====================================================================
        # INDEXES for new models
        # =====================================================================
        migrations.AddIndex(
            model_name='steprequirement',
            index=models.Index(fields=['step', 'requirement_type'], name='stepreq_step_type_idx'),
        ),
        migrations.AddIndex(
            model_name='fpirecord',
            index=models.Index(fields=['work_order', 'step', 'status'], name='fpi_wo_step_status_idx'),
        ),
        migrations.AddIndex(
            model_name='fpirecord',
            index=models.Index(fields=['equipment', 'shift_date'], name='fpi_equip_shift_idx'),
        ),
        migrations.AddIndex(
            model_name='stepoverride',
            index=models.Index(fields=['step_execution', 'status'], name='override_exec_status_idx'),
        ),
        migrations.AddIndex(
            model_name='stepoverride',
            index=models.Index(fields=['status', 'expires_at'], name='override_status_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='stepexecutionmeasurement',
            index=models.Index(fields=['step_execution', 'measurement_definition'], name='execmeas_exec_def_idx'),
        ),
    ]
