# Generated by Django 5.1.6 on 2026-02-20 04:11

import django.db.models.deletion
import django.utils.timezone
import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0008_step_completion_and_workflow_prep'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fpirecord',
            new_name='Tracker_fpi_work_or_1a4a9c_idx',
            old_name='fpi_wo_step_status_idx',
        ),
        migrations.RenameIndex(
            model_name='fpirecord',
            new_name='Tracker_fpi_equipme_246a07_idx',
            old_name='fpi_equip_shift_idx',
        ),
        migrations.RenameIndex(
            model_name='stepexecutionmeasurement',
            new_name='Tracker_ste_step_ex_776bea_idx',
            old_name='execmeas_exec_def_idx',
        ),
        migrations.RenameIndex(
            model_name='stepoverride',
            new_name='Tracker_ste_step_ex_776c40_idx',
            old_name='override_exec_status_idx',
        ),
        migrations.RenameIndex(
            model_name='stepoverride',
            new_name='Tracker_ste_status_b05306_idx',
            old_name='override_status_expires_idx',
        ),
        migrations.RenameIndex(
            model_name='steprequirement',
            new_name='Tracker_ste_step_id_d589de_idx',
            old_name='stepreq_step_type_idx',
        ),
        migrations.AddField(
            model_name='fpirecord',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fpirecord',
            name='is_current_version',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fpirecord',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.fpirecord'),
        ),
        migrations.AddField(
            model_name='fpirecord',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='stepexecutionmeasurement',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stepexecutionmeasurement',
            name='is_current_version',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stepexecutionmeasurement',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.stepexecutionmeasurement'),
        ),
        migrations.AddField(
            model_name='stepexecutionmeasurement',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='stepoverride',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stepoverride',
            name='is_current_version',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stepoverride',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.stepoverride'),
        ),
        migrations.AddField(
            model_name='stepoverride',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='steprequirement',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='steprequirement',
            name='is_current_version',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='steprequirement',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.steprequirement'),
        ),
        migrations.AddField(
            model_name='steprequirement',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='fpirecord',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fpirecord',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='fpirecord',
            name='id',
            field=models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fpirecord',
            name='status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed'), ('waived', 'Waived')], default='pending', help_text='Current status of the FPI', max_length=20),
        ),
        migrations.AlterField(
            model_name='parts',
            name='part_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('AWAITING_QA', 'Awaiting QA'), ('READY FOR NEXT STEP', 'Ready for next step'), ('COMPLETED', 'Completed'), ('QUARANTINED', 'Quarantined'), ('REWORK_NEEDED', 'Rework Needed'), ('REWORK_IN_PROGRESS', 'Rework In Progress'), ('SCRAPPED', 'Scrapped'), ('CANCELLED', 'Cancelled'), ('SHIPPED', 'Shipped'), ('IN_STOCK', 'In Stock'), ('AWAITING_PICKUP', 'Awaiting Pickup'), ('CORE_BANKED', 'Core Banked'), ('RMA_CLOSED', 'RMA Closed')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='stepexecution',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('claimed', 'Claimed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled'), ('rolled_back', 'Rolled Back')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='stepexecutionmeasurement',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stepexecutionmeasurement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='stepexecutionmeasurement',
            name='id',
            field=models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stepoverride',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stepoverride',
            name='block_type',
            field=models.CharField(choices=[('qa_signoff', 'QA Signoff Required'), ('fpi_required', 'FPI Required'), ('measurement_failed', 'Measurement Failed'), ('quarantine', 'Part Quarantined'), ('sampling_required', 'Sampling Required'), ('batch_incomplete', 'Batch Incomplete'), ('training_expired', 'Training Expired'), ('calibration_expired', 'Calibration Expired'), ('regulatory_hold', 'Regulatory Hold'), ('rollback', 'Step Rollback'), ('other', 'Other')], help_text='Type of block being overridden', max_length=30),
        ),
        migrations.AlterField(
            model_name='stepoverride',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='stepoverride',
            name='id',
            field=models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='steprequirement',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='steprequirement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='steprequirement',
            name='id',
            field=models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='steps',
            name='fpi_scope',
            field=models.CharField(choices=[('per_workorder', 'Per Work Order'), ('per_shift', 'Per Shift'), ('per_equipment', 'Per Equipment'), ('per_operator', 'Per Operator')], default='per_workorder', help_text='Scope at which FPI applies', max_length=20),
        ),
    ]
