# Generated by Django 5.1.6 on 2026-02-20 16:34

import django.db.models.deletion
import django.utils.timezone
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0009_rollback_support'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepRollback',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('reason', models.CharField(choices=[('operator_error', 'Operator Error'), ('data_entry_error', 'Data Entry Error'), ('wrong_decision', 'Wrong Decision Path'), ('defect_found', 'Defect Found Later'), ('rework_required', 'Rework Required'), ('equipment_issue', 'Equipment Issue Discovered'), ('process_deviation', 'Process Deviation'), ('engineering_request', 'Engineering Request'), ('customer_rejection', 'Customer Rejection'), ('other', 'Other')], help_text='Reason category for the rollback', max_length=30)),
                ('reason_detail', models.TextField(help_text='Detailed explanation for the rollback')),
                ('voided_executions', models.JSONField(default=list, help_text='StepExecution IDs that were voided')),
                ('voided_quality_reports', models.JSONField(default=list, help_text='QualityReport IDs that were voided')),
                ('voided_measurements', models.JSONField(default=list, help_text='StepExecutionMeasurement IDs that were voided')),
                ('preserve_measurements', models.BooleanField(default=False, help_text='If True, measurements at target step are preserved')),
                ('require_re_inspection', models.BooleanField(default=True, help_text='If True, part is re-flagged for sampling at target step')),
                ('require_re_fpi', models.BooleanField(default=False, help_text='If True, FPI must be redone')),
                ('requested_at', models.DateTimeField(auto_now_add=True, help_text='When rollback was requested')),
                ('approved_at', models.DateTimeField(blank=True, help_text='When rollback was approved', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('executed', 'Executed'), ('rejected', 'Rejected')], default='pending', help_text='Current status of the rollback', max_length=20)),
                ('executed_at', models.DateTimeField(blank=True, help_text='When rollback was executed', null=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='User who approved/rejected the rollback', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rollback_approvals', to=settings.AUTH_USER_MODEL)),
                ('executed_by', models.ForeignKey(blank=True, help_text='User who executed the rollback', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rollback_executions', to=settings.AUTH_USER_MODEL)),
                ('from_step', models.ForeignKey(help_text='Step the part was at before rollback', on_delete=django.db.models.deletion.PROTECT, related_name='rollbacks_from', to='Tracker.steps')),
                ('ncr_reference', models.ForeignKey(blank=True, help_text='Related NCR/CAPA if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_rollbacks', to='Tracker.capa')),
                ('part', models.ForeignKey(help_text='Part that was rolled back', on_delete=django.db.models.deletion.CASCADE, related_name='rollbacks', to='Tracker.parts')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.steprollback')),
                ('requested_by', models.ForeignKey(help_text='User who requested the rollback', on_delete=django.db.models.deletion.PROTECT, related_name='rollback_requests', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant')),
                ('to_step', models.ForeignKey(help_text='Step the part was rolled back to', on_delete=django.db.models.deletion.PROTECT, related_name='rollbacks_to', to='Tracker.steps')),
            ],
            options={
                'verbose_name': 'Step Rollback',
                'verbose_name_plural': 'Step Rollbacks',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchRollback',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('selection_criteria', models.JSONField(default=dict, help_text='How parts were selected (for audit)')),
                ('reason', models.CharField(choices=[('operator_error', 'Operator Error'), ('data_entry_error', 'Data Entry Error'), ('wrong_decision', 'Wrong Decision Path'), ('defect_found', 'Defect Found Later'), ('rework_required', 'Rework Required'), ('equipment_issue', 'Equipment Issue Discovered'), ('process_deviation', 'Process Deviation'), ('engineering_request', 'Engineering Request'), ('customer_rejection', 'Customer Rejection'), ('other', 'Other')], help_text='Reason category for the rollback', max_length=30)),
                ('reason_detail', models.TextField(help_text='Detailed explanation for the rollback')),
                ('requested_at', models.DateTimeField(auto_now_add=True, help_text='When batch rollback was requested')),
                ('approved_at', models.DateTimeField(blank=True, help_text='When batch rollback was approved', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('executed', 'Executed'), ('rejected', 'Rejected')], default='pending', help_text='Current status of the batch rollback', max_length=20)),
                ('executed_at', models.DateTimeField(blank=True, help_text='When batch rollback was executed', null=True)),
                ('affected_parts', models.ManyToManyField(help_text='Parts included in this batch rollback', related_name='batch_rollbacks', to='Tracker.parts')),
                ('approved_by', models.ForeignKey(blank=True, help_text='User who approved/rejected the batch rollback', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batch_rollback_approvals', to=settings.AUTH_USER_MODEL)),
                ('executed_by', models.ForeignKey(blank=True, help_text='User who executed the batch rollback', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batch_rollback_executions', to=settings.AUTH_USER_MODEL)),
                ('ncr_reference', models.ForeignKey(blank=True, help_text='Related NCR/CAPA if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_batch_rollbacks', to='Tracker.capa')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.batchrollback')),
                ('requested_by', models.ForeignKey(help_text='User who requested the batch rollback', on_delete=django.db.models.deletion.PROTECT, related_name='batch_rollback_requests', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant')),
                ('to_step', models.ForeignKey(help_text='Target step for rollback', on_delete=django.db.models.deletion.PROTECT, related_name='batch_rollbacks_to', to='Tracker.steps')),
                ('work_order', models.ForeignKey(help_text='Work order containing affected parts', on_delete=django.db.models.deletion.CASCADE, related_name='batch_rollbacks', to='Tracker.workorder')),
                ('individual_rollbacks', models.ManyToManyField(blank=True, help_text='Individual StepRollback records created for each part', related_name='batch_rollback', to='Tracker.steprollback')),
            ],
            options={
                'verbose_name': 'Batch Rollback',
                'verbose_name_plural': 'Batch Rollbacks',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='RecordEdit',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('object_id', models.UUIDField(help_text='ID of the edited record')),
                ('field_name', models.CharField(help_text='Name of the field that was edited', max_length=100)),
                ('old_value', models.TextField(blank=True, help_text='Previous value (serialized)')),
                ('new_value', models.TextField(blank=True, help_text='New value (serialized)')),
                ('reason', models.TextField(help_text='Reason for the edit')),
                ('edited_at', models.DateTimeField(auto_now_add=True, help_text='When the edit was made')),
                ('content_type', models.ForeignKey(help_text='Type of the edited record', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('edited_by', models.ForeignKey(help_text='User who made the edit', on_delete=django.db.models.deletion.PROTECT, related_name='record_edits', to=settings.AUTH_USER_MODEL)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.recordedit')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant')),
            ],
            options={
                'verbose_name': 'Record Edit',
                'verbose_name_plural': 'Record Edits',
                'ordering': ['-edited_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='Tracker_rec_content_10ebe7_idx'), models.Index(fields=['edited_by', 'edited_at'], name='Tracker_rec_edited__c1ae1b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='steprollback',
            index=models.Index(fields=['part', 'status'], name='Tracker_ste_part_id_b6f930_idx'),
        ),
        migrations.AddIndex(
            model_name='steprollback',
            index=models.Index(fields=['status', 'requested_at'], name='Tracker_ste_status_27ba99_idx'),
        ),
    ]
