# Generated by Django 5.1.6 on 2026-03-01 00:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid_utils.compat
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0010_steprollback_batchrollback_recordedit_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementdefinition',
            name='spc_enabled',
            field=models.BooleanField(default=False, help_text='Enable SPC monitoring for this measurement. When enabled, values are checked against active SPCBaseline control limits.'),
        ),
        migrations.AddField(
            model_name='steps',
            name='block_on_spc_violation',
            field=models.BooleanField(default=False, help_text='If True, parts cannot advance if any SPC-enabled measurement is out of control'),
        ),
        migrations.CreateModel(
            name='LifeLimitDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('name', models.CharField(help_text="Display name (e.g., 'Flight Cycles', 'Shelf Life')", max_length=100)),
                ('unit', models.CharField(help_text="Unit being tracked (e.g., 'cycles', 'hours', 'days')", max_length=50)),
                ('unit_label', models.CharField(help_text="Display label (e.g., 'Cycles', 'Flight Hours', 'Days')", max_length=50)),
                ('is_calendar_based', models.BooleanField(default=False, help_text='If true, value is calculated from reference_date. Valid units for calendar-based: days, months, years')),
                ('soft_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Warning/overhaul threshold', max_digits=12, null=True)),
                ('hard_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Absolute limit - block/retire when reached', max_digits=12, null=True)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.lifelimitdefinition')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant')),
            ],
            options={
                'verbose_name': 'Life Limit Definition',
                'verbose_name_plural': 'Life Limit Definitions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LifeTracking',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('object_id', models.UUIDField()),
                ('accumulated', models.DecimalField(decimal_places=2, default=0, help_text='Current accumulated value', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('reference_date', models.DateField(blank=True, help_text='For calendar-based: manufacture/install/overhaul date', null=True)),
                ('source', models.CharField(choices=[('oem', 'OEM Records'), ('customer', 'Customer Provided'), ('logbook', 'Logbook Entry'), ('calculated', 'Calculated'), ('estimated', 'Estimated'), ('transferred', 'Transferred from Core'), ('reset', 'Reset After Rebuild')], default='estimated', help_text='Where did this life data come from?', max_length=20)),
                ('cached_status', models.CharField(db_index=True, default='ok', help_text='Cached status, updated on save', max_length=10)),
                ('hard_limit_override', models.DecimalField(blank=True, decimal_places=2, help_text='Override hard limit for this specific instance', max_digits=12, null=True)),
                ('soft_limit_override', models.DecimalField(blank=True, decimal_places=2, help_text='Override soft limit for this specific instance', max_digits=12, null=True)),
                ('override_reason', models.CharField(blank=True, help_text='Reason for limit override', max_length=200)),
                ('reset_history', models.JSONField(blank=True, default=list, help_text='History of resets/overhauls')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracking_records', to='Tracker.lifelimitdefinition')),
                ('override_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_life_overrides', to=settings.AUTH_USER_MODEL)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.lifetracking')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant')),
            ],
            options={
                'verbose_name': 'Life Tracking',
                'verbose_name_plural': 'Life Tracking Records',
            },
        ),
        migrations.CreateModel(
            name='PartTypeLifeLimit',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('is_required', models.BooleanField(default=True, help_text='If true, parts of this type must have this tracking')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_type_links', to='Tracker.lifelimitdefinition')),
                ('part_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='life_limits', to='Tracker.parttypes')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.parttypelifelimit')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant')),
            ],
            options={
                'verbose_name': 'Part Type Life Limit',
                'verbose_name_plural': 'Part Type Life Limits',
            },
        ),
        migrations.AddConstraint(
            model_name='lifelimitdefinition',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='life_limit_def_tenant_name_uniq'),
        ),
        migrations.AddIndex(
            model_name='lifetracking',
            index=models.Index(fields=['content_type', 'object_id'], name='Tracker_lif_content_275e7f_idx'),
        ),
        migrations.AddConstraint(
            model_name='lifetracking',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id', 'definition'), name='life_tracking_entity_definition_uniq'),
        ),
        migrations.AddConstraint(
            model_name='parttypelifelimit',
            constraint=models.UniqueConstraint(fields=('part_type', 'definition'), name='part_type_life_limit_uniq'),
        ),
    ]
