# Generated by Django 5.1.6 on 2026-03-02 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0011_life_tracking_and_spc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['name'], 'permissions': [('full_tenant_access', 'Has full visibility to all tenant data (without this, users only see data related to their orders)'), ('view_auditlog', 'Can view audit log entries'), ('export_auditlog', 'Can export audit log data'), ('verify_export_control', 'Can verify export control compliance'), ('change_export_classification', 'Can change export classification'), ('export_data', 'Can export data from the system')], 'verbose_name': 'Tenant', 'verbose_name_plural': 'Tenants'},
        ),
    ]
