# Generated by Django 5.1.6 on 2026-03-05 18:08

import django.db.models.deletion
import django.utils.timezone
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0012_add_system_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capa',
            name='capa_type',
            field=models.CharField(choices=[('corrective', 'Corrective Action'), ('preventive', 'Preventive Action'), ('customer_complaint', 'Customer Complaint'), ('internal_audit', 'Internal Audit'), ('supplier', 'Supplier Issue')], max_length=30),
        ),
        migrations.AlterField(
            model_name='capa',
            name='severity',
            field=models.CharField(choices=[('critical', 'Critical'), ('major', 'Major'), ('minor', 'Minor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='capa',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('pending_verification', 'Pending Verification'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=30),
        ),
        migrations.AlterField(
            model_name='capataskassignee',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='capatasks',
            name='completion_mode',
            field=models.CharField(choices=[('single_owner', 'Single Owner'), ('any_assignee', 'Any Assignee'), ('all_assignees', 'All Assignees')], default='single_owner', max_length=20),
        ),
        migrations.AlterField(
            model_name='capatasks',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='capatasks',
            name='task_type',
            field=models.CharField(choices=[('containment', 'Containment'), ('corrective', 'Corrective Action'), ('preventive', 'Preventive Action')], max_length=20),
        ),
        migrations.AlterField(
            model_name='capaverification',
            name='effectiveness_result',
            field=models.CharField(choices=[('confirmed', 'Confirmed Effective'), ('not_effective', 'Not Effective'), ('inconclusive', 'Inconclusive')], default='inconclusive', max_length=20),
        ),
        migrations.AlterField(
            model_name='generatedreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('rfi', 'RFI'), ('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('on_hold', 'On hold'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='parts',
            name='part_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('awaiting_qa', 'Awaiting QA'), ('ready_for_next_step', 'Ready for next step'), ('completed', 'Completed'), ('quarantined', 'Quarantined'), ('rework_needed', 'Rework Needed'), ('rework_in_progress', 'Rework In Progress'), ('scrapped', 'Scrapped'), ('cancelled', 'Cancelled'), ('shipped', 'Shipped'), ('in_stock', 'In Stock'), ('awaiting_pickup', 'Awaiting Pickup'), ('core_banked', 'Core Banked'), ('rma_closed', 'RMA Closed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='rcarecord',
            name='rca_method',
            field=models.CharField(choices=[('five_whys', '5 Whys'), ('fishbone', 'Fishbone Diagram'), ('fault_tree', 'Fault Tree'), ('pareto', 'Pareto Analysis')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rcarecord',
            name='rca_review_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('required', 'Required'), ('completed', 'Completed')], default='not_required', max_length=20),
        ),
        migrations.AlterField(
            model_name='rcarecord',
            name='root_cause_verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified'), ('disputed', 'Disputed')], default='unverified', max_length=20),
        ),
        migrations.AlterField(
            model_name='rootcause',
            name='category',
            field=models.CharField(choices=[('man', 'Man (People)'), ('machine', 'Machine (Equipment)'), ('material', 'Material'), ('method', 'Method (Process)'), ('measurement', 'Measurement'), ('environment', 'Environment'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rootcause',
            name='role',
            field=models.CharField(choices=[('primary', 'Primary'), ('contributing', 'Contributing')], default='primary', max_length=20),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='workorder_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('on_hold', 'On hold'), ('cancelled', 'Cancelled'), ('waiting_for_operator', 'Waiting for operator')], default='pending', max_length=50),
        ),
        migrations.CreateModel(
            name='CapaStatusTransition',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('from_status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('pending_verification', 'Pending Verification'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], help_text='Status before transition', max_length=30)),
                ('to_status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('pending_verification', 'Pending Verification'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], help_text='Status after transition', max_length=30)),
                ('notes', models.TextField(blank=True, help_text='Reason or notes for the transition')),
                ('capa', models.ForeignKey(help_text='The CAPA that was transitioned', on_delete=django.db.models.deletion.CASCADE, related_name='status_transitions', to='Tracker.capa')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.capastatustransition')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant')),
                ('transitioned_by', models.ForeignKey(help_text='User who performed the transition', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capa_transitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CAPA Status Transition',
                'verbose_name_plural': 'CAPA Status Transitions',
                'ordering': ['-created_at'],
            },
        ),
    ]
