# Generated by Django 5.1.6 on 2026-03-06 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0013_add_capa_status_transition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchrollback',
            name='reason',
            field=models.CharField(choices=[('OPERATOR_ERROR', 'Operator Error'), ('DATA_ENTRY_ERROR', 'Data Entry Error'), ('WRONG_DECISION', 'Wrong Decision Path'), ('DEFECT_FOUND', 'Defect Found Later'), ('REWORK_REQUIRED', 'Rework Required'), ('EQUIPMENT_ISSUE', 'Equipment Issue Discovered'), ('PROCESS_DEVIATION', 'Process Deviation'), ('ENGINEERING_REQUEST', 'Engineering Request'), ('CUSTOMER_REJECTION', 'Customer Rejection'), ('OTHER', 'Other')], help_text='Reason category for the rollback', max_length=30),
        ),
        migrations.AlterField(
            model_name='batchrollback',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('EXECUTED', 'Executed'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Current status of the batch rollback', max_length=20),
        ),
        migrations.AlterField(
            model_name='bom',
            name='bom_type',
            field=models.CharField(choices=[('ASSEMBLY', 'Assembly'), ('DISASSEMBLY', 'Disassembly')], default='ASSEMBLY', max_length=20),
        ),
        migrations.AlterField(
            model_name='bom',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('RELEASED', 'Released'), ('OBSOLETE', 'Obsolete')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='calibrationrecord',
            name='calibration_type',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('INITIAL', 'Initial'), ('AFTER_REPAIR', 'After Repair'), ('AFTER_ADJUSTMENT', 'After Adjustment'), ('VERIFICATION', 'Verification Check')], default='SCHEDULED', max_length=20),
        ),
        migrations.AlterField(
            model_name='calibrationrecord',
            name='result',
            field=models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('LIMITED', 'Limited/Restricted Use')], default='PASS', max_length=10),
        ),
        migrations.AlterField(
            model_name='capa',
            name='approval_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_required', help_text='Approval workflow status', max_length=20),
        ),
        migrations.AlterField(
            model_name='capa',
            name='capa_type',
            field=models.CharField(choices=[('CORRECTIVE', 'Corrective Action'), ('PREVENTIVE', 'Preventive Action'), ('CUSTOMER_COMPLAINT', 'Customer Complaint'), ('INTERNAL_AUDIT', 'Internal Audit'), ('SUPPLIER', 'Supplier Issue')], max_length=30),
        ),
        migrations.AlterField(
            model_name='capa',
            name='severity',
            field=models.CharField(choices=[('CRITICAL', 'Critical'), ('MAJOR', 'Major'), ('MINOR', 'Minor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='capa',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('PENDING_VERIFICATION', 'Pending Verification'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=30),
        ),
        migrations.AlterField(
            model_name='capastatustransition',
            name='from_status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('PENDING_VERIFICATION', 'Pending Verification'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], help_text='Status before transition', max_length=30),
        ),
        migrations.AlterField(
            model_name='capastatustransition',
            name='to_status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('PENDING_VERIFICATION', 'Pending Verification'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], help_text='Status after transition', max_length=30),
        ),
        migrations.AlterField(
            model_name='capataskassignee',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='capatasks',
            name='completion_mode',
            field=models.CharField(choices=[('SINGLE_OWNER', 'Single Owner'), ('ANY_ASSIGNEE', 'Any Assignee'), ('ALL_ASSIGNEES', 'All Assignees')], default='SINGLE_OWNER', max_length=20),
        ),
        migrations.AlterField(
            model_name='capatasks',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='capatasks',
            name='task_type',
            field=models.CharField(choices=[('CONTAINMENT', 'Containment'), ('CORRECTIVE', 'Corrective Action'), ('PREVENTIVE', 'Preventive Action')], max_length=20),
        ),
        migrations.AlterField(
            model_name='capaverification',
            name='effectiveness_result',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed Effective'), ('NOT_EFFECTIVE', 'Not Effective'), ('INCONCLUSIVE', 'Inconclusive')], default='INCONCLUSIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='core',
            name='source_type',
            field=models.CharField(choices=[('CUSTOMER_RETURN', 'Customer Return'), ('PURCHASED', 'Purchased Core'), ('WARRANTY', 'Warranty Return'), ('TRADE_IN', 'Trade-In')], default='CUSTOMER_RETURN', max_length=20),
        ),
        migrations.AlterField(
            model_name='core',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('IN_DISASSEMBLY', 'In Disassembly'), ('DISASSEMBLED', 'Disassembled'), ('SCRAPPED', 'Scrapped')], default='RECEIVED', max_length=20),
        ),
        migrations.AlterField(
            model_name='documents',
            name='classification',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('INTERNAL', 'Internal Use'), ('CONFIDENTIAL', 'Confidential'), ('RESTRICTED', 'Restricted'), ('SECRET', 'Secret')], default='INTERNAL', help_text='Security classification level for document access control', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('released', 'Released'), ('obsolete', 'Obsolete')], default='draft', help_text='Document workflow status', max_length=20),
        ),
        migrations.AlterField(
            model_name='downtimeevent',
            name='category',
            field=models.CharField(choices=[('PLANNED', 'Planned Maintenance'), ('UNPLANNED', 'Unplanned/Breakdown'), ('CHANGEOVER', 'Changeover/Setup'), ('CALIBRATION', 'Calibration'), ('NO_WORK', 'No Work Available'), ('NO_OPERATOR', 'No Operator Available'), ('MATERIAL', 'Waiting for Material'), ('QUALITY', 'Quality Issue'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='equipments',
            name='status',
            field=models.CharField(choices=[('IN_SERVICE', 'In Service'), ('OUT_OF_SERVICE', 'Out of Service'), ('IN_CALIBRATION', 'In Calibration'), ('IN_MAINTENANCE', 'In Maintenance'), ('RETIRED', 'Retired')], default='IN_SERVICE', max_length=20),
        ),
        migrations.AlterField(
            model_name='fpirecord',
            name='result',
            field=models.CharField(blank=True, choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('CONDITIONAL', 'Conditional Pass')], help_text='Final result of the FPI', max_length=20),
        ),
        migrations.AlterField(
            model_name='fpirecord',
            name='status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('PENDING', 'Pending'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('WAIVED', 'Waived')], default='PENDING', help_text='Current status of the FPI', max_length=20),
        ),
        migrations.AlterField(
            model_name='generatedreport',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='lifetracking',
            name='cached_status',
            field=models.CharField(db_index=True, default='OK', help_text='Cached status, updated on save', max_length=10),
        ),
        migrations.AlterField(
            model_name='lifetracking',
            name='source',
            field=models.CharField(choices=[('OEM', 'OEM Records'), ('CUSTOMER', 'Customer Provided'), ('LOGBOOK', 'Logbook Entry'), ('CALCULATED', 'Calculated'), ('ESTIMATED', 'Estimated'), ('TRANSFERRED', 'Transferred from Core'), ('RESET', 'Reset After Rebuild')], default='ESTIMATED', help_text='Where did this life data come from?', max_length=20),
        ),
        migrations.AlterField(
            model_name='materiallot',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('IN_USE', 'In Use'), ('CONSUMED', 'Consumed'), ('SCRAPPED', 'Scrapped'), ('QUARANTINE', 'Quarantine')], default='RECEIVED', max_length=20),
        ),
        migrations.AlterField(
            model_name='measurementdefinition',
            name='type',
            field=models.CharField(choices=[('numeric', 'Numeric'), ('pass_fail', 'Pass/Fail')], max_length=20),
        ),
        migrations.AlterField(
            model_name='measurementresult',
            name='value_pass_fail',
            field=models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='notificationtask',
            name='notification_type',
            field=models.CharField(choices=[('weekly_report', 'Weekly Order Report'), ('capa_reminder', 'CAPA Reminder'), ('approval_request', 'Approval Request'), ('approval_decision', 'Approval Decision'), ('approval_escalation', 'Approval Escalation')], max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('RFI', 'RFI'), ('PENDING', 'Pending'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On hold'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderviewer',
            name='invitation_type',
            field=models.CharField(choices=[('DIRECT', 'Direct Invitation'), ('COMPANY', 'Company Member'), ('STAFF', 'Staff Assigned')], default='DIRECT', max_length=20),
        ),
        migrations.AlterField(
            model_name='parts',
            name='part_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('AWAITING_QA', 'Awaiting QA'), ('READY_FOR_NEXT_STEP', 'Ready for next step'), ('COMPLETED', 'Completed'), ('QUARANTINED', 'Quarantined'), ('REWORK_NEEDED', 'Rework Needed'), ('REWORK_IN_PROGRESS', 'Rework In Progress'), ('SCRAPPED', 'Scrapped'), ('CANCELLED', 'Cancelled'), ('SHIPPED', 'Shipped'), ('IN_STOCK', 'In Stock'), ('AWAITING_PICKUP', 'Awaiting Pickup'), ('CORE_BANKED', 'Core Banked'), ('RMA_CLOSED', 'RMA Closed')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='processes',
            name='category',
            field=models.CharField(choices=[('MANUFACTURING', 'Manufacturing'), ('QUALITY', 'Quality'), ('MAINTENANCE', 'Maintenance'), ('NPI', 'New Product Introduction'), ('DOCUMENT', 'Document Control')], default='MANUFACTURING', help_text='Process category for workflow engine routing', max_length=20),
        ),
        migrations.AlterField(
            model_name='processes',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('DEPRECATED', 'Deprecated')], default='DRAFT', help_text='Controls editability and availability for work orders', max_length=20),
        ),
        migrations.AlterField(
            model_name='qualityreportdefect',
            name='severity',
            field=models.CharField(choices=[('MINOR', 'Minor'), ('MAJOR', 'Major'), ('CRITICAL', 'Critical')], default='MAJOR', help_text='Severity of this specific defect instance', max_length=20),
        ),
        migrations.AlterField(
            model_name='qualityreports',
            name='status',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('pending', 'Pending')], max_length=10),
        ),
        migrations.AlterField(
            model_name='quarantinedisposition',
            name='current_state',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=15),
        ),
        migrations.AlterField(
            model_name='quarantinedisposition',
            name='disposition_type',
            field=models.CharField(blank=True, choices=[('rework', 'Rework'), ('repair', 'Repair'), ('scrap', 'Scrap'), ('use_as_is', 'Use As Is'), ('return_to_supplier', 'Return to Supplier')], max_length=20),
        ),
        migrations.AlterField(
            model_name='quarantinedisposition',
            name='severity',
            field=models.CharField(choices=[('critical', 'Critical'), ('major', 'Major'), ('minor', 'Minor')], default='major', max_length=10),
        ),
        migrations.AlterField(
            model_name='rcarecord',
            name='rca_method',
            field=models.CharField(choices=[('FIVE_WHYS', '5 Whys'), ('FISHBONE', 'Fishbone Diagram'), ('FAULT_TREE', 'Fault Tree'), ('PARETO', 'Pareto Analysis')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rcarecord',
            name='rca_review_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('REQUIRED', 'Required'), ('COMPLETED', 'Completed')], default='NOT_REQUIRED', max_length=20),
        ),
        migrations.AlterField(
            model_name='rcarecord',
            name='root_cause_verification_status',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('VERIFIED', 'Verified'), ('DISPUTED', 'Disputed')], default='UNVERIFIED', max_length=20),
        ),
        migrations.AlterField(
            model_name='rootcause',
            name='category',
            field=models.CharField(choices=[('MAN', 'Man (People)'), ('MACHINE', 'Machine (Equipment)'), ('MATERIAL', 'Material'), ('METHOD', 'Method (Process)'), ('MEASUREMENT', 'Measurement'), ('ENVIRONMENT', 'Environment'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rootcause',
            name='role',
            field=models.CharField(choices=[('PRIMARY', 'Primary'), ('CONTRIBUTING', 'Contributing')], default='PRIMARY', max_length=20),
        ),
        migrations.AlterField(
            model_name='samplingrule',
            name='rule_type',
            field=models.CharField(choices=[('EVERY_NTH_PART', 'Every Nth Part'), ('PERCENTAGE', 'Percentage of Parts'), ('RANDOM', 'Pure Random'), ('FIRST_N_PARTS', 'First N Parts'), ('LAST_N_PARTS', 'Last N Parts'), ('EXACT_COUNT', 'Exact Count (No Variance)')], max_length=32),
        ),
        migrations.AlterField(
            model_name='scheduleslot',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20),
        ),
        migrations.AlterField(
            model_name='stepedge',
            name='edge_type',
            field=models.CharField(choices=[('DEFAULT', 'Default/Pass'), ('ALTERNATE', 'Alternate/Fail'), ('ESCALATION', 'Escalation')], default='DEFAULT', max_length=20),
        ),
        migrations.AlterField(
            model_name='stepexecution',
            name='fpi_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('PENDING', 'Pending'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('WAIVED', 'Waived')], default='NOT_REQUIRED', help_text='First Piece Inspection status for this execution', max_length=20),
        ),
        migrations.AlterField(
            model_name='stepexecution',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CLAIMED', 'Claimed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped'), ('CANCELLED', 'Cancelled'), ('ROLLED_BACK', 'Rolled Back')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='stepoverride',
            name='block_type',
            field=models.CharField(choices=[('QA_SIGNOFF', 'QA Signoff Required'), ('FPI_REQUIRED', 'FPI Required'), ('MEASUREMENT_FAILED', 'Measurement Failed'), ('QUARANTINE', 'Part Quarantined'), ('SAMPLING_REQUIRED', 'Sampling Required'), ('BATCH_INCOMPLETE', 'Batch Incomplete'), ('TRAINING_EXPIRED', 'Training Expired'), ('CALIBRATION_EXPIRED', 'Calibration Expired'), ('REGULATORY_HOLD', 'Regulatory Hold'), ('ROLLBACK', 'Step Rollback'), ('OTHER', 'Other')], help_text='Type of block being overridden', max_length=30),
        ),
        migrations.AlterField(
            model_name='stepoverride',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', help_text='Current status of the override request', max_length=20),
        ),
        migrations.AlterField(
            model_name='steprequirement',
            name='requirement_type',
            field=models.CharField(choices=[('MEASUREMENT', 'Measurement'), ('DOCUMENT', 'Document'), ('SIGNOFF', 'Signoff'), ('EQUIPMENT_CHECK', 'Equipment Check'), ('MATERIAL_SCAN', 'Material Scan'), ('TRAINING_VALID', 'Training Valid'), ('CALIBRATION_VALID', 'Calibration Valid'), ('FPI_PASSED', 'FPI Passed'), ('QA_APPROVAL', 'QA Approval'), ('CUSTOM', 'Custom')], help_text='Type of requirement', max_length=30),
        ),
        migrations.AlterField(
            model_name='steprollback',
            name='reason',
            field=models.CharField(choices=[('OPERATOR_ERROR', 'Operator Error'), ('DATA_ENTRY_ERROR', 'Data Entry Error'), ('WRONG_DECISION', 'Wrong Decision Path'), ('DEFECT_FOUND', 'Defect Found Later'), ('REWORK_REQUIRED', 'Rework Required'), ('EQUIPMENT_ISSUE', 'Equipment Issue Discovered'), ('PROCESS_DEVIATION', 'Process Deviation'), ('ENGINEERING_REQUEST', 'Engineering Request'), ('CUSTOMER_REJECTION', 'Customer Rejection'), ('OTHER', 'Other')], help_text='Reason category for the rollback', max_length=30),
        ),
        migrations.AlterField(
            model_name='steprollback',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('EXECUTED', 'Executed'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Current status of the rollback', max_length=20),
        ),
        migrations.AlterField(
            model_name='steps',
            name='decision_type',
            field=models.CharField(blank=True, choices=[('QA_RESULT', 'Based on QA Pass/Fail'), ('MEASUREMENT', 'Based on Measurement Threshold'), ('MANUAL', 'Manual Operator Selection')], max_length=20),
        ),
        migrations.AlterField(
            model_name='steps',
            name='fpi_scope',
            field=models.CharField(choices=[('PER_WORKORDER', 'Per Work Order'), ('PER_SHIFT', 'Per Shift'), ('PER_EQUIPMENT', 'Per Equipment'), ('PER_OPERATOR', 'Per Operator')], default='PER_WORKORDER', help_text='Scope at which FPI applies', max_length=20),
        ),
        migrations.AlterField(
            model_name='steps',
            name='revisit_assignment',
            field=models.CharField(choices=[('ANY', 'Any Qualified Operator'), ('SAME', 'Same as Previous'), ('DIFFERENT', 'Different Operator'), ('ROLE', 'Specific Role')], default='ANY', max_length=20),
        ),
        migrations.AlterField(
            model_name='steps',
            name='step_type',
            field=models.CharField(choices=[('TASK', 'Task'), ('START', 'Start'), ('DECISION', 'Decision'), ('REWORK', 'Rework'), ('TIMER', 'Timer/Wait'), ('TERMINAL', 'Terminal')], default='TASK', help_text='Visual type for flow editor.', max_length=20),
        ),
        migrations.AlterField(
            model_name='steps',
            name='terminal_status',
            field=models.CharField(blank=True, choices=[('COMPLETED', 'Completed Successfully'), ('SHIPPED', 'Shipped to Customer'), ('STOCK', 'Put into Inventory'), ('SCRAPPED', 'Scrapped'), ('RETURNED', 'Returned to Supplier'), ('AWAITING_PICKUP', 'Awaiting Customer Pickup'), ('CORE_BANKED', 'Core Banked'), ('RMA_CLOSED', 'RMA Closed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='threedmodel',
            name='processing_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', help_text='Current processing state', max_length=20),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='entry_type',
            field=models.CharField(choices=[('PRODUCTION', 'Production'), ('SETUP', 'Setup/Changeover'), ('REWORK', 'Rework'), ('DOWNTIME', 'Downtime'), ('INDIRECT', 'Indirect Labor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('INTERNAL', 'Internal'), ('PORTAL', 'Portal')], default='INTERNAL', help_text='Type of user account', max_length=20),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='workorder_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On hold'), ('CANCELLED', 'Cancelled'), ('WAITING_FOR_OPERATOR', 'Waiting for operator')], default='PENDING', max_length=50),
        ),
    ]
