# Generated by Django 5.1.6 on 2026-03-09 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0014_alter_batchrollback_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capa',
            name='approval_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NOT_REQUIRED', help_text='Approval workflow status', max_length=20),
        ),
        migrations.AlterField(
            model_name='documents',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('RELEASED', 'Released'), ('OBSOLETE', 'Obsolete')], default='DRAFT', help_text='Document workflow status', max_length=20),
        ),
        migrations.AlterField(
            model_name='heatmapannotations',
            name='severity',
            field=models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hubspotsynclog',
            name='status',
            field=models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='RUNNING', max_length=20),
        ),
        migrations.AlterField(
            model_name='hubspotsynclog',
            name='sync_type',
            field=models.CharField(choices=[('FULL', 'Full Sync'), ('INCREMENTAL', 'Incremental Sync'), ('SINGLE', 'Single Deal Sync')], default='FULL', max_length=20),
        ),
        migrations.AlterField(
            model_name='measurementdefinition',
            name='type',
            field=models.CharField(choices=[('NUMERIC', 'Numeric'), ('PASS_FAIL', 'Pass/Fail')], max_length=20),
        ),
        migrations.AlterField(
            model_name='measurementresult',
            name='value_pass_fail',
            field=models.CharField(blank=True, choices=[('PASS', 'Pass'), ('FAIL', 'Fail')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='notificationtask',
            name='channel_type',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('IN_APP', 'In-App Notification'), ('SMS', 'SMS')], default='EMAIL', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationtask',
            name='interval_type',
            field=models.CharField(choices=[('FIXED', 'Fixed Interval'), ('DEADLINE_BASED', 'Deadline Based')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationtask',
            name='notification_type',
            field=models.CharField(choices=[('WEEKLY_REPORT', 'Weekly Order Report'), ('CAPA_REMINDER', 'CAPA Reminder'), ('APPROVAL_REQUEST', 'Approval Request'), ('APPROVAL_DECISION', 'Approval Decision'), ('APPROVAL_ESCALATION', 'Approval Escalation')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationtask',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='qualityreports',
            name='status',
            field=models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('PENDING', 'Pending')], max_length=10),
        ),
        migrations.AlterField(
            model_name='quarantinedisposition',
            name='current_state',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('CLOSED', 'Closed')], default='OPEN', max_length=15),
        ),
        migrations.AlterField(
            model_name='quarantinedisposition',
            name='disposition_type',
            field=models.CharField(blank=True, choices=[('REWORK', 'Rework'), ('REPAIR', 'Repair'), ('SCRAP', 'Scrap'), ('USE_AS_IS', 'Use As Is'), ('RETURN_TO_SUPPLIER', 'Return to Supplier')], max_length=20),
        ),
        migrations.AlterField(
            model_name='quarantinedisposition',
            name='severity',
            field=models.CharField(choices=[('CRITICAL', 'Critical'), ('MAJOR', 'Major'), ('MINOR', 'Minor')], default='MAJOR', max_length=10),
        ),
        migrations.AlterField(
            model_name='stepexecution',
            name='decision_result',
            field=models.CharField(blank=True, help_text="Result of decision: 'PASS', 'FAIL', measurement value, etc.", max_length=50),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('TRIAL', 'Trial'), ('SUSPENDED', 'Suspended'), ('PENDING_DELETION', 'Pending Deletion')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='tier',
            field=models.CharField(choices=[('STARTER', 'Starter'), ('PRO', 'Pro'), ('ENTERPRISE', 'Enterprise')], default='STARTER', max_length=20),
        ),
    ]
