# Generated by Django 5.1.6 on 2026-03-10 16:22

import django.db.models.deletion
import django.utils.timezone
import encrypted_model_fields.fields
import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0015_alter_capa_approval_status_alter_documents_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantLLMProvider',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('ollama', 'Ollama (Local/Self-hosted)'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic')], help_text='LLM provider type', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='Use this provider as the default for AI features')),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this provider configuration is active')),
                ('model_name', models.CharField(help_text="Model identifier (e.g., 'gpt-4o', 'claude-3-5-sonnet-20240620', 'llama3')", max_length=100)),
                ('base_url', models.URLField(blank=True, default='', help_text="Base URL for Ollama server (e.g., 'http://localhost:11434')")),
                ('api_key', encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', help_text='API key (encrypted at rest)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_providers', to='Tracker.tenant')),
            ],
            options={
                'verbose_name': 'Tenant LLM Provider',
                'verbose_name_plural': 'Tenant LLM Providers',
                'db_table': 'tracker_tenant_llm_provider',
                'ordering': ['-is_default', 'provider'],
                'unique_together': {('tenant', 'provider')},
            },
        ),
    ]
