# Generated by Django 5.1.6 on 2026-04-20 02:58

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0027_milestonetemplate_partial_unique'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='Admin-friendly label shown in the rule list.', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('STEP_FAILURE', 'Part failed at step')], db_index=True, max_length=50)),
                ('scope_object_id', models.CharField(blank=True, max_length=64, null=True)),
                ('recipient_resolver_key', models.CharField(blank=True, help_text='Name of a registered role resolver (e.g. "step_execution_assignee"). Resolver takes the event payload and returns an iterable of Users.', max_length=64)),
                ('channel_type', models.CharField(choices=[('EMAIL', 'Email'), ('IN_APP', 'In-App Notification')], default='EMAIL', max_length=20)),
                ('min_gap_seconds', models.PositiveIntegerField(default=3600, help_text='Per-(rule, recipient) cooldown. A recipient will not receive another notification from this rule until this many seconds have passed. 0 disables dedup.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='measurementdefinition',
            options={'base_manager_name': 'unscoped', 'default_manager_name': 'unscoped'},
        ),
        migrations.AlterModelOptions(
            name='measurementresult',
            options={'base_manager_name': 'unscoped', 'default_manager_name': 'unscoped'},
        ),
        migrations.AlterModelOptions(
            name='qaapproval',
            options={'base_manager_name': 'unscoped', 'default_manager_name': 'unscoped'},
        ),
        migrations.AlterModelOptions(
            name='qualityerrorslist',
            options={'base_manager_name': 'unscoped', 'default_manager_name': 'unscoped'},
        ),
        migrations.AlterModelOptions(
            name='samplingrule',
            options={'base_manager_name': 'unscoped', 'default_manager_name': 'unscoped'},
        ),
        migrations.AlterModelOptions(
            name='samplingruleset',
            options={'base_manager_name': 'unscoped', 'default_manager_name': 'unscoped'},
        ),
        migrations.AlterModelManagers(
            name='approvalrequest',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='approvalresponse',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='approvaltemplate',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='archivereason',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='assemblyusage',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='batchrollback',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='bom',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='bomline',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='calibrationrecord',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='capa',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='capastatustransition',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='capataskassignee',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='capatasks',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='capaverification',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='companies',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='core',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='disassemblybomline',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='documents',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='documenttype',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='downtimeevent',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='equipments',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='equipmenttype',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='equipmentusage',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='externalapiorderidentifier',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='fishbone',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='fivewhys',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='fpirecord',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='generatedreport',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='harvestedcomponent',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='heatmapannotations',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='lifelimitdefinition',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='lifetracking',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='materiallot',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='materialusage',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='measurementdefinition',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='measurementresult',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='milestone',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='milestonetemplate',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='notificationtask',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='orders',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='parts',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='parttypelifelimit',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='parttypes',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='processes',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='qaapproval',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='qualityerrorslist',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='qualityreports',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='quarantinedisposition',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='rcarecord',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='recordedit',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='rootcause',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='samplinganalytics',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='samplingauditlog',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='samplingrule',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='samplingruleset',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='samplingtriggerstate',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='scheduleslot',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='shift',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='spcbaseline',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='stepexecution',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='stepexecutionmeasurement',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='stepoverride',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='steprequirement',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='steprollback',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='steps',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='steptransitionlog',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='threedmodel',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='timeentry',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='trainingrecord',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='trainingrequirement',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='trainingtype',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='workcenter',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='workorder',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='bom',
            name='bom_tenant_parttype_rev_type_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='milestonetemplate',
            name='milestone_template_tenant_name_uniq',
        ),
        migrations.RenameIndex(
            model_name='notificationtask',
            new_name='Tracker_not_tenant__9adc02_idx',
            old_name='tracker_not_tenant__a13df9_idx',
        ),
        migrations.AlterField(
            model_name='notificationtask',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notificationtask',
            name='notification_type',
            field=models.CharField(choices=[('WEEKLY_REPORT', 'Weekly Order Report'), ('CAPA_REMINDER', 'CAPA Reminder'), ('APPROVAL_REQUEST', 'Approval Request'), ('APPROVAL_DECISION', 'Approval Decision'), ('APPROVAL_ESCALATION', 'Approval Escalation'), ('STEP_FAILURE', 'Part failed at step')], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='bom',
            constraint=models.UniqueConstraint(fields=('tenant', 'part_type', 'revision', 'bom_type'), name='bom_tenant_parttype_rev_type_uniq'),
        ),
        migrations.AddConstraint(
            model_name='milestonetemplate',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='milestone_template_tenant_name_uniq'),
        ),
        migrations.AddField(
            model_name='notificationrule',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.notificationrule'),
        ),
        migrations.AddField(
            model_name='notificationrule',
            name='recipient_groups',
            field=models.ManyToManyField(blank=True, related_name='notification_rules', to='Tracker.tenantgroup'),
        ),
        migrations.AddField(
            model_name='notificationrule',
            name='recipient_users',
            field=models.ManyToManyField(blank=True, related_name='notification_rules_as_recipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationrule',
            name='scope_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_rules', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notificationrule',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant'),
        ),
        migrations.AddField(
            model_name='notificationtask',
            name='source_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_tasks', to='Tracker.notificationrule'),
        ),
        migrations.AddIndex(
            model_name='notificationrule',
            index=models.Index(fields=['tenant', 'event_type', 'is_active'], name='Tracker_not_tenant__800f43_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationrule',
            index=models.Index(fields=['scope_content_type', 'scope_object_id'], name='Tracker_not_scope_c_47f588_idx'),
        ),
    ]
