# Generated by Django 5.1.6 on 2026-04-21 16:33

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0028_notification_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderHold',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('is_voided', models.BooleanField(default=False, help_text='Whether this record has been voided')),
                ('voided_at', models.DateTimeField(blank=True, help_text='When this record was voided', null=True)),
                ('void_reason', models.TextField(blank=True, help_text='Reason for voiding this record')),
                ('reason', models.CharField(choices=[('MATERIAL', 'Material'), ('QUALITY', 'Quality'), ('TOOLING', 'Tooling'), ('OPERATOR', 'Operator'), ('CUSTOMER', 'Customer'), ('OTHER', 'Other')], max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('placed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_clear_at', models.DateTimeField(blank=True, null=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('cleared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('placed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.workorderhold')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant')),
                ('voided_by', models.ForeignKey(blank=True, help_text='User who voided this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='Tracker.workorder')),
            ],
            options={
                'indexes': [models.Index(fields=['work_order', 'cleared_at'], name='Tracker_wor_work_or_5362c0_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('cleared_at__isnull', True), ('is_voided', False)), fields=('work_order',), name='workorderhold_one_open_per_wo')],
            },
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
    ]
