# Generated by Django 5.1.6 on 2026-04-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0029_workorderhold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationrule',
            name='event_type',
            field=models.CharField(choices=[('STEP_FAILURE', 'Part failed at step'), ('WORK_ORDER_HELD_TOO_LONG', 'Work order held too long'), ('WORK_ORDER_STALLED', 'Work order stalled'), ('WORK_ORDER_OVERDUE', 'Work order overdue')], db_index=True, max_length=50),
        ),
    ]
