# Generated by Django 5.1.6 on 2026-04-21 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0030_alter_notificationrule_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='parent_workorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_workorders', to='Tracker.workorder'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='split_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='split_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workorder',
            name='split_reason',
            field=models.CharField(blank=True, choices=[('QUANTITY', 'Quantity'), ('OPERATION', 'Operation'), ('REWORK', 'Rework')], max_length=16, null=True),
        ),
    ]
