# Generated by Django 5.1.6 on 2026-04-28 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0031_workorder_parent_workorder_workorder_split_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TenantGroupMembership',
        ),
    ]
