# Generated by Django 5.1.6 on 2026-04-29 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0032_drop_tenant_group_membership'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='core',
            options={'ordering': ['-received_date'], 'permissions': [('start_disassembly', 'Can start core disassembly'), ('complete_disassembly', 'Can complete core disassembly'), ('scrap_core', 'Can scrap a core')], 'verbose_name': 'Core', 'verbose_name_plural': 'Cores'},
        ),
        migrations.AlterModelOptions(
            name='harvestedcomponent',
            options={'ordering': ['-disassembled_at'], 'permissions': [('grade_component', 'Can grade a harvested component'), ('accept_component', 'Can accept a harvested component to inventory'), ('reject_component', 'Can reject a harvested component')], 'verbose_name': 'Harvested Component', 'verbose_name_plural': 'Harvested Components'},
        ),
    ]
