# Generated by Django 5.1.6 on 2026-04-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0033_add_reman_custom_permissions'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bom',
            name='bom_tenant_parttype_rev_type_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='milestonetemplate',
            name='milestone_template_tenant_name_uniq',
        ),
        migrations.AddConstraint(
            model_name='bom',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current_version', True)), fields=('tenant', 'part_type', 'revision', 'bom_type'), name='bom_tenant_parttype_rev_type_uniq'),
        ),
        migrations.AddConstraint(
            model_name='milestonetemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current_version', True)), fields=('tenant', 'name'), name='milestone_template_tenant_name_uniq'),
        ),
    ]
