# Generated by Django 5.1.6 on 2026-04-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0034_restore_partial_unique_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpirecord',
            name='notes',
            field=models.TextField(blank=True, help_text='Inspector notes captured at pass / fail time (audit trail)'),
        ),
    ]
