# Generated by Django 5.1.6 on 2026-05-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0036_processchangerequest_processchangeorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequest',
            name='approval_type',
            field=models.CharField(choices=[('DOCUMENT_RELEASE', 'Document Release'), ('CAPA_CRITICAL', 'CAPA Critical'), ('CAPA_MAJOR', 'CAPA Major'), ('ECO', 'Engineering Change Order'), ('TRAINING_CERT', 'Training Certification'), ('PROCESS_APPROVAL', 'Process Approval'), ('PCR_APPROVAL', 'Process Change Request Approval'), ('PCO_APPROVAL', 'Process Change Order Approval'), ('PCN_RELEASE', 'Process Change Notice Release')], max_length=50),
        ),
        migrations.AlterField(
            model_name='approvaltemplate',
            name='approval_type',
            field=models.CharField(choices=[('DOCUMENT_RELEASE', 'Document Release'), ('CAPA_CRITICAL', 'CAPA Critical'), ('CAPA_MAJOR', 'CAPA Major'), ('ECO', 'Engineering Change Order'), ('TRAINING_CERT', 'Training Certification'), ('PROCESS_APPROVAL', 'Process Approval'), ('PCR_APPROVAL', 'Process Change Request Approval'), ('PCO_APPROVAL', 'Process Change Order Approval'), ('PCN_RELEASE', 'Process Change Notice Release')], max_length=50),
        ),
    ]
