# Generated by Django 5.1.6 on 2026-05-13 17:32

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0037_alter_approvalrequest_approval_type_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='processchangenotice',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='processchangeorder',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='processchangerequest',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
    ]
