# Generated by Django 5.1.6 on 2026-05-13 19:59

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0038_alter_processchangenotice_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('event_code', models.CharField(db_index=True, max_length=64)),
                ('channel', models.CharField(max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('rendered_subject', models.CharField(blank=True, max_length=512)),
                ('rendered_body_text', models.TextField(blank=True)),
                ('rendered_body_html', models.TextField(blank=True)),
                ('rendered_action_url', models.CharField(blank=True, max_length=1024)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('retrying', 'Retrying'), ('suppressed', 'Suppressed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('is_test', models.BooleanField(default=False)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.notificationoutbox')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbox_rows', to='Tracker.notificationrule')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_outbox_rows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(condition=models.Q(('status__in', ['pending', 'retrying'])), fields=['tenant', 'status'], name='notif_outbox_tenant_status'), models.Index(fields=['tenant', 'event_code', 'created_at'], name='Tracker_not_tenant__907d17_idx'), models.Index(fields=['user', 'read_at', 'created_at'], name='Tracker_not_user_id_9c226b_idx'), models.Index(fields=['correlation_id'], name='Tracker_not_correla_a1d6e5_idx')],
                'constraints': [models.UniqueConstraint(fields=('event_code', 'idempotency_key'), name='notification_outbox_event_idempotency_unique')],
            },
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
    ]
