# Generated by Django 5.1.6 on 2026-05-19 15:30

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0040_notification_settings'),
    ]

    operations = [
        # The legacy NotificationRule schema is fundamentally different from
        # the Phase 3 one (event_type enum → event_code registry, GFK scope →
        # scope_kind discriminator, recipient_resolver_key removed). Any
        # existing rows can't be meaningfully translated. Codebase audit
        # confirmed only test/demo rows exist in any environment, so clear
        # the table before adding the new schema. Reverse migration restores
        # nothing — these rows are unrecoverable.
        migrations.RunSQL(
            sql='DELETE FROM "Tracker_notificationrule";',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='ExternalContact',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(blank=True, help_text="Free-form label, e.g. 'primary', 'quality', 'procurement'.", max_length=64)),
                ('enabled', models.BooleanField(default=True)),
                ('unsubscribe_token', models.CharField(blank=True, max_length=128)),
            ],
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='notificationrule',
            options={'permissions': [('edit_notification_rules', 'Can author tenant and customer notification rules')]},
        ),
        migrations.AlterModelManagers(
            name='notificationrule',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveIndex(
            model_name='notificationrule',
            name='Tracker_not_tenant__800f43_idx',
        ),
        migrations.RemoveIndex(
            model_name='notificationrule',
            name='Tracker_not_scope_c_47f588_idx',
        ),
        migrations.RemoveField(
            model_name='notificationrule',
            name='channel_type',
        ),
        migrations.RemoveField(
            model_name='notificationrule',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='notificationrule',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='notificationrule',
            name='recipient_resolver_key',
        ),
        migrations.RemoveField(
            model_name='notificationrule',
            name='scope_content_type',
        ),
        migrations.RemoveField(
            model_name='notificationrule',
            name='scope_object_id',
        ),
        migrations.AddField(
            model_name='notificationrule',
            name='channels',
            field=models.JSONField(blank=True, default=list, help_text="List of channel codes, e.g. ['email', 'in_app']."),
        ),
        migrations.AddField(
            model_name='notificationrule',
            name='conditions',
            field=models.JSONField(blank=True, default=dict, help_text='Parsed CEL AST cache; populated at save time.'),
        ),
        migrations.AddField(
            model_name='notificationrule',
            name='conditions_source',
            field=models.TextField(blank=True, help_text="CEL expression evaluated against the event's payload."),
        ),
        migrations.AddField(
            model_name='notificationrule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notification_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationrule',
            name='enabled',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='notificationrule',
            name='event_code',
            field=models.CharField(db_index=True, default='', help_text='Must exist in EVENT_REGISTRY (validated at save time).', max_length=64),
        ),
        migrations.AddField(
            model_name='notificationrule',
            name='owner_user',
            field=models.ForeignKey(blank=True, help_text="Required when scope_kind='personal'; null otherwise.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_notification_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationrule',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notificationrule',
            name='scope_customer',
            field=models.ForeignKey(blank=True, help_text="Required when scope_kind='customer'; null otherwise.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_rules', to='Tracker.companies'),
        ),
        migrations.AddField(
            model_name='notificationrule',
            name='scope_kind',
            field=models.CharField(choices=[('tenant', 'Tenant-wide'), ('customer', 'Customer-scoped'), ('personal', 'Personal')], db_index=True, default='tenant', max_length=16),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='min_gap_seconds',
            field=models.PositiveIntegerField(default=3600, help_text='Per-(rule, recipient) cooldown. Recipients will not receive another notification from this rule until this many seconds have passed. 0 disables dedup.'),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='externalcontact',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_contacts', to='Tracker.companies'),
        ),
        migrations.AddField(
            model_name='externalcontact',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.externalcontact'),
        ),
        migrations.AddField(
            model_name='externalcontact',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant'),
        ),
        migrations.AddField(
            model_name='notificationrule',
            name='recipient_external',
            field=models.ManyToManyField(blank=True, help_text="Only valid when scope_kind='customer'.", related_name='notification_rules', to='Tracker.externalcontact'),
        ),
        migrations.AddIndex(
            model_name='notificationrule',
            index=models.Index(fields=['tenant', 'event_code', 'enabled'], name='Tracker_not_tenant__308311_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationrule',
            index=models.Index(fields=['tenant', 'scope_kind', 'scope_customer'], name='Tracker_not_tenant__139f64_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationrule',
            index=models.Index(condition=models.Q(('scope_kind', 'personal')), fields=['owner_user', 'event_code'], name='nr_personal_owner_event'),
        ),
        migrations.AddConstraint(
            model_name='notificationrule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scope_kind', 'tenant'), ('scope_customer__isnull', True), ('owner_user__isnull', True)), models.Q(('scope_kind', 'customer'), ('scope_customer__isnull', False), ('owner_user__isnull', True)), models.Q(('scope_kind', 'personal'), ('scope_customer__isnull', True), ('owner_user__isnull', False)), _connector='OR'), name='notification_rule_scope_invariant'),
        ),
        migrations.AddIndex(
            model_name='externalcontact',
            index=models.Index(fields=['tenant', 'customer', 'enabled'], name='Tracker_ext_tenant__cc864b_idx'),
        ),
        migrations.AddConstraint(
            model_name='externalcontact',
            constraint=models.UniqueConstraint(fields=('customer', 'email'), name='external_contact_unique_per_customer'),
        ),
    ]
