# Generated by Django 5.1.6 on 2026-05-19 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0041_externalcontact_alter_notificationrule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationoutbox',
            name='external_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_outbox_rows', to='Tracker.externalcontact'),
        ),
        migrations.AddIndex(
            model_name='notificationoutbox',
            index=models.Index(fields=['rule', 'user', 'created_at'], name='Tracker_not_rule_id_1de523_idx'),
        ),
    ]
