# Generated by Django 5.1.6 on 2026-05-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0042_notificationoutbox_external_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationoutbox',
            name='idempotency_key',
            field=models.CharField(max_length=255),
        ),
    ]
