# Generated by Django 5.1.6 on 2026-05-19 20:44

import datetime
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0043_alter_notificationoutbox_idempotency_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('scope_kind', models.CharField(choices=[('tenant', 'Tenant-wide'), ('customer', 'Customer-scoped')], db_index=True, default='tenant', max_length=16)),
                ('provider_kind', models.CharField(help_text='ScheduledContentProvider registry key.', max_length=64)),
                ('provider_params', models.JSONField(blank=True, default=dict, help_text="Params passed to the provider. For customer-scoped schedules, the dispatcher merges in {'customer_id': scope_customer.id} before invoking the provider.")),
                ('cadence', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=16)),
                ('day_of_week', models.IntegerField(blank=True, help_text="0=Monday ... 6=Sunday. Required when cadence='weekly'.", null=True)),
                ('day_of_month', models.IntegerField(blank=True, help_text="1-28 (capped to avoid Feb/short-month gotchas). Required when cadence='monthly'.", null=True)),
                ('time_of_day', models.TimeField(default=datetime.time(8, 0), help_text="Local clock time in the schedule's timezone.")),
                ('timezone', models.CharField(default='UTC', help_text="IANA timezone name (e.g. 'America/New_York'). Defaults to UTC; the fire task falls back to tenant.default_timezone if 'UTC' is set and the tenant configured a non-UTC default.", max_length=64)),
                ('channels', models.JSONField(blank=True, default=list, help_text="List of channel codes, e.g. ['email']. Email-only at launch.")),
                ('last_fired_at', models.DateTimeField(blank=True, db_index=True, help_text='Set to now() inside the fire transaction, before rendering.', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notification_schedules', to=settings.AUTH_USER_MODEL)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.notificationschedule')),
                ('recipient_external', models.ManyToManyField(blank=True, help_text="Only valid when scope_kind='customer'.", related_name='notification_schedules', to='Tracker.externalcontact')),
                ('recipient_groups', models.ManyToManyField(blank=True, related_name='notification_schedules', to='Tracker.tenantgroup')),
                ('recipient_users', models.ManyToManyField(blank=True, related_name='notification_schedules_as_recipient', to=settings.AUTH_USER_MODEL)),
                ('scope_customer', models.ForeignKey(blank=True, help_text="Required when scope_kind='customer'; null otherwise.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_schedules', to='Tracker.companies')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant')),
            ],
            options={
                'permissions': [('edit_notification_schedules', 'Can author tenant and customer scheduled notifications')],
                'indexes': [models.Index(fields=['tenant', 'enabled', 'cadence'], name='Tracker_not_tenant__8d5109_idx'), models.Index(fields=['tenant', 'scope_kind', 'scope_customer'], name='Tracker_not_tenant__7e61fd_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('scope_kind', 'tenant'), ('scope_customer__isnull', True)), models.Q(('scope_kind', 'customer'), ('scope_customer__isnull', False)), _connector='OR'), name='notification_schedule_scope_shape'), models.CheckConstraint(condition=models.Q(models.Q(('cadence', 'weekly'), ('day_of_week__isnull', False), ('day_of_month__isnull', True)), models.Q(('cadence', 'monthly'), ('day_of_week__isnull', True), ('day_of_month__isnull', False)), _connector='OR'), name='notification_schedule_cadence_shape')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
    ]
