# Generated by Django 5.1.6 on 2026-05-19 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0044_notificationschedule'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notificationschedule',
            name='notification_schedule_scope_shape',
        ),
        migrations.AddField(
            model_name='notificationschedule',
            name='owner_user',
            field=models.ForeignKey(blank=True, help_text="Required when scope_kind='personal'; null otherwise. Personal-scoped schedules are also delivered to this user (the owner is the implicit recipient).", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_notification_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationschedule',
            name='scope_kind',
            field=models.CharField(choices=[('tenant', 'Tenant-wide'), ('customer', 'Customer-scoped'), ('personal', 'Personal')], db_index=True, default='tenant', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='notificationschedule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scope_kind', 'tenant'), ('scope_customer__isnull', True), ('owner_user__isnull', True)), models.Q(('scope_kind', 'customer'), ('scope_customer__isnull', False), ('owner_user__isnull', True)), models.Q(('scope_kind', 'personal'), ('scope_customer__isnull', True), ('owner_user__isnull', False)), _connector='OR'), name='notification_schedule_scope_shape'),
        ),
    ]
