# Generated by Django 5.1.6 on 2026-05-20 14:49

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0046_migrate_weekly_reports'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalationPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.escalationpolicy')),
                ('rule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_policy', to='Tracker.notificationrule')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant')),
            ],
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='EscalationInstance',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('source_object_id', models.CharField(max_length=64)),
                ('current_step', models.PositiveSmallIntegerField(default=0, help_text='0-indexed; the step that fires on the next tick.')),
                ('next_fire_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('acknowledged', 'Acknowledged'), ('exhausted', 'Exhausted'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16)),
                ('audit', models.JSONField(blank=True, default=list)),
                ('correlation_id', models.CharField(blank=True, default='', max_length=128)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.escalationinstance')),
                ('source_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='Tracker.escalationpolicy')),
            ],
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='EscalationStep',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(help_text='Step position in the chain, 0-indexed. Max 2 (three steps).')),
                ('delay_seconds', models.PositiveIntegerField(help_text="Wait from the previous step's fire (or from rule fire for order=0).")),
                ('subject_override', models.CharField(blank=True, default='', max_length=255)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='Tracker.escalationpolicy')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.escalationstep')),
                ('recipient_groups', models.ManyToManyField(blank=True, related_name='escalation_steps', to='Tracker.tenantgroup')),
                ('recipient_users', models.ManyToManyField(blank=True, related_name='escalation_steps_as_recipient', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant')),
            ],
            options={
                'ordering': ['order'],
            },
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='escalationpolicy',
            index=models.Index(fields=['tenant', 'enabled'], name='Tracker_esc_tenant__3f97ce_idx'),
        ),
        migrations.AddIndex(
            model_name='escalationinstance',
            index=models.Index(fields=['status', 'next_fire_at'], name='Tracker_esc_status_d3879a_idx'),
        ),
        migrations.AddIndex(
            model_name='escalationinstance',
            index=models.Index(fields=['tenant', 'status'], name='Tracker_esc_tenant__e4c848_idx'),
        ),
        migrations.AddIndex(
            model_name='escalationinstance',
            index=models.Index(fields=['source_content_type', 'source_object_id'], name='esc_inst_source_idx'),
        ),
        migrations.AddConstraint(
            model_name='escalationinstance',
            constraint=models.UniqueConstraint(fields=('policy', 'source_content_type', 'source_object_id'), name='escalation_instance_unique_per_source'),
        ),
        migrations.AddIndex(
            model_name='escalationstep',
            index=models.Index(fields=['policy', 'order'], name='Tracker_esc_policy__cfb9ff_idx'),
        ),
        migrations.AddConstraint(
            model_name='escalationstep',
            constraint=models.UniqueConstraint(fields=('policy', 'order'), name='escalation_step_unique_order'),
        ),
        migrations.AddConstraint(
            model_name='escalationstep',
            constraint=models.CheckConstraint(condition=models.Q(('order__lt', 3)), name='escalation_step_order_lt_max'),
        ),
    ]
