# Generated by Django 5.1.6 on 2026-05-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0047_escalation'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalationinstance',
            name='payload_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
