# Generated by Django 5.1.6 on 2026-05-20 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0048_escalationinstance_payload_snapshot'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationoutbox',
            name='source_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notificationoutbox',
            name='source_object_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddIndex(
            model_name='notificationoutbox',
            index=models.Index(fields=['source_content_type', 'source_object_id'], name='notif_outbox_source_idx'),
        ),
    ]
