# Generated by Django 5.1.6 on 2026-05-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0049_notificationoutbox_source_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationrule',
            name='recipient_strategy',
            field=models.CharField(choices=[('static', 'Static — recipients from this rule only'), ('from_payload', 'From event — recipients from the event payload'), ('union', "Union — combine event-payload recipients with this rule's")], default='static', help_text="Where to pull recipients from at fire time. 'static' uses the rule's M2M lists only; 'from_payload' reads recipient IDs from the event's payload; 'union' combines both.", max_length=16),
        ),
    ]
