# Generated by Django 5.1.6 on 2026-06-01 14:47

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0050_notificationrule_recipient_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps',
            name='sequencing_mode',
            field=models.CharField(default='sequential', help_text="How this Op's substeps are ordered for the operator. 'sequential' = substep N requires N-1 complete; 'free_order' = any order. Choices defined in Tracker.models.dwi.SequencingMode.", max_length=20),
        ),
        migrations.CreateModel(
            name='Substep',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text="Position within the parent Op's substep sequence (0-indexed).")),
                ('title', models.CharField(help_text='Short human-readable title shown in substep listings.', max_length=200)),
                ('body_blocks', models.JSONField(blank=True, default=list, help_text="TipTap document JSON. Shape: {type: 'doc', content: [...]}. See ambac-tracker-ui/src/types/dwi.ts (DwiDocument) for the node vocabulary.")),
                ('is_optional', models.BooleanField(default=False, help_text='Operator may mark this substep N/A instead of completing it.')),
                ('requires_signature', models.BooleanField(default=False, help_text="Operator must sign at substep completion. Distinct from inline AttestationCheckpoint(kind='signature') nodes within the body, which are gates inside the substep flow.")),
                ('expected_duration', models.DurationField(blank=True, help_text='Estimated time the substep typically takes. Informational.', null=True)),
                ('source_library_substep_id', models.PositiveIntegerField(blank=True, help_text='Forward-compatible: id of the LibrarySubstep this was inserted from.', null=True)),
                ('source_library_version', models.PositiveIntegerField(blank=True, help_text='Forward-compatible: version of the LibrarySubstep at insert time.', null=True)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.substep')),
                ('sampling_rule', models.ForeignKey(blank=True, help_text='If set, the substep only applies to parts this rule selects. Null = substep always applies to every part visiting the step.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicable_substeps', to='Tracker.samplingrule')),
                ('step', models.ForeignKey(help_text='The parent Op this substep belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='substeps', to='Tracker.steps')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant')),
            ],
            options={
                'ordering': ['step', 'order'],
            },
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SubstepCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True, help_text='UTC timestamp when the completion was recorded.')),
                ('marked_not_applicable', models.BooleanField(default=False, help_text='Set when the operator marks an optional substep N/A instead of completing it.')),
                ('notes', models.TextField(blank=True, help_text='Operator notes captured at completion; required when marking N/A.')),
                ('signature_data', models.TextField(blank=True, help_text='Base64 PNG signature blob, matching the ApprovalResponse format.', null=True)),
                ('signature_meaning', models.CharField(blank=True, help_text='Short human-readable description of what the signature attests to.', max_length=200, null=True)),
                ('verified_at', models.DateTimeField(blank=True, help_text='When identity verification (password / SSO) succeeded.', null=True)),
                ('verification_method', models.CharField(choices=[('PASSWORD', 'Password'), ('SSO', 'SSO'), ('NONE', 'None')], default='NONE', help_text="How the signing operator's identity was verified.", max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP at signing time; captured for audit defense.', null=True)),
                ('completed_by', models.ForeignKey(help_text='Operator who completed the substep.', on_delete=django.db.models.deletion.PROTECT, related_name='substep_completions', to=settings.AUTH_USER_MODEL)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.substepcompletion')),
                ('step_execution', models.ForeignKey(help_text='The execution record the operator was working when they completed this substep.', on_delete=django.db.models.deletion.CASCADE, related_name='substep_completions', to='Tracker.stepexecution')),
                ('substep', models.ForeignKey(help_text='The substep that was completed (or marked N/A).', on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='Tracker.substep')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant')),
            ],
            options={
                'ordering': ['-completed_at'],
            },
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SubstepResource',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, help_text='Optional quantity (e.g. count of fasteners, mass of material).', max_digits=12, null=True)),
                ('notes', models.CharField(blank=True, help_text='Short note about how/why this resource is needed.', max_length=200)),
                ('required', models.BooleanField(default=True, help_text="If True, operator can't proceed without the resource being present.")),
                ('equipment_type', models.ForeignKey(blank=True, help_text="The equipment class needed (e.g. 'Digital micrometer 0-1 in').", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referenced_by_substeps', to='Tracker.equipmenttype')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.substepresource')),
                ('substep', models.ForeignKey(help_text='The substep this resource is referenced from.', on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='Tracker.substep')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant')),
            ],
            options={
                'ordering': ['substep', 'pk'],
            },
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SubstepTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('language', models.CharField(help_text="BCP 47 language tag (e.g. 'en', 'es-MX', 'pt-BR').", max_length=10)),
                ('title', models.CharField(help_text='Translated title.', max_length=200)),
                ('body_blocks', models.JSONField(blank=True, default=list, help_text='Translated TipTap document JSON; same shape as Substep.body_blocks.')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.substeptranslation')),
                ('substep', models.ForeignKey(help_text='The substep this translation applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='Tracker.substep')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant')),
            ],
            options={
                'ordering': ['substep', 'language'],
            },
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='substep',
            index=models.Index(fields=['step', 'order'], name='dwi_substep_step_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='substep',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('step', 'order'), name='dwi_substep_step_order_uniq'),
        ),
        migrations.AddIndex(
            model_name='substepcompletion',
            index=models.Index(fields=['step_execution', 'substep'], name='dwi_subcomp_exec_subs_idx'),
        ),
        migrations.AddIndex(
            model_name='substepcompletion',
            index=models.Index(fields=['completed_by', '-completed_at'], name='dwi_subcomp_user_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='substepcompletion',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('step_execution', 'substep'), name='dwi_substepcompletion_exec_substep_uniq'),
        ),
        migrations.AddConstraint(
            model_name='substepresource',
            constraint=models.CheckConstraint(condition=models.Q(('equipment_type__isnull', False)), name='dwi_substepresource_has_equipment_type'),
        ),
        migrations.AddIndex(
            model_name='substeptranslation',
            index=models.Index(fields=['substep', 'language'], name='dwi_subtrans_substep_lang_idx'),
        ),
        migrations.AddConstraint(
            model_name='substeptranslation',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('substep', 'language'), name='dwi_substeptranslation_substep_lang_uniq'),
        ),
    ]
