# Generated by Django 5.1.6 on 2026-06-01 15:29

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0051_dwi_phase_1_substep_core'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubstepGateCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('node_id', models.CharField(help_text="UUIDv7 of the AttestationCheckpoint node in Substep.body_blocks (minted client-side per decision #18). Stable across the substep's lifetime as long as the engineer doesn't cut-paste the node — see src/lib/dwi/node-id.ts.", max_length=64)),
                ('completed_at', models.DateTimeField(auto_now_add=True, help_text='UTC timestamp when the gate was confirmed/signed.')),
                ('signature_data', models.TextField(blank=True, help_text='Base64 PNG signature blob, matching the ApprovalResponse format.', null=True)),
                ('signature_meaning', models.CharField(blank=True, help_text='Short human-readable description of what the signature attests to.', max_length=200, null=True)),
                ('verified_at', models.DateTimeField(blank=True, help_text='When identity verification (password / SSO) succeeded.', null=True)),
                ('verification_method', models.CharField(choices=[('PASSWORD', 'Password'), ('SSO', 'SSO'), ('NONE', 'None')], default='NONE', help_text="How the signing operator's identity was verified.", max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP at signing time; captured for audit defense.', null=True)),
                ('completed_by', models.ForeignKey(help_text='Operator who confirmed/signed the gate.', on_delete=django.db.models.deletion.PROTECT, related_name='substep_gate_completions', to=settings.AUTH_USER_MODEL)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.substepgatecompletion')),
                ('step_execution', models.ForeignKey(help_text='The execution record where this gate was completed.', on_delete=django.db.models.deletion.CASCADE, related_name='substep_gate_completions', to='Tracker.stepexecution')),
                ('substep', models.ForeignKey(help_text='The substep the gate node lives in.', on_delete=django.db.models.deletion.CASCADE, related_name='gate_completions', to='Tracker.substep')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant')),
            ],
            options={
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['step_execution', 'substep', 'node_id'], name='dwi_subgate_esn_idx'), models.Index(fields=['completed_by', '-completed_at'], name='dwi_subgate_user_time_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('step_execution', 'substep', 'node_id'), name='dwi_substepgate_exec_sub_node_uniq')],
            },
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SubstepResponse',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('node_id', models.CharField(help_text='UUIDv7 of the capture node in Substep.body_blocks (minted client-side per decision #18).', max_length=64)),
                ('kind', models.CharField(choices=[('text', 'Text input'), ('choice', 'Choice (radio / select)'), ('photo', 'Photo capture'), ('video', 'Video capture'), ('scan', 'Barcode / QR scan'), ('file', 'File upload'), ('timer', 'Timer (countdown / stopwatch)'), ('computed', 'Computed value (formula)')], help_text='Which kind of capture node produced this response.', max_length=20)),
                ('value_text', models.TextField(blank=True, help_text='Short text capture: text input, choice selection, scan code.')),
                ('value_json', models.JSONField(blank=True, help_text="Structured payload for kinds that don't fit a single string: Timer (started_at/completed_at/elapsed_seconds/direction), ComputedValue (inputs/result/in_spec).", null=True)),
                ('responded_at', models.DateTimeField(auto_now_add=True, help_text='UTC timestamp when the response was captured.')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.substepresponse')),
                ('responded_by', models.ForeignKey(help_text='Operator who captured the response.', on_delete=django.db.models.deletion.PROTECT, related_name='substep_responses', to=settings.AUTH_USER_MODEL)),
                ('step_execution', models.ForeignKey(help_text='The execution record where this response was captured.', on_delete=django.db.models.deletion.CASCADE, related_name='substep_responses', to='Tracker.stepexecution')),
                ('substep', models.ForeignKey(help_text='The substep the capture node lives in.', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='Tracker.substep')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant')),
                ('value_document', models.ForeignKey(blank=True, help_text='Photo / video / file capture: FK to the uploaded Documents row.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substep_responses', to='Tracker.documents')),
            ],
            options={
                'ordering': ['-responded_at'],
                'indexes': [models.Index(fields=['step_execution', 'substep', 'node_id'], name='dwi_subresp_esn_idx'), models.Index(fields=['kind', '-responded_at'], name='dwi_subresp_kind_time_idx'), models.Index(fields=['responded_by', '-responded_at'], name='dwi_subresp_user_time_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('step_execution', 'substep', 'node_id'), name='dwi_substepresponse_exec_sub_node_uniq')],
            },
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
    ]
