# Generated by Django 5.1.6 on 2026-06-01 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0052_dwi_phase_2_per_node_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepexecutionmeasurement',
            name='substep',
            field=models.ForeignKey(blank=True, help_text='Substep this measurement was captured from, when the source was a DWI MeasurementInput node. Null means the measurement was recorded at the Op level (legacy path or non-DWI workflow).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='step_execution_measurements', to='Tracker.substep'),
        ),
        migrations.AddField(
            model_name='stepmeasurementrequirement',
            name='substep',
            field=models.ForeignKey(blank=True, help_text='If set, the requirement applies at substep granularity rather than Op-level.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurement_requirements', to='Tracker.substep'),
        ),
        migrations.AddField(
            model_name='steprequirement',
            name='substep',
            field=models.ForeignKey(blank=True, help_text='If set, the requirement applies at substep granularity rather than Op-level.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step_requirements', to='Tracker.substep'),
        ),
        migrations.AddField(
            model_name='substep',
            name='is_inspection_point',
            field=models.BooleanField(default=False, help_text='When True, MeasurementInput captures within this substep additionally create inspection records (QualityReports + MeasurementResult) via services/qms/inline_capture.py, firing the existing record_quality_report_side_effects pipeline (auto-quarantine on out-of-spec, ncr.opened notification, sampling fallback). Default False = process data only. Set True for FAI substeps, in-process hold-points, final inspection. See architectural decision #21 in the DWI design doc.'),
        ),
        migrations.AddIndex(
            model_name='stepexecutionmeasurement',
            index=models.Index(fields=['substep', 'recorded_at'], name='dwi_sem_substep_time_idx'),
        ),
    ]
