# Generated by Django 5.1.6 on 2026-06-02 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0053_dwi_phase_3_substep_aware_measurements'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepexecution',
            name='core',
            field=models.ForeignKey(blank=True, help_text='The core being tracked through this teardown step (mutually exclusive with `part`).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step_executions', to='Tracker.core'),
        ),
        migrations.AddField(
            model_name='steptransitionlog',
            name='core',
            field=models.ForeignKey(blank=True, help_text='The core that transitioned to the step (mutually exclusive with `part`).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='step_transition_logs', to='Tracker.core'),
        ),
        migrations.AlterField(
            model_name='stepexecution',
            name='part',
            field=models.ForeignKey(blank=True, help_text='The part being tracked through this step (mutually exclusive with `core`).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step_executions', to='Tracker.parts'),
        ),
        migrations.AlterField(
            model_name='steptransitionlog',
            name='part',
            field=models.ForeignKey(blank=True, help_text='The part that transitioned to the step (mutually exclusive with `core`).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tracker.parts'),
        ),
        migrations.AddIndex(
            model_name='stepexecution',
            index=models.Index(fields=['core', 'step'], name='Tracker_ste_core_id_a340d0_idx'),
        ),
        migrations.AddConstraint(
            model_name='stepexecution',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('core__isnull', True), ('part__isnull', False)), models.Q(('core__isnull', False), ('part__isnull', True)), _connector='OR'), name='step_execution_one_subject'),
        ),
        migrations.AddConstraint(
            model_name='steptransitionlog',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('core__isnull', True), ('part__isnull', False)), models.Q(('core__isnull', False), ('part__isnull', True)), _connector='OR'), name='step_transition_log_one_subject'),
        ),
    ]
