# Generated by Django 5.1.6 on 2026-06-02 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_roles(apps, schema_editor):
    """Copy legacy single-FK / flat-M2M relationships into the new role-tagged
    through tables so the deprecation window can land cleanly.

    Idempotent — safe to re-run because each through row is keyed by
    (quality_report, equipment_or_user, role) which already has a unique
    constraint. We use `get_or_create` to make that explicit.
    """
    QualityReports = apps.get_model('Tracker', 'QualityReports')
    QualityReportEquipment = apps.get_model('Tracker', 'QualityReportEquipment')
    QualityReportPersonnel = apps.get_model('Tracker', 'QualityReportPersonnel')

    # Use `_default_manager` because QualityReports is a SecureModel — its
    # default-named `objects` manager is tenant-scoped and not available
    # in migration apps state. `_default_manager` resolves to whatever is
    # registered without tripping the tenant-context check.
    for qr in QualityReports._default_manager.iterator():
        if qr.machine_id:
            QualityReportEquipment.objects.get_or_create(
                quality_report=qr, equipment_id=qr.machine_id, role='PRODUCTION',
            )
        if qr.detected_by_id:
            QualityReportPersonnel.objects.get_or_create(
                quality_report=qr, user_id=qr.detected_by_id, role='DETECTED_BY',
            )
        if qr.verified_by_id:
            QualityReportPersonnel.objects.get_or_create(
                quality_report=qr, user_id=qr.verified_by_id, role='VERIFIED_BY',
            )
        for op_id in qr.operators.values_list('id', flat=True):
            QualityReportPersonnel.objects.get_or_create(
                quality_report=qr, user_id=op_id, role='OPERATOR',
            )


def backfill_roles_reverse(apps, schema_editor):
    """Reverse just empties the new through tables. The legacy FK / M2M
    fields stay populated regardless (they're the durable source of truth
    until a follow-up PR removes them), so reversing the backfill is safe.
    """
    apps.get_model('Tracker', 'QualityReportEquipment').objects.all().delete()
    apps.get_model('Tracker', 'QualityReportPersonnel').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0054_reman_dwi_r1_step_execution_core'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualityreports',
            name='detected_by',
            field=models.ForeignKey(help_text='DEPRECATED — use `personnel` (role=DETECTED_BY). Kept for back-compat.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='defects_detected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qualityreports',
            name='operators',
            field=models.ManyToManyField(blank=True, help_text='DEPRECATED — use `personnel` (role=OPERATOR). Kept for back-compat.', related_name='defects_during_operation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qualityreports',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED — use `personnel` (role=VERIFIED_BY). Kept for back-compat.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defects_verified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='QualityReportEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PRODUCTION', 'Production machine'), ('FIXTURE', 'Fixture / hold-down'), ('TOOL', 'Cutting / forming tool'), ('GAUGE', 'Inspection gauge / instrument'), ('OTHER', 'Other')], default='PRODUCTION', help_text='What role this equipment played for this report.', max_length=20)),
                ('notes', models.CharField(blank=True, help_text='Optional context (e.g. which station in a multi-station cell).', max_length=200)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_report_links', to='Tracker.equipments')),
                ('quality_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_links', to='Tracker.qualityreports')),
            ],
        ),
        migrations.AddField(
            model_name='qualityreports',
            name='equipments',
            field=models.ManyToManyField(blank=True, help_text='Equipment implicated in this report, with per-row role (production machine, fixture, tool, gauge, other). Replaces the single `machine` FK so cell ops and multi-station steps are captured accurately for Pareto / root-cause analysis.', related_name='quality_reports', through='Tracker.QualityReportEquipment', to='Tracker.equipments'),
        ),
        migrations.CreateModel(
            name='QualityReportPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('DETECTED_BY', 'Detected by'), ('OPERATOR', 'Operator on the job'), ('VERIFIED_BY', 'Verified by (second sig)'), ('INSPECTOR', 'Inspector'), ('WITNESS', 'Witness'), ('TRAINER', 'Trainer / supervisor'), ('TRAINEE', 'Trainee under supervision')], help_text='What role this user played on this report.', max_length=20)),
                ('signed_at', models.DateTimeField(blank=True, help_text='When the user attested to their role (signature timestamp). Null for non-signing roles like OPERATOR.', null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('quality_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel_links', to='Tracker.qualityreports')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_report_personnel_links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='qualityreports',
            name='personnel',
            field=models.ManyToManyField(blank=True, help_text='Users involved in this report with per-row role (detected_by, operator, verified_by, inspector, witness, trainer, trainee). Replaces the legacy `detected_by` / `operators` / `verified_by` trio so any user role can be captured without schema churn.', related_name='quality_report_personnel', through='Tracker.QualityReportPersonnel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='qualityreportequipment',
            index=models.Index(fields=['equipment', 'role'], name='qreq_equipment_role_idx'),
        ),
        migrations.AddConstraint(
            model_name='qualityreportequipment',
            constraint=models.UniqueConstraint(fields=('quality_report', 'equipment', 'role'), name='qreq_report_equipment_role_uniq'),
        ),
        migrations.AddIndex(
            model_name='qualityreportpersonnel',
            index=models.Index(fields=['user', 'role'], name='qrp_user_role_idx'),
        ),
        migrations.AddConstraint(
            model_name='qualityreportpersonnel',
            constraint=models.UniqueConstraint(fields=('quality_report', 'user', 'role'), name='qrp_report_user_role_uniq'),
        ),
        migrations.RunPython(backfill_roles, backfill_roles_reverse),
    ]
