# Generated by Django 5.1.6 on 2026-06-02 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0055_add_qualityreport_equipment_personnel_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='core',
            name='step',
            field=models.ForeignKey(blank=True, help_text='Current Step in the teardown Process (null for cores not yet routed).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_cores', to='Tracker.steps'),
        ),
    ]
