# Generated by Django 5.1.6 on 2026-06-02 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0056_reman_dwi_r2_core_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='disassemblybomline',
            name='positions',
            field=models.JSONField(blank=True, default=list, help_text="Optional ordered list of position labels (e.g., ['Cyl 1', 'Cyl 2', 'Cyl 3', 'Cyl 4']) of length expected_qty. Pre-fills the capture node's position field per row. Free-text when empty."),
        ),
        migrations.AddField(
            model_name='parttypes',
            name='default_disassembly_process',
            field=models.ForeignKey(blank=True, help_text="Canonical preference for the teardown picker. When set, the operator's bulk-teardown dialog preselects this Process. Optional: when null, the picker has no preselection and (for automation paths) WO creation refuses to resolve a default.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_disassembly', to='Tracker.processes'),
        ),
        migrations.AddField(
            model_name='processes',
            name='is_disassembly',
            field=models.BooleanField(default=False, help_text='When True, this Process is eligible to be selected as a teardown process for Cores of its `part_type`. A single core_type may have multiple eligible disassembly Processes (quick teardown, full overhaul, failure-analysis); the operator picks at WO creation.'),
        ),
    ]
