# Generated by Django 5.1.6 on 2026-06-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0057_reman_dwi_r3_eligibility_and_positions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substepresponse',
            name='kind',
            field=models.CharField(choices=[('text', 'Text input'), ('choice', 'Choice (radio / select)'), ('photo', 'Photo capture'), ('video', 'Video capture'), ('scan', 'Barcode / QR scan'), ('file', 'File upload'), ('timer', 'Timer (countdown / stopwatch)'), ('computed', 'Computed value (formula)'), ('attestation', 'Attestation (confirm / signature)'), ('status', 'Quality status (PASS / FAIL / PENDING)'), ('equipment_roles', 'Equipment + roles'), ('personnel_roles', 'Personnel + roles'), ('signatures', 'Inspection signatures (detected / verified)'), ('defects', 'Defect findings'), ('annotation', 'Part annotation (3D)')], help_text='Which kind of capture node produced this response.', max_length=20),
        ),
    ]
