# Generated by Django 5.1.6 on 2026-06-02 17:16

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0058_extend_substep_response_kinds'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchExecution',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When the operator started the batch.')),
                ('sealed_at', models.DateTimeField(blank=True, help_text='When the batch was sealed (first BATCH-scope substep fired). Parts can be added freely before this; locked after.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When every BATCH-scope substep on the Step was completed.', null=True)),
                ('notes', models.TextField(blank=True, help_text='Operator notes captured at batch start / during the run.')),
            ],
            options={
                'ordering': ['-started_at'],
            },
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='substepcompletion',
            name='dwi_substepcompletion_exec_substep_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='substepresponse',
            name='dwi_substepresponse_exec_sub_node_uniq',
        ),
        migrations.AddField(
            model_name='substep',
            name='scope',
            field=models.CharField(choices=[('sampled', 'Per part (sampling)'), ('batch', 'Per batch')], default='sampled', help_text='Whether the substep runs per part (SAMPLED, default — uses sampling_rule for cadence, null rule = 100%) or once for the whole batch (BATCH — oven cycles, wash tanks, plating baths). BATCH substeps write captures against a `BatchExecution` shared by every part in the batch, instead of per-part `StepExecution`.', max_length=10),
        ),
        migrations.AlterField(
            model_name='substep',
            name='sampling_rule',
            field=models.ForeignKey(blank=True, help_text='Only meaningful when scope=SAMPLED. If set, the substep only applies to parts this rule selects. Null = substep always applies to every part visiting the step (100% sample). Ignored when scope=BATCH.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicable_substeps', to='Tracker.samplingrule'),
        ),
        migrations.AlterField(
            model_name='substepcompletion',
            name='step_execution',
            field=models.ForeignKey(blank=True, help_text='Set when the substep is per-part (scope=SAMPLED). Exactly one of step_execution / batch_execution should be set; check constraint enforces this at the DB level.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='substep_completions', to='Tracker.stepexecution'),
        ),
        migrations.AlterField(
            model_name='substepresponse',
            name='kind',
            field=models.CharField(choices=[('text', 'Text input'), ('choice', 'Choice (radio / select)'), ('photo', 'Photo capture'), ('video', 'Video capture'), ('scan', 'Barcode / QR scan'), ('file', 'File upload'), ('timer', 'Timer (countdown / stopwatch)'), ('computed', 'Computed value (formula)'), ('attestation', 'Attestation (confirm / signature)'), ('status', 'Quality status (PASS / FAIL / PENDING)'), ('equipment_roles', 'Equipment + roles'), ('personnel_roles', 'Personnel + roles'), ('signatures', 'Inspection signatures (detected / verified)'), ('defects', 'Defect findings'), ('annotation', 'Part annotation (3D)'), ('harvested_components', 'Harvested components (teardown)')], help_text='Which kind of capture node produced this response.', max_length=20),
        ),
        migrations.AlterField(
            model_name='substepresponse',
            name='step_execution',
            field=models.ForeignKey(blank=True, help_text='Set when the substep is per-part (scope=SAMPLED). Exactly one of step_execution / batch_execution should be set.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='substep_responses', to='Tracker.stepexecution'),
        ),
        migrations.AddField(
            model_name='batchexecution',
            name='parts',
            field=models.ManyToManyField(blank=True, help_text='Parts that are members of this batch.', related_name='batch_executions', to='Tracker.parts'),
        ),
        migrations.AddField(
            model_name='batchexecution',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.batchexecution'),
        ),
        migrations.AddField(
            model_name='batchexecution',
            name='started_by',
            field=models.ForeignKey(help_text='Operator who started the batch.', on_delete=django.db.models.deletion.PROTECT, related_name='batch_executions_started', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batchexecution',
            name='step',
            field=models.ForeignKey(help_text='The Step the batch is running through.', on_delete=django.db.models.deletion.CASCADE, related_name='batch_executions', to='Tracker.steps'),
        ),
        migrations.AddField(
            model_name='batchexecution',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant'),
        ),
        migrations.AddField(
            model_name='batchexecution',
            name='work_order',
            field=models.ForeignKey(help_text='The WorkOrder whose parts make up this batch.', on_delete=django.db.models.deletion.CASCADE, related_name='batch_executions', to='Tracker.workorder'),
        ),
        migrations.AddField(
            model_name='substepcompletion',
            name='batch_execution',
            field=models.ForeignKey(blank=True, help_text='Set when the substep is per-batch (scope=BATCH). Exactly one of step_execution / batch_execution should be set.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='substep_completions', to='Tracker.batchexecution'),
        ),
        migrations.AddField(
            model_name='substepresponse',
            name='batch_execution',
            field=models.ForeignKey(blank=True, help_text='Set when the substep is per-batch (scope=BATCH). Exactly one of step_execution / batch_execution should be set.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='substep_responses', to='Tracker.batchexecution'),
        ),
        migrations.AddIndex(
            model_name='substepcompletion',
            index=models.Index(fields=['batch_execution', 'substep'], name='dwi_subcomp_batch_subs_idx'),
        ),
        migrations.AddIndex(
            model_name='substepresponse',
            index=models.Index(fields=['batch_execution', 'substep', 'node_id'], name='dwi_subresp_bsn_idx'),
        ),
        migrations.AddConstraint(
            model_name='substepcompletion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('batch_execution__isnull', True), ('step_execution__isnull', False)), models.Q(('batch_execution__isnull', False), ('step_execution__isnull', True)), _connector='OR'), name='dwi_subcomp_exactly_one_exec_fk'),
        ),
        migrations.AddConstraint(
            model_name='substepcompletion',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('step_execution__isnull', False)), fields=('step_execution', 'substep'), name='dwi_substepcompletion_exec_substep_uniq'),
        ),
        migrations.AddConstraint(
            model_name='substepcompletion',
            constraint=models.UniqueConstraint(condition=models.Q(('batch_execution__isnull', False), ('deleted_at__isnull', True)), fields=('batch_execution', 'substep'), name='dwi_substepcompletion_batch_substep_uniq'),
        ),
        migrations.AddConstraint(
            model_name='substepresponse',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('batch_execution__isnull', True), ('step_execution__isnull', False)), models.Q(('batch_execution__isnull', False), ('step_execution__isnull', True)), _connector='OR'), name='dwi_subresp_exactly_one_exec_fk'),
        ),
        migrations.AddConstraint(
            model_name='substepresponse',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('step_execution__isnull', False)), fields=('step_execution', 'substep', 'node_id'), name='dwi_substepresponse_exec_sub_node_uniq'),
        ),
        migrations.AddConstraint(
            model_name='substepresponse',
            constraint=models.UniqueConstraint(condition=models.Q(('batch_execution__isnull', False), ('deleted_at__isnull', True)), fields=('batch_execution', 'substep', 'node_id'), name='dwi_substepresponse_batch_sub_node_uniq'),
        ),
        migrations.AddIndex(
            model_name='batchexecution',
            index=models.Index(fields=['work_order', 'step'], name='dwi_batchexec_wo_step_idx'),
        ),
        migrations.AddIndex(
            model_name='batchexecution',
            index=models.Index(fields=['-started_at'], name='dwi_batchexec_started_idx'),
        ),
    ]
