# Generated by Django 5.1.6 on 2026-06-03 18:19

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0059_dwi_batch_execution_and_substep_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='split_at',
            field=models.DateTimeField(blank=True, help_text='UTC timestamp when the split happened. Set together with split_from_cohort.', null=True),
        ),
        migrations.AddField(
            model_name='parts',
            name='split_from_cohort',
            field=models.BooleanField(default=False, help_text='True iff this part has been pulled off its WorkOrder cohort and now advances independently. Set via the split_part_from_lot service; one-way in v1 (no re-merging).'),
        ),
        migrations.AddField(
            model_name='parts',
            name='split_reason',
            field=models.CharField(blank=True, choices=[('quarantine', 'Quarantine'), ('rework', 'Rework'), ('expedite', 'Expedite'), ('customer_pull', 'Customer pull'), ('scrap', 'Scrap')], help_text='Reason this part was split off; blank when split_from_cohort=False.', max_length=20),
        ),
        migrations.AddField(
            model_name='substep',
            name='allow_not_applicable',
            field=models.BooleanField(default=False, help_text='Engineer authoring concern: when True, an operator may mark this substep N/A (must provide na_reason_code on the SubstepCompletion row). When False, N/A is rejected at write time. Ignored when is_critical=True.'),
        ),
        migrations.AddField(
            model_name='substep',
            name='is_critical',
            field=models.BooleanField(default=False, help_text='Safety-critical substep. When True, N/A is impossible regardless of `allow_not_applicable` or `is_optional`; the gate will reject any SubstepCompletion with marked_not_applicable=True for this substep, even at gate-time re-check.'),
        ),
        migrations.AddField(
            model_name='substepcompletion',
            name='is_voided',
            field=models.BooleanField(default=False, help_text='Whether this record has been voided'),
        ),
        migrations.AddField(
            model_name='substepcompletion',
            name='na_reason_code',
            field=models.CharField(blank=True, help_text="Reason code captured when `marked_not_applicable=True`. Required by the advancement gate; free-text 'skipped' is how QMS findings happen, so an enumerated reason is mandatory at the data layer.", max_length=64),
        ),
        migrations.AddField(
            model_name='substepcompletion',
            name='void_reason',
            field=models.TextField(blank=True, help_text='Reason for voiding this record'),
        ),
        migrations.AddField(
            model_name='substepcompletion',
            name='voided_at',
            field=models.DateTimeField(blank=True, help_text='When this record was voided', null=True),
        ),
        migrations.AddField(
            model_name='substepcompletion',
            name='voided_by',
            field=models.ForeignKey(blank=True, help_text='User who voided this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SamplingDecision',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('outcome', models.CharField(choices=[('selected', 'Selected'), ('deselected', 'Deselected'), ('pending', 'Pending')], help_text='What the rule decided — SELECTED, DESELECTED, or PENDING.', max_length=12)),
                ('ruleset_version', models.PositiveIntegerField(default=1, help_text="Version of the SamplingRuleSet that produced this decision. Audit can answer 'what rule was active when this was decided' via this field; rule edits bump the version on supersession.")),
                ('decided_at', models.DateTimeField(auto_now_add=True, help_text='UTC timestamp the decision was written.')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.samplingdecision')),
                ('step_execution', models.ForeignKey(help_text='The (part, step, visit) this decision applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='sampling_decisions', to='Tracker.stepexecution')),
                ('substep', models.ForeignKey(help_text='The substep whose sampling_rule produced this decision.', on_delete=django.db.models.deletion.CASCADE, related_name='sampling_decisions', to='Tracker.substep')),
                ('superseded_by', models.ForeignKey(blank=True, help_text="When a rule change invalidates this decision, the new SamplingDecision row's id goes here. Null = this decision is live.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='Tracker.samplingdecision')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant')),
            ],
            options={
                'ordering': ['step_execution', 'substep', '-decided_at'],
                'indexes': [models.Index(fields=['step_execution', 'substep'], name='dwi_samplingdec_exec_sub_idx'), models.Index(fields=['outcome', 'decided_at'], name='dwi_samplingdec_outcome_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('superseded_by__isnull', True)), fields=('step_execution', 'substep'), name='dwi_samplingdecision_live_uniq')],
            },
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
    ]
