# Generated by Django 5.1.6 on 2026-06-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0060_advancement_engine_phase_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='split_reason',
            field=models.CharField(blank=True, choices=[('quarantine', 'Quarantine'), ('rework', 'Rework'), ('scrap', 'Scrap')], help_text='Reason this part was split off; blank when split_from_cohort=False.', max_length=20),
        ),
    ]
