# Generated by Django 5.1.6 on 2026-06-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0061_drop_expedite_customer_pull_split_reasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='expected_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
