# Generated by Django 5.1.6 on 2026-06-08 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0062_workorder_expected_start_alter_workorder_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='processchangerequest',
            name='draft_process_version',
            field=models.ForeignKey(blank=True, help_text='DRAFT process version the engineer is authoring against. Forked at PCR creation; PCO inherits this at approval.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='Tracker.processes'),
        ),
        migrations.AddField(
            model_name='processchangerequest',
            name='proposed_change_diff',
            field=models.JSONField(blank=True, help_text='Structured diff between target_process and draft_process_version, populated at submit time.', null=True),
        ),
    ]
