# Generated by Django 5.1.6 on 2026-06-08 23:06

import uuid
from django.db import migrations, models


def backfill_identity_chains(apps, schema_editor):
    """Unify identity_id within each previous_version chain.

    The AddField default fires once per row, so chain members start with
    different identity_ids. Walk each chain back to its root and copy
    the root's identity_id forward to every descendant so they share.
    """
    Steps = apps.get_model('Tracker', 'Steps')

    # Map every Step id to its chain root's identity_id.
    root_identity_by_step_id = {}
    # Process root rows first — they define the chain identity.
    for step in Steps._base_manager.filter(previous_version__isnull=True).iterator():
        root_identity_by_step_id[step.id] = step.identity_id

    # Walk downstream rows, copy ancestor's identity_id forward. Repeat
    # passes until stable so chains of any depth resolve.
    pending = set(
        Steps._base_manager.filter(previous_version__isnull=False).values_list('id', 'previous_version_id')
    )
    progress = True
    while pending and progress:
        progress = False
        resolved_this_pass = set()
        for step_id, prev_id in pending:
            if prev_id in root_identity_by_step_id:
                root_identity_by_step_id[step_id] = root_identity_by_step_id[prev_id]
                resolved_this_pass.add((step_id, prev_id))
                progress = True
        pending -= resolved_this_pass

    # Bulk-update only rows whose identity_id needs to change.
    to_update = []
    for step in Steps._base_manager.exclude(previous_version__isnull=True).only('id', 'identity_id').iterator():
        target = root_identity_by_step_id.get(step.id)
        if target is not None and step.identity_id != target:
            step.identity_id = target
            to_update.append(step)
    if to_update:
        Steps._base_manager.bulk_update(to_update, ['identity_id'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0064_alter_approvalrequest_approval_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps',
            name='identity_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.RunPython(backfill_identity_chains, reverse_code=noop_reverse),
    ]
