# Generated by Django 5.1.6 on 2026-06-08 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0065_steps_identity_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='processchangerequest',
            name='processchangerequest_one_open_per_process',
        ),
    ]
