# Generated by Django 5.1.6 on 2026-06-09 12:11
#
# Schema-only step. The actual per-row identity backfill lives in
# 0069 — splitting the two means a mid-deploy crash during the
# (potentially long-running) data walk can't leave the column
# committed but the migration unrecorded, which would brick re-runs
# with "column already exists" on the AddField. Each migration here
# either fully applies and is recorded, or rolls back atomically.

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0067_fix_steps_identity_per_chain'),
    ]

    operations = [
        migrations.AddField(
            model_name='substep',
            name='identity_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
