# Generated by Django 5.1.6 on 2026-06-09 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0069_substep_identity_id_backfill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processes',
            name='is_batch_process',
        ),
    ]
