# Generated by Django 5.1.6 on 2026-06-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0070_drop_processes_is_batch_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='change_control_mode',
            field=models.CharField(choices=[('SIMPLIFIED', 'Simplified'), ('REGULATED', 'Regulated')], default='SIMPLIFIED', help_text='SIMPLIFIED: PCO auto-approves at PCR approval and PCN auto-releases at implementation (ISO 9001 8.5.6). REGULATED: PCO requires explicit author + approve with separation of duties, PCR approval requires collected signatures, PCN requires explicit release (IATF 16949 8.5.6.1 / AS9100D 8.5.6).', max_length=20),
        ),
    ]
