# Generated by Django 5.1.6 on 2026-06-10 19:50
#
# Repoints Steps.revisit_role from the global auth.Group to the
# tenant-scoped TenantGroup as part of retiring app-level global groups.
# auth.Group has an integer PK and TenantGroup a UUID PK, so the column
# type changes (integer -> uuid) and cannot be cast in place. The field
# is runtime-inert (operator-assignment-by-role was never implemented;
# `_get_operator_for_step` returns None for revisit_assignment='role'),
# so we drop the old column (discarding the few stale auth.Group ids) and
# add a fresh nullable FK to TenantGroup.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0071_tenant_change_control_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steps',
            name='revisit_role',
        ),
        migrations.AddField(
            model_name='steps',
            name='revisit_role',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='Tracker.tenantgroup',
                help_text="Required role when revisit_assignment='role'",
            ),
        ),
    ]
