# Generated by Django 5.1.6 on 2026-06-17 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0072_alter_steps_revisit_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parts',
            options={'permissions': [('resolve_step_decision', 'Can resolve a manual decision-point step (choose the routing branch)')], 'verbose_name': 'Part', 'verbose_name_plural': 'Parts'},
        ),
    ]
