# Generated by Django 5.1.6 on 2026-06-18 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0073_alter_parts_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpirecord',
            name='quality_report',
            field=models.ForeignKey(blank=True, help_text="The designated first piece's QualityReport this buy-off was made against", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fpi_records', to='Tracker.qualityreports'),
        ),
    ]
