# Generated by Django 5.1.6 on 2026-06-18 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0074_fpirecord_quality_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fpirecord',
            options={'ordering': ['-created_at'], 'permissions': [('sign_off_fpi', 'Can sign off (buy off) a First Piece Inspection')], 'verbose_name': 'FPI Record', 'verbose_name_plural': 'FPI Records'},
        ),
    ]
