# Generated by Django 5.1.6 on 2026-06-22 13:44

import django.db.models.deletion
import django.utils.timezone
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0075_alter_fpirecord_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('is_home', models.BooleanField(default=False, help_text="User's home/primary tenant (mirrors their User.tenant FK).")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('suspended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships_suspended', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='Tracker.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tenant Membership',
                'verbose_name_plural': 'Tenant Memberships',
                'db_table': 'tracker_tenant_membership',
                'indexes': [models.Index(fields=['user', 'tenant'], name='tracker_ten_user_id_5eead4_idx'), models.Index(fields=['tenant', 'status'], name='tracker_ten_tenant__7b726a_idx')],
                'unique_together': {('user', 'tenant')},
            },
        ),
    ]
