# Generated by Django 5.1.6 on 2026-06-23 12:32
"""
Backfill `measurement_type` on DWI `measurementInput` nodes from their linked
MeasurementDefinition.

The DWI MeasurementInput node denormalizes the measurement's type (NUMERIC /
PASS_FAIL) so the operator runtime can render the right widget (numeric field
vs. Pass/Fail dropdown) without fetching the definition. Nodes authored before
that field existed have `measurement_type` absent/None and therefore render as
numeric even when the linked spec is PASS_FAIL. This copies the type from the
linked definition (which is a fixed version, so the value never goes stale).

Idempotent: re-running sets the same value. Nodes with no
`measurement_definition_id` are left untouched (the author sets the type via
the node's Pass/Fail toggle).
"""
from django.db import migrations


def _walk(node, def_types, stats):
    """Recursively set measurement_type on measurementInput nodes. Returns True
    if anything in this subtree changed."""
    changed = False
    if isinstance(node, dict):
        if node.get("type") == "measurementInput":
            attrs = node.setdefault("attrs", {})
            md_id = attrs.get("measurement_definition_id")
            if md_id:
                desired = def_types.get(str(md_id))
                if desired and attrs.get("measurement_type") != desired:
                    attrs["measurement_type"] = desired
                    stats["nodes"] += 1
                    changed = True
        for child in node.get("content") or []:
            if _walk(child, def_types, stats):
                changed = True
    elif isinstance(node, list):
        for child in node:
            if _walk(child, def_types, stats):
                changed = True
    return changed


def backfill(apps, schema_editor):
    Substep = apps.get_model("Tracker", "Substep")
    MeasurementDefinition = apps.get_model("Tracker", "MeasurementDefinition")

    # id -> type for every definition (cross-tenant; migrations bypass scoping).
    # `_base_manager` because SecureModel's custom managers aren't available on
    # historical models in migrations.
    def_types = {
        str(pk): t
        for pk, t in MeasurementDefinition._base_manager.values_list("id", "type")
    }

    stats = {"nodes": 0, "substeps": 0}
    for sub in Substep._base_manager.exclude(body_blocks__isnull=True).iterator():
        body = sub.body_blocks
        if not body:
            continue
        if _walk(body, def_types, stats):
            sub.body_blocks = body
            sub.save(update_fields=["body_blocks"])
            stats["substeps"] += 1

    print(
        f"  backfilled measurement_type on {stats['nodes']} node(s) "
        f"across {stats['substeps']} substep(s)."
    )


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0078_documentlink'),
    ]

    operations = [
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
