# Generated by Django 5.1.6 on 2026-06-24 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0079_backfill_measurement_node_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementdefinition',
            name='backup_equipment',
            field=models.ForeignKey(blank=True, help_text='Fallback gauge/instrument when the default is unavailable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_for_measurements', to='Tracker.equipments'),
        ),
        migrations.AddField(
            model_name='measurementdefinition',
            name='characteristic_number',
            field=models.CharField(blank=True, help_text='Balloon number on the drawing (AS9102 / Control Plan reference).', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='measurementdefinition',
            name='default_equipment',
            field=models.ForeignKey(blank=True, help_text='Preferred gauge/instrument for this measurement (operator default).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_measurements', to='Tracker.equipments'),
        ),
    ]
