# Generated by Django 5.1.6 on 2026-06-26 12:04

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0080_measurementdefinition_backup_equipment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivingInspectionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('aql', models.DecimalField(decimal_places=3, help_text='Acceptable Quality Limit (e.g. 1.000, 0.650). Ignored when strategy=C0 uses Ac=0.', max_digits=5)),
                ('inspection_level', models.CharField(choices=[('I', 'General Level I'), ('II', 'General Level II'), ('III', 'General Level III')], default='II', max_length=3)),
                ('severity', models.CharField(choices=[('NORMAL', 'Normal'), ('TIGHTENED', 'Tightened'), ('REDUCED', 'Reduced')], default='NORMAL', help_text='AQL inspection severity (normal/tightened/reduced).', max_length=10)),
                ('strategy', models.CharField(choices=[('C0', 'Zero-acceptance (C=0 / Squeglia)'), ('Z14', 'ANSI/ASQ Z1.4')], default='C0', help_text='Acceptance-sampling strategy. C=0 is the default for aero/auto.', max_length=4)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Receiving Inspection Plan',
                'verbose_name_plural': 'Receiving Inspection Plans',
                'ordering': ['part_type', 'supplier'],
            },
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='qualityreports',
            name='accept_number',
            field=models.PositiveIntegerField(blank=True, help_text='Acceptance-sampling accept number (Ac) snapshot.', null=True),
        ),
        migrations.AddField(
            model_name='qualityreports',
            name='material_lot',
            field=models.ForeignKey(blank=True, help_text='Set when this report is a receiving inspection of an incoming lot (mutually exclusive with `part`).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_reports', to='Tracker.materiallot'),
        ),
        migrations.AddField(
            model_name='qualityreports',
            name='reject_number',
            field=models.PositiveIntegerField(blank=True, help_text='Acceptance-sampling reject number (Re) snapshot.', null=True),
        ),
        migrations.AddField(
            model_name='qualityreports',
            name='sample_size',
            field=models.PositiveIntegerField(blank=True, help_text='Acceptance-sampling sample size (n) snapshot at inspection time.', null=True),
        ),
        migrations.AlterField(
            model_name='materiallot',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('AWAITING_INSPECTION', 'Awaiting Inspection'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('IN_USE', 'In Use'), ('CONSUMED', 'Consumed'), ('SCRAPPED', 'Scrapped'), ('QUARANTINE', 'Quarantine')], default='RECEIVED', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='qualityreports',
            constraint=models.CheckConstraint(condition=models.Q(('part__isnull', False), ('material_lot__isnull', False), _negated=True), name='qualityreport_not_part_and_lot'),
        ),
        migrations.AddField(
            model_name='receivinginspectionplan',
            name='characteristics',
            field=models.ManyToManyField(blank=True, help_text="Measurements checked during receiving inspection. Empty = fall back to the part type's measurements.", related_name='receiving_inspection_plans', to='Tracker.measurementdefinition'),
        ),
        migrations.AddField(
            model_name='receivinginspectionplan',
            name='part_type',
            field=models.ForeignKey(help_text='Part type this plan inspects.', on_delete=django.db.models.deletion.PROTECT, related_name='receiving_inspection_plans', to='Tracker.parttypes'),
        ),
        migrations.AddField(
            model_name='receivinginspectionplan',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.receivinginspectionplan'),
        ),
        migrations.AddField(
            model_name='receivinginspectionplan',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Supplier this plan applies to. Null = applies to all suppliers of the part type.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receiving_inspection_plans', to='Tracker.companies'),
        ),
        migrations.AddField(
            model_name='receivinginspectionplan',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant'),
        ),
    ]
