# Generated by Django 5.1.6 on 2026-06-26 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0081_receivinginspectionplan_qualityreports_accept_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplingruleset',
            name='aql',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Acceptable Quality Limit for AQL/C=0 lot acceptance.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='samplingruleset',
            name='inspection_level',
            field=models.CharField(blank=True, help_text='ANSI/ASQ Z1.4 inspection level (I/II/III) for AQL sampling.', max_length=3),
        ),
        migrations.AddField(
            model_name='samplingruleset',
            name='severity',
            field=models.CharField(blank=True, help_text='AQL inspection severity (NORMAL/TIGHTENED/REDUCED).', max_length=10),
        ),
        migrations.AddField(
            model_name='samplingruleset',
            name='strategy',
            field=models.CharField(blank=True, help_text='Acceptance-sampling strategy: C0 (default) or Z14.', max_length=4),
        ),
        migrations.AddField(
            model_name='samplingruleset',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Supplier scope for receiving acceptance sampling. Null = all suppliers.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sampling_rulesets', to='Tracker.companies'),
        ),
        migrations.AlterField(
            model_name='samplingrule',
            name='rule_type',
            field=models.CharField(choices=[('EVERY_NTH_PART', 'Every Nth Part'), ('PERCENTAGE', 'Percentage of Parts'), ('RANDOM', 'Pure Random'), ('FIRST_N_PARTS', 'First N Parts'), ('LAST_N_PARTS', 'Last N Parts'), ('EXACT_COUNT', 'Exact Count (No Variance)'), ('AQL', 'Acceptance Sampling (ANSI/ASQ Z1.4)'), ('C_ZERO', 'Zero-Acceptance (C=0 / Squeglia)')], max_length=32),
        ),
        migrations.AlterField(
            model_name='steps',
            name='step_type',
            field=models.CharField(choices=[('TASK', 'Task'), ('START', 'Start'), ('DECISION', 'Decision'), ('REWORK', 'Rework'), ('TIMER', 'Timer/Wait'), ('TERMINAL', 'Terminal'), ('RECEIVING', 'Receiving Inspection')], default='TASK', help_text='Visual type for flow editor.', max_length=20),
        ),
        migrations.DeleteModel(
            name='ReceivingInspectionPlan',
        ),
    ]
