# Generated by Django 5.1.6 on 2026-06-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0082_samplingruleset_aql_samplingruleset_inspection_level_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stepexecution',
            name='step_execution_one_subject',
        ),
        migrations.AddConstraint(
            model_name='stepexecution',
            constraint=models.CheckConstraint(condition=models.Q(('part__isnull', False), ('core__isnull', False), _negated=True), name='step_execution_one_subject'),
        ),
    ]
