# Generated by Django 5.1.6 on 2026-06-26 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0083_remove_stepexecution_step_execution_one_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capa',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Supplier this CAPA is raised against (Supplier Corrective Action / SCAR).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_capas', to='Tracker.companies'),
        ),
        migrations.AddField(
            model_name='materiallot',
            name='erp_po_number',
            field=models.CharField(blank=True, help_text='ERP purchase-order reference (UQMES does not own purchasing).', max_length=100),
        ),
        migrations.AddField(
            model_name='materiallot',
            name='promised_date',
            field=models.DateField(blank=True, help_text="Supplier's promised delivery date (from the PO); drives on-time-delivery scoring.", null=True),
        ),
    ]
