# Generated by Django 5.1.6 on 2026-06-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0084_capa_supplier_materiallot_erp_po_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementresult',
            name='sample_number',
            field=models.PositiveIntegerField(blank=True, help_text='1-based index of the sampled unit within an acceptance-sampling inspection. Null = single/lot-level capture. A unit is a defective if any of its results is out of spec.', null=True),
        ),
    ]
