# Generated by Django 5.1.6 on 2026-06-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0085_measurementresult_sample_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityreports',
            name='defectives_found',
            field=models.PositiveIntegerField(blank=True, help_text="Bulk/attribute capture: number of defectives found across the sample (used when units aren't measured individually). Null = per-unit capture.", null=True),
        ),
    ]
