# Generated by Django 5.1.6 on 2026-06-26 17:34

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0086_qualityreports_defectives_found'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplingruleset',
            name='fallback_threshold',
        ),
        migrations.AddField(
            model_name='samplingruleset',
            name='gate_actions',
            field=models.JSONField(blank=True, default=list, help_text='List of GateAction codes to fire when the gate trips.'),
        ),
        migrations.AddField(
            model_name='samplingruleset',
            name='gate_approval_template',
            field=models.ForeignKey(blank=True, help_text='Template for a REQUIRE_APPROVAL action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='Tracker.approvaltemplate'),
        ),
        migrations.AddField(
            model_name='samplingruleset',
            name='gate_capa_severity',
            field=models.CharField(blank=True, help_text='Severity for a RAISE_CAPA_SCAR action.', max_length=10),
        ),
        migrations.AddField(
            model_name='samplingruleset',
            name='gate_capa_type',
            field=models.CharField(blank=True, help_text='CAPA type for a RAISE_CAPA_SCAR action (SUPPLIER => SCAR).', max_length=20),
        ),
        migrations.AddField(
            model_name='samplingruleset',
            name='gate_metric',
            field=models.CharField(blank=True, choices=[('CONSECUTIVE_FAILS', 'Consecutive failures'), ('FAIL_RATE_PCT', 'Failure rate (%)'), ('DEFECTIVE_COUNT', 'Defective count')], help_text='Aggregate signal this step watches. Blank = no gate.', max_length=20),
        ),
        migrations.AddField(
            model_name='samplingruleset',
            name='gate_min_sample',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum inspections before a FAIL_RATE_PCT gate can fire.', null=True),
        ),
        migrations.AddField(
            model_name='samplingruleset',
            name='gate_threshold',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Threshold: percent for FAIL_RATE_PCT, count otherwise.', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='samplingruleset',
            name='gate_window',
            field=models.CharField(blank=True, choices=[('WORK_ORDER', 'Whole work order at this step'), ('ROLLING_N', 'Rolling last N inspections'), ('LOT', 'Receiving lot sample')], help_text='Window the metric is computed over.', max_length=12),
        ),
        migrations.AddField(
            model_name='samplingruleset',
            name='gate_window_n',
            field=models.PositiveIntegerField(blank=True, help_text='N for ROLLING_N windows.', null=True),
        ),
        migrations.CreateModel(
            name='StepGateFiring',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('metric', models.CharField(choices=[('CONSECUTIVE_FAILS', 'Consecutive failures'), ('FAIL_RATE_PCT', 'Failure rate (%)'), ('DEFECTIVE_COUNT', 'Defective count')], max_length=20)),
                ('metric_value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('threshold', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('actions_taken', models.JSONField(blank=True, default=list)),
                ('fired_at', models.DateTimeField(auto_now_add=True)),
                ('approval_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='Tracker.approvalrequest')),
                ('created_capa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='Tracker.capa')),
                ('material_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tracker.materiallot')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.stepgatefiring')),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_firings', to='Tracker.samplingruleset')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tracker.steps')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant')),
                ('triggered_by_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='Tracker.qualityreports')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tracker.workorder')),
            ],
            options={
                'verbose_name': 'Step Gate Firing',
                'verbose_name_plural': 'Step Gate Firings',
                'constraints': [models.UniqueConstraint(condition=models.Q(('work_order__isnull', False)), fields=('tenant', 'ruleset', 'work_order', 'step'), name='stepgatefiring_wo_uniq'), models.UniqueConstraint(condition=models.Q(('material_lot__isnull', False)), fields=('tenant', 'ruleset', 'material_lot', 'step'), name='stepgatefiring_lot_uniq')],
            },
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
    ]
