# Generated by Django 5.1.6 on 2026-06-29 13:35

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0087_remove_samplingruleset_fallback_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parttypes',
            name='requires_supplier_qualification',
            field=models.BooleanField(default=False, help_text='Require an approved SupplierQualification covering the supplier before a received lot of this part type can be accepted into stock.'),
        ),
        migrations.AlterField(
            model_name='steps',
            name='decision_type',
            field=models.CharField(blank=True, choices=[('QA_RESULT', 'Based on QA Pass/Fail'), ('MEASUREMENT', 'Based on Measurement Threshold'), ('MANUAL', 'Manual Operator Selection'), ('AGGREGATE', 'Based on Quality Gate (aggregate signal)')], max_length=20),
        ),
        migrations.CreateModel(
            name='SupplierQualification',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('qualification_number', models.CharField(editable=False, max_length=20)),
                ('scope_type', models.CharField(choices=[('PART_TYPE', 'Part Type'), ('COMMODITY', 'Commodity'), ('SPECIAL_PROCESS', 'Special Process')], default='PART_TYPE', max_length=20)),
                ('scope_label', models.CharField(blank=True, help_text='Commodity or special-process name for COMMODITY/SPECIAL_PROCESS scopes.', max_length=120)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('CONDITIONAL', 'Conditional'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired'), ('DISQUALIFIED', 'Disqualified')], default='PENDING', max_length=15)),
                ('basis', models.CharField(blank=True, choices=[('AUDIT', 'Audit'), ('PPAP', 'PPAP'), ('FAI', 'First Article'), ('SURVEY', 'Survey'), ('HISTORICAL', 'Historical')], max_length=15)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approval_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='Tracker.approvalrequest')),
                ('part_type', models.ForeignKey(blank=True, help_text='Scope target when scope_type=PART_TYPE.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_qualifications', to='Tracker.parttypes')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.supplierqualification')),
                ('qualified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='Tracker.companies')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant')),
            ],
            options={
                'verbose_name': 'Supplier Qualification',
                'verbose_name_plural': 'Supplier Qualifications',
                'ordering': ['-created_at'],
                'permissions': [('approve_supplierqualification', 'Can grant/approve supplier qualifications')],
                'indexes': [models.Index(fields=['supplier', 'status'], name='squal_supplier_status_idx'), models.Index(fields=['status', 'expiry_date'], name='squal_status_expiry_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'qualification_number'), name='supplierqualification_tenant_number_uniq')],
            },
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
    ]
