# Generated by Django 5.1.6 on 2026-06-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0088_parttypes_requires_supplier_qualification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiallot',
            name='hold_reason',
            field=models.CharField(blank=True, help_text='Why a lot is held/quarantined (e.g. SUPPLIER_UNQUALIFIED). Lets the receiving queue explain a hold.', max_length=40),
        ),
    ]
