# Generated by Django 5.1.6 on 2026-06-30 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0089_materiallot_hold_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityreports',
            name='acceptability_constant_k',
            field=models.FloatField(blank=True, help_text='Z1.9 acceptability constant (k) snapshot; accept when x̄/s index ≥ k.', null=True),
        ),
        migrations.AddField(
            model_name='qualityreports',
            name='variables_characteristic',
            field=models.ForeignKey(blank=True, help_text='The characteristic measured for a Z1.9 variables acceptance decision.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variables_reports', to='Tracker.measurementdefinition'),
        ),
        migrations.AddField(
            model_name='samplingruleset',
            name='variables_characteristic',
            field=models.ForeignKey(blank=True, help_text='The single numeric characteristic a Z1.9 variables plan measures.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variables_rulesets', to='Tracker.measurementdefinition'),
        ),
        migrations.AlterField(
            model_name='samplingrule',
            name='rule_type',
            field=models.CharField(choices=[('EVERY_NTH_PART', 'Every Nth Part'), ('PERCENTAGE', 'Percentage of Parts'), ('RANDOM', 'Pure Random'), ('FIRST_N_PARTS', 'First N Parts'), ('LAST_N_PARTS', 'Last N Parts'), ('EXACT_COUNT', 'Exact Count (No Variance)'), ('AQL', 'Acceptance Sampling (ANSI/ASQ Z1.4)'), ('C_ZERO', 'Zero-Acceptance (C=0 / Squeglia)'), ('VARIABLES', 'Variables Sampling (ANSI/ASQ Z1.9)')], max_length=32),
        ),
        migrations.AlterField(
            model_name='samplingruleset',
            name='strategy',
            field=models.CharField(blank=True, help_text='Acceptance-sampling strategy: C0 (default), Z14, or Z19 (variables).', max_length=4),
        ),
    ]
