# Generated by Django 5.1.6 on 2026-07-04 13:38

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0090_qualityreports_acceptability_constant_k_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parttypes',
            name='requires_part_approval',
            field=models.BooleanField(default=False, help_text='Require an active PartApproval (PPAP/FAI) covering the (part type, supplier) before a received lot of this part type can be accepted into stock.'),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='approval_type',
            field=models.CharField(choices=[('DOCUMENT_RELEASE', 'Document Release'), ('CAPA_APPROVAL', 'CAPA Approval'), ('CAPA_CRITICAL', 'CAPA Critical'), ('CAPA_MAJOR', 'CAPA Major'), ('ECO', 'Engineering Change Order'), ('TRAINING_CERT', 'Training Certification'), ('PROCESS_APPROVAL', 'Process Approval'), ('PCR_APPROVAL', 'Process Change Request Approval'), ('PCO_APPROVAL', 'Process Change Order Approval'), ('PCN_RELEASE', 'Process Change Notice Release'), ('PPAP', 'PPAP'), ('FAI', 'First Article (FAI / AS9102)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='approvaltemplate',
            name='approval_type',
            field=models.CharField(choices=[('DOCUMENT_RELEASE', 'Document Release'), ('CAPA_APPROVAL', 'CAPA Approval'), ('CAPA_CRITICAL', 'CAPA Critical'), ('CAPA_MAJOR', 'CAPA Major'), ('ECO', 'Engineering Change Order'), ('TRAINING_CERT', 'Training Certification'), ('PROCESS_APPROVAL', 'Process Approval'), ('PCR_APPROVAL', 'Process Change Request Approval'), ('PCO_APPROVAL', 'Process Change Order Approval'), ('PCN_RELEASE', 'Process Change Notice Release'), ('PPAP', 'PPAP'), ('FAI', 'First Article (FAI / AS9102)')], max_length=50),
        ),
        migrations.CreateModel(
            name='PartApproval',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('approval_number', models.CharField(editable=False, max_length=20)),
                ('approval_type', models.CharField(choices=[('PPAP', 'PPAP'), ('FAI', 'First Article (FAI / AS9102)')], default='PPAP', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('CONDITIONAL', 'Conditional'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired'), ('DISQUALIFIED', 'Disqualified')], default='PENDING', max_length=15)),
                ('reference', models.CharField(blank=True, help_text='PPAP/FAI package or submission reference (the artifact stays external).', max_length=120)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approval_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='Tracker.approvalrequest')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('part_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_approvals', to='Tracker.parttypes')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.partapproval')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_approvals', to='Tracker.companies')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant')),
            ],
            options={
                'verbose_name': 'Part Approval',
                'verbose_name_plural': 'Part Approvals',
                'ordering': ['-created_at'],
                'permissions': [('approve_partapproval', 'Can grant/approve part approvals')],
                'indexes': [models.Index(fields=['part_type', 'supplier', 'status'], name='partappr_pt_sup_status_idx'), models.Index(fields=['status', 'expiry_date'], name='partappr_status_expiry_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'approval_number'), name='partapproval_tenant_number_uniq')],
            },
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
    ]
