# Generated by Django 5.1.6 on 2026-07-06 01:59

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0091_parttypes_requires_part_approval_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutsideProcessShipment',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('is_voided', models.BooleanField(default=False, help_text='Whether this record has been voided')),
                ('voided_at', models.DateTimeField(blank=True, help_text='When this record was voided', null=True)),
                ('void_reason', models.TextField(blank=True, help_text='Reason for voiding this record')),
                ('shipment_number', models.CharField(blank=True, help_text='Auto-generated, tenant-unique (OSP-YYYY-######).', max_length=100)),
                ('reference', models.CharField(blank=True, help_text='Outbound PO / packing-slip reference.', max_length=120)),
                ('shipped_at', models.DateTimeField(auto_now_add=True)),
                ('return_reference', models.CharField(blank=True, help_text='Inbound packing-slip reference on return.', max_length=120)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SENT', 'Sent Out'), ('RETURNED', 'Returned')], default='SENT', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Outside Process Shipment',
                'verbose_name_plural': 'Outside Process Shipments',
                'ordering': ['-shipped_at'],
            },
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='qualityreports',
            name='qualityreport_not_part_and_lot',
        ),
        migrations.AddField(
            model_name='steps',
            name='is_outside_process',
            field=models.BooleanField(default=False, help_text='If True, this step is performed by an outside vendor: parts are sent out (StepExecution send stamps / OutsideProcessShipment) and run a receiving-style return inspection when they come back. See services/mes/outside_process.py.'),
        ),
        migrations.AddField(
            model_name='steps',
            name='outside_supplier',
            field=models.ForeignKey(blank=True, help_text='Default subcontract vendor for this outside-process op (overridable per shipment).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outside_process_steps', to='Tracker.companies'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='part_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('AT_OUTSIDE_PROCESS', 'At Outside Process'), ('AWAITING_QA', 'Awaiting QA'), ('READY_FOR_NEXT_STEP', 'Ready for next step'), ('COMPLETED', 'Completed'), ('QUARANTINED', 'Quarantined'), ('REWORK_NEEDED', 'Rework Needed'), ('REWORK_IN_PROGRESS', 'Rework In Progress'), ('SCRAPPED', 'Scrapped'), ('CANCELLED', 'Cancelled'), ('SHIPPED', 'Shipped'), ('IN_STOCK', 'In Stock'), ('AWAITING_PICKUP', 'Awaiting Pickup'), ('CORE_BANKED', 'Core Banked'), ('RMA_CLOSED', 'RMA Closed')], default='PENDING', max_length=50),
        ),
        migrations.AddField(
            model_name='outsideprocessshipment',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.outsideprocessshipment'),
        ),
        migrations.AddField(
            model_name='outsideprocessshipment',
            name='returned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='osp_shipments_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outsideprocessshipment',
            name='shipped_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='osp_shipments_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outsideprocessshipment',
            name='step',
            field=models.ForeignKey(help_text='The outside-process step the parts are out for.', on_delete=django.db.models.deletion.PROTECT, related_name='outside_process_shipments', to='Tracker.steps'),
        ),
        migrations.AddField(
            model_name='outsideprocessshipment',
            name='supplier',
            field=models.ForeignKey(help_text='The subcontract vendor the parts were sent to.', on_delete=django.db.models.deletion.PROTECT, related_name='outside_process_shipments', to='Tracker.companies'),
        ),
        migrations.AddField(
            model_name='outsideprocessshipment',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant'),
        ),
        migrations.AddField(
            model_name='outsideprocessshipment',
            name='voided_by',
            field=models.ForeignKey(blank=True, help_text='User who voided this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outsideprocessshipment',
            name='work_order',
            field=models.ForeignKey(blank=True, help_text='The work order the shipped parts belong to (usually one).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outside_process_shipments', to='Tracker.workorder'),
        ),
        migrations.AddField(
            model_name='qualityreports',
            name='osp_shipment',
            field=models.ForeignKey(blank=True, help_text='Set when this report is the return inspection of a subcontract shipment (mutually exclusive with `part` / `material_lot`).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_reports', to='Tracker.outsideprocessshipment'),
        ),
        migrations.AddField(
            model_name='stepexecution',
            name='outside_process_shipment',
            field=models.ForeignKey(blank=True, help_text='The subcontract shipment this part left the building under, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='step_executions', to='Tracker.outsideprocessshipment'),
        ),
        migrations.AddConstraint(
            model_name='qualityreports',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('part__isnull', False), ('material_lot__isnull', False), _negated=True), models.Q(('part__isnull', False), ('osp_shipment__isnull', False), _negated=True), models.Q(('material_lot__isnull', False), ('osp_shipment__isnull', False), _negated=True)), name='qualityreport_at_most_one_subject'),
        ),
        migrations.AddIndex(
            model_name='outsideprocessshipment',
            index=models.Index(fields=['status', 'shipped_at'], name='Tracker_out_status_4d034d_idx'),
        ),
        migrations.AddIndex(
            model_name='outsideprocessshipment',
            index=models.Index(fields=['supplier', 'status'], name='Tracker_out_supplie_90160a_idx'),
        ),
        migrations.AddConstraint(
            model_name='outsideprocessshipment',
            constraint=models.UniqueConstraint(condition=models.Q(('shipment_number__isnull', False), models.Q(('shipment_number', ''), _negated=True)), fields=('tenant', 'shipment_number'), name='osp_shipment_tenant_number_uniq'),
        ),
    ]
