# Generated by Django 5.1.6 on 2026-07-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0092_outsideprocessshipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outsideprocessshipment',
            name='status',
            field=models.CharField(choices=[('SENT', 'Sent Out'), ('RETURNED', 'Returned'), ('CLOSED', 'Closed')], default='SENT', max_length=20),
        ),
    ]
