# Generated by Django 5.1.6 on 2026-07-07 13:47

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0093_alter_outsideprocessshipment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SamplingSeverityState',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('severity', models.CharField(choices=[('NORMAL', 'Normal'), ('TIGHTENED', 'Tightened'), ('REDUCED', 'Reduced')], default='NORMAL', max_length=10)),
                ('severity_since', models.DateTimeField(blank=True, null=True)),
                ('discontinued', models.BooleanField(default=False)),
                ('recent_outcomes', models.JSONField(blank=True, default=list)),
                ('consecutive_accepts', models.PositiveIntegerField(default=0)),
                ('lots_in_regime', models.PositiveIntegerField(default=0)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.samplingseveritystate')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='severity_states', to='Tracker.steps')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='severity_states', to='Tracker.companies')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant')),
            ],
            options={
                'verbose_name': 'Sampling Severity State',
                'verbose_name_plural': 'Sampling Severity States',
                'indexes': [models.Index(fields=['step', 'supplier'], name='sevstate_step_sup_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'step', 'supplier'), name='samplingseveritystate_tenant_uniq')],
            },
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
    ]
