# Generated by Django 5.1.6 on 2026-07-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0094_samplingseveritystate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approverassignment',
            name='assignment_source',
            field=models.CharField(choices=[('TEMPLATE_DEFAULT', 'Template Default'), ('TEMPLATE_GROUP', 'Template Group Auto-Assign'), ('MANUAL', 'Manual Assignment'), ('DELEGATION', 'Delegated'), ('ESCALATION', 'Escalation'), ('CLAIMED', 'Claimed from Group')], default='MANUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='groupapproverassignment',
            name='assignment_source',
            field=models.CharField(choices=[('TEMPLATE_DEFAULT', 'Template Default'), ('TEMPLATE_GROUP', 'Template Group Auto-Assign'), ('MANUAL', 'Manual Assignment'), ('DELEGATION', 'Delegated'), ('ESCALATION', 'Escalation'), ('CLAIMED', 'Claimed from Group')], default='TEMPLATE_GROUP', max_length=20),
        ),
    ]
