# Generated by Django 5.1.6 on 2026-07-08 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0095_alter_approverassignment_assignment_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpirecord',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, help_text='When the pending request was acknowledged', null=True),
        ),
        migrations.AddField(
            model_name='fpirecord',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, help_text='QA user who acknowledged the pending request (is on it)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
