# Generated by Django 5.1.6 on 2026-07-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0096_fpirecord_acknowledged_at_fpirecord_acknowledged_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarantinedisposition',
            name='due_date',
            field=models.DateField(blank=True, help_text='Target resolution date — drives the due dot on quality inboxes', null=True),
        ),
    ]
