# Generated by Django 5.1.6 on 2026-07-13 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0097_quarantinedisposition_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityreports',
            name='step_execution',
            field=models.ForeignKey(blank=True, help_text='The part-visit whose capture produced this report (DWI inspection points).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_reports', to='Tracker.stepexecution'),
        ),
        migrations.AddField(
            model_name='qualityreports',
            name='substep',
            field=models.ForeignKey(blank=True, help_text='The substep whose capture produced this report. One report per (step_execution, substep) inspection event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_reports', to='Tracker.substep'),
        ),
        migrations.AddIndex(
            model_name='qualityreports',
            index=models.Index(fields=['step_execution', 'substep'], name='qr_exec_substep_idx'),
        ),
        migrations.AddConstraint(
            model_name='qualityreports',
            constraint=models.UniqueConstraint(condition=models.Q(('step_execution__isnull', False), ('substep__isnull', False)), fields=('step_execution', 'substep'), name='qualityreport_exec_substep_uniq'),
        ),
    ]
