# Generated by Django 5.1.6 on 2026-07-14 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0098_qualityreports_step_execution_qualityreports_substep_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stepexecutionmeasurement',
            options={'ordering': ['recorded_at'], 'verbose_name': 'Step Execution Measurement', 'verbose_name_plural': 'Step Execution Measurements'},
        ),
        migrations.AddField(
            model_name='qualityreports',
            name='batch_execution',
            field=models.ForeignKey(blank=True, help_text='The batch whose capture produced this report, for BATCH-scope inspection substeps (wash/heat-treat/plating cycles). Mutually exclusive with step_execution — a report is per-part OR per-batch, never both.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_reports', to='Tracker.batchexecution'),
        ),
        migrations.AddField(
            model_name='stepexecutionmeasurement',
            name='batch_execution',
            field=models.ForeignKey(blank=True, help_text='The batch this reading belongs to, for BATCH-scope substeps (one cycle reading for the whole load). Mutually exclusive with step_execution.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='Tracker.batchexecution'),
        ),
        migrations.AlterField(
            model_name='qualityreports',
            name='substep',
            field=models.ForeignKey(blank=True, help_text='The substep whose capture produced this report. One report per (step_execution, substep) or (batch_execution, substep) event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_reports', to='Tracker.substep'),
        ),
        migrations.AlterField(
            model_name='stepexecutionmeasurement',
            name='step_execution',
            field=models.ForeignKey(blank=True, help_text='The part-visit this reading belongs to. Null for BATCH-scope measurements, which key on batch_execution instead.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='Tracker.stepexecution'),
        ),
        migrations.AddIndex(
            model_name='qualityreports',
            index=models.Index(fields=['batch_execution', 'substep'], name='qr_batch_substep_idx'),
        ),
        migrations.AddIndex(
            model_name='stepexecutionmeasurement',
            index=models.Index(fields=['batch_execution', 'measurement_definition'], name='dwi_sem_batch_def_idx'),
        ),
        migrations.AddConstraint(
            model_name='qualityreports',
            constraint=models.UniqueConstraint(condition=models.Q(('batch_execution__isnull', False), ('substep__isnull', False)), fields=('batch_execution', 'substep'), name='qualityreport_batch_substep_uniq'),
        ),
        migrations.AddConstraint(
            model_name='qualityreports',
            constraint=models.CheckConstraint(condition=models.Q(('step_execution__isnull', False), ('batch_execution__isnull', False), _negated=True), name='qualityreport_not_both_provenance'),
        ),
        migrations.AddConstraint(
            model_name='stepexecutionmeasurement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('batch_execution__isnull', True), ('step_execution__isnull', False)), models.Q(('batch_execution__isnull', False), ('step_execution__isnull', True)), _connector='OR'), name='sem_exactly_one_target'),
        ),
    ]
