# Generated by Django 5.1.6 on 2026-07-14 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0099_alter_stepexecutionmeasurement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarantinedisposition',
            name='batch_execution',
            field=models.ForeignKey(blank=True, help_text="Set when this disposition covers a failed batch cycle (the whole load), instead of a single part. Affected parts are the batch's members. Mutually exclusive with `part` in practice.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispositions', to='Tracker.batchexecution'),
        ),
    ]
