# Generated by Django 5.1.6 on 2026-07-14 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0100_quarantinedisposition_batch_execution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualityreports',
            name='machine',
        ),
    ]
