# Generated by Django 5.1.6 on 2026-07-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0101_remove_qualityreports_machine'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='quarantinedisposition',
            constraint=models.CheckConstraint(condition=models.Q(('part__isnull', False), ('batch_execution__isnull', False), _negated=True), name='disposition_not_both_part_and_batch'),
        ),
    ]
