# Generated by Django 5.1.6 on 2026-07-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0102_quarantinedisposition_disposition_not_both_part_and_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps',
            name='operation_number',
            field=models.CharField(blank=True, default='', help_text="Human-facing operation number for travelers/routing (e.g. '10', '20', 'OP-30'). Free-form; blank falls back to the routing position.", max_length=20),
        ),
    ]
