# Generated by Django 5.1.6 on 2026-07-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0103_steps_operation_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='entry_type',
            field=models.CharField(choices=[('PRODUCTION', 'Production'), ('SETUP', 'Setup/Changeover'), ('REWORK', 'Rework'), ('DOWNTIME', 'Downtime'), ('INDIRECT', 'Indirect Labor'), ('BREAK', 'Break'), ('LUNCH', 'Lunch')], max_length=20),
        ),
    ]
