# Generated by Django 5.1.6 on 2026-07-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0104_alter_timeentry_entry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='entry_type',
            field=models.CharField(choices=[('PRODUCTION', 'Production'), ('SETUP', 'Setup/Changeover'), ('REWORK', 'Rework'), ('DOWNTIME', 'Downtime'), ('INDIRECT', 'Indirect Labor'), ('SHIFT', 'On Shift'), ('BREAK', 'Break'), ('LUNCH', 'Lunch')], max_length=20),
        ),
    ]
