# Generated by Django 5.1.6 on 2026-07-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0106_shiftnote_shiftnoteack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftnote',
            name='acknowledgment_required',
            field=models.BooleanField(default=False),
        ),
    ]
