# Generated by Django 5.1.6 on 2026-07-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0107_shiftnote_acknowledgment_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrecord',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Level 1 — Trainee (supervised)'), (2, 'Level 2 — Assisted (output checked)'), (3, 'Level 3 — Qualified (independent)'), (4, 'Level 4 — Expert (can train/sign off others)')], default=3, help_text='Assessed competency level reached by this record (1-4). This is the assessed result, not mere attendance — clause 7.2 evidence.'),
        ),
        migrations.AddField(
            model_name='trainingrequirement',
            name='min_level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Level 1 — Trainee (supervised)'), (2, 'Level 2 — Assisted (output checked)'), (3, 'Level 3 — Qualified (independent)'), (4, 'Level 4 — Expert (can train/sign off others)')], default=3, help_text='Minimum competency level required to be authorized (1-4). Default Qualified (3) = must be independently qualified.'),
        ),
    ]
