# Generated by Django 5.1.6 on 2026-07-20 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0108_trainingrecord_level_trainingrequirement_min_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingrecord',
            options={'ordering': ['-completed_date'], 'permissions': [('view_training_matrix', 'Can view the org-wide training competency matrix')], 'verbose_name': 'Training Record', 'verbose_name_plural': 'Training Records'},
        ),
    ]
