# Generated by Django 5.1.6 on 2026-07-20 19:00

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0109_alter_trainingrecord_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True, help_text='Inactive roles are hidden from assignment pickers.')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.jobrole')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant')),
            ],
            options={
                'verbose_name': 'Job Role',
                'verbose_name_plural': 'Job Roles',
                'ordering': ['name'],
            },
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='trainingrequirement',
            name='job_role',
            field=models.ForeignKey(blank=True, help_text='Role-scoped requirement: the competence this job role must hold.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_requirements', to='Tracker.jobrole'),
        ),
        migrations.AddField(
            model_name='user',
            name='job_role',
            field=models.ForeignKey(blank=True, help_text='Primary job role / position — drives the required-competency profile.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='Tracker.jobrole'),
        ),
        migrations.AddConstraint(
            model_name='trainingrequirement',
            constraint=models.UniqueConstraint(condition=models.Q(('job_role__isnull', False)), fields=('training_type', 'job_role'), name='unique_training_per_job_role'),
        ),
    ]
