# Generated by Django 5.1.6 on 2026-07-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0110_jobrole_trainingrequirement_job_role_user_job_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stepexecution',
            options={'ordering': ['entered_at'], 'permissions': [('override_training_gate', 'Can override the training authorization gate to start unqualified work')], 'verbose_name': 'Step Execution', 'verbose_name_plural': 'Step Executions'},
        ),
        migrations.AddField(
            model_name='stepexecution',
            name='training_authorization',
            field=models.JSONField(blank=True, help_text="Snapshot of the operator's training authorization at work start (audit trail). Includes the supervisor override, if one was used.", null=True),
        ),
    ]
