# Generated by Django 5.1.6 on 2026-07-23 18:42

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0111_alter_stepexecution_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps',
            name='work_center',
            field=models.ForeignKey(blank=True, help_text="The work-center where this step runs. Primary routing signal for which surface (operator queue / QA inbox / receiving) the step belongs on. Nullable during migration; unmapped steps surface in a 'no-work-center' bucket. See Documents/WORK_CENTER_DESIGN.md.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='steps', to='Tracker.workcenter'),
        ),
        migrations.AddField(
            model_name='workcenter',
            name='kind',
            field=models.CharField(choices=[('PRODUCTION', 'Production'), ('INSPECTION', 'Inspection'), ('RECEIVING', 'Receiving'), ('OSP', 'Outside Process')], default='PRODUCTION', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='recipient_strategy',
            field=models.CharField(choices=[('static', 'Static - recipients from this rule only'), ('from_payload', 'From event - recipients from the event payload'), ('union', "Union - combine event-payload recipients with this rule's")], default='static', help_text="Where to pull recipients from at fire time. 'static' uses the rule's M2M lists only; 'from_payload' reads recipient IDs from the event's payload; 'union' combines both.", max_length=16),
        ),
        migrations.AlterField(
            model_name='qualityreports',
            name='batch_execution',
            field=models.ForeignKey(blank=True, help_text='The batch whose capture produced this report, for BATCH-scope inspection substeps (wash/heat-treat/plating cycles). Mutually exclusive with step_execution - a report is per-part OR per-batch, never both.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_reports', to='Tracker.batchexecution'),
        ),
        migrations.AlterField(
            model_name='qualityreports',
            name='detected_by',
            field=models.ForeignKey(help_text='DEPRECATED - use `personnel` (role=DETECTED_BY). Kept for back-compat.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='defects_detected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qualityreports',
            name='operators',
            field=models.ManyToManyField(blank=True, help_text='DEPRECATED - use `personnel` (role=OPERATOR). Kept for back-compat.', related_name='defects_during_operation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qualityreports',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED - use `personnel` (role=VERIFIED_BY). Kept for back-compat.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defects_verified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quarantinedisposition',
            name='due_date',
            field=models.DateField(blank=True, help_text='Target resolution date - drives the due dot on quality inboxes', null=True),
        ),
        migrations.AlterField(
            model_name='samplingdecision',
            name='outcome',
            field=models.CharField(choices=[('selected', 'Selected'), ('deselected', 'Deselected'), ('pending', 'Pending')], help_text='What the rule decided - SELECTED, DESELECTED, or PENDING.', max_length=12),
        ),
        migrations.AlterField(
            model_name='substep',
            name='scope',
            field=models.CharField(choices=[('sampled', 'Per part (sampling)'), ('batch', 'Per batch')], default='sampled', help_text='Whether the substep runs per part (SAMPLED, default - uses sampling_rule for cadence, null rule = 100%) or once for the whole batch (BATCH - oven cycles, wash tanks, plating baths). BATCH substeps write captures against a `BatchExecution` shared by every part in the batch, instead of per-part `StepExecution`.', max_length=10),
        ),
        migrations.AlterField(
            model_name='substepgatecompletion',
            name='node_id',
            field=models.CharField(help_text="UUIDv7 of the AttestationCheckpoint node in Substep.body_blocks (minted client-side per decision #18). Stable across the substep's lifetime as long as the engineer doesn't cut-paste the node - see src/lib/dwi/node-id.ts.", max_length=64),
        ),
        migrations.AlterField(
            model_name='trainingrecord',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Level 1 - Trainee (supervised)'), (2, 'Level 2 - Assisted (output checked)'), (3, 'Level 3 - Qualified (independent)'), (4, 'Level 4 - Expert (can train/sign off others)')], default=3, help_text='Assessed competency level reached by this record (1-4). This is the assessed result, not mere attendance - clause 7.2 evidence.'),
        ),
        migrations.AlterField(
            model_name='trainingrequirement',
            name='min_level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Level 1 - Trainee (supervised)'), (2, 'Level 2 - Assisted (output checked)'), (3, 'Level 3 - Qualified (independent)'), (4, 'Level 4 - Expert (can train/sign off others)')], default=3, help_text='Minimum competency level required to be authorized (1-4). Default Qualified (3) = must be independently qualified.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='job_role',
            field=models.ForeignKey(blank=True, help_text='Primary job role / position - drives the required-competency profile.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='Tracker.jobrole'),
        ),
        migrations.CreateModel(
            name='UserWorkCenterMembership',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False, help_text="The user's preferred default station (drives the operator home's initial scope).")),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.userworkcentermembership')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_center_memberships', to=settings.AUTH_USER_MODEL)),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_memberships', to='Tracker.workcenter')),
            ],
            options={
                'verbose_name': 'Work Center Membership',
                'verbose_name_plural': 'Work Center Memberships',
                'indexes': [models.Index(fields=['user', 'is_primary'], name='Tracker_use_user_id_890fad_idx'), models.Index(fields=['work_center'], name='Tracker_use_work_ce_43cc42_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'work_center'), name='userworkcentermembership_user_wc_uniq')],
            },
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
    ]
