# Generated by Django 5.1.6 on 2026-08-03 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0112_steps_work_center_workcenter_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps',
            name='part_advancement_mode',
            field=models.CharField(choices=[('COHORT', 'Cohort — all-or-none (all parts must clear before any advance)'), ('PER_PART', 'Per-part — each part advances independently on its own gate')], default='COHORT', help_text="Non-batch steps only. Batch steps are always per-load. COHORT: classic lot cohesion — the whole (WO, step) cohort waits until every part clears. Use for shared-context steps where the batch legitimately moves together. PER_PART: each part advances on its own gate — a failed part doesn't hold up passing parts. Use for individually-inspected QA-decision steps (Nozzle Inspection, Flow Testing, Final Test).", max_length=16),
        ),
    ]
