# Generated by Django 5.1.6 on 2026-08-05 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0113_add_step_part_advancement_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpirecord',
            name='performed_by',
            field=models.ForeignKey(blank=True, help_text='Operator at whose station a QA person co-signed this buy-off (distinct from inspected_by, the attester). Null for a direct QA sign-off.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
