# Generated by Django 5.1.6 on 2026-08-05 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0114_fpirecord_performed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='steptransitionlog',
            name='authorized_by',
            field=models.ForeignKey(blank=True, help_text='User who authorized the transition when different from the operator who performed it (co-signed routing). Null otherwise.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
