# Generated by Django 5.1.6 on 2026-08-06 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0115_steptransitionlog_authorized_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarantinedisposition',
            name='decision_authorized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quarantinedisposition',
            name='decision_authorized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_dispositions', to=settings.AUTH_USER_MODEL),
        ),
    ]
