# Generated by Django 5.1.6 on 2026-08-17 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0116_quarantinedisposition_decision_authorized_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steprollback',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='steprollback',
            name='executed_by',
        ),
        migrations.RemoveField(
            model_name='steprollback',
            name='from_step',
        ),
        migrations.RemoveField(
            model_name='steprollback',
            name='ncr_reference',
        ),
        migrations.RemoveField(
            model_name='steprollback',
            name='part',
        ),
        migrations.RemoveField(
            model_name='steprollback',
            name='previous_version',
        ),
        migrations.RemoveField(
            model_name='steprollback',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='steprollback',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='steprollback',
            name='to_step',
        ),
        migrations.DeleteModel(
            name='BatchRollback',
        ),
        migrations.DeleteModel(
            name='StepRollback',
        ),
    ]
