# Generated by Django 5.1.6 on 2026-08-18 16:23

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid_utils.compat
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0117_drop_step_batch_rollback'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomline',
            name='source',
            field=models.CharField(choices=[('MAKE', 'Made in-house'), ('BUY', 'Purchased')], default='BUY', help_text='Make-vs-buy: MAKE spawns an in-house child WO the parent assembly pegs to (WorkOrder.pegged_to_bom_line); BUY is procured. Plan #9.', max_length=4),
        ),
        migrations.AddField(
            model_name='stepedge',
            name='tech_continuity',
            field=models.CharField(choices=[('ANY', 'Any operator'), ('SAME', 'Same operator'), ('DIFFERENT', 'Different operator')], default='ANY', help_text='Scheduling: whether from→to must be run by the same operator (SAME), a different one (DIFFERENT — e.g. independent verification), or ANY.', max_length=10),
        ),
        migrations.AddField(
            model_name='stepexecution',
            name='equipment',
            field=models.ForeignKey(blank=True, help_text='Machine that ran this step (machine-attributed timing / OEE). Stamped at DWI submit; falls back to step.default_equipment. Nullable for history and no-machine steps (plan #1).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='step_executions', to='Tracker.equipments'),
        ),
        migrations.AddField(
            model_name='steps',
            name='max_continuous_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Scheduling constraint: maximum continuous minutes for this step (e.g. max machine run before a required pause, or max hold before the next op must start — cure/dry/transport). Null = unconstrained.', null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='pegged_to_bom_line',
            field=models.ForeignKey(blank=True, help_text='The parent BOM line this component job fills (plan #9).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pegged_workorders', to='Tracker.bomline'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='pegged_to_workorder',
            field=models.ForeignKey(blank=True, help_text='Parent assembly WO this in-house component job feeds (plan #9).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='component_pegs', to='Tracker.workorder'),
        ),
        migrations.CreateModel(
            name='ContinuousMachine',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('parts_per_hour', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('bar_change_interval_hours', models.FloatField(blank=True, help_text='Hours of run between bar changes (null = no bar changes).', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('bar_change_duration_minutes', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('equipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='continuous_profile', to='Tracker.equipments')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.continuousmachine')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant')),
            ],
            options={
                'verbose_name': 'Continuous Machine',
                'verbose_name_plural': 'Continuous Machines',
            },
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='How many of this fixture exist (concurrency limit).')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.fixture')),
                ('steps', models.ManyToManyField(blank=True, help_text='Steps that require this fixture.', related_name='fixtures', to='Tracker.steps')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant')),
            ],
            options={
                'verbose_name': 'Fixture',
                'verbose_name_plural': 'Fixtures',
            },
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleResult',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('horizon_start', models.DateTimeField()),
                ('horizon_end', models.DateTimeField()),
                ('solver_status', models.CharField(choices=[('OPTIMAL', 'Optimal'), ('FEASIBLE', 'Feasible'), ('INFEASIBLE', 'Infeasible'), ('MODEL_INVALID', 'Model invalid'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=15)),
                ('solve_time_ms', models.PositiveIntegerField(default=0)),
                ('objective_value_cents', models.BigIntegerField(default=0, help_text='Objective (total cost) in cents.')),
                ('is_stale', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.scheduleresult')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant')),
            ],
            options={
                'verbose_name': 'Schedule Result',
                'verbose_name_plural': 'Schedule Results',
                'ordering': ['-created_at'],
            },
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_pinned', models.BooleanField(default=False, help_text='Planner-pinned: the solver must keep this fixed.')),
                ('fence_zone', models.CharField(choices=[('frozen', 'Frozen'), ('slushy', 'Slushy'), ('liquid', 'Liquid')], default='liquid', max_length=6)),
                ('machine', models.ForeignKey(blank=True, help_text='Assigned machine (null if the step needs none).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_tasks', to='Tracker.equipments')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tasks', to='Tracker.parts')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.scheduledtask')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_tasks', to='Tracker.steps')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='Tracker.scheduleresult')),
            ],
            options={
                'verbose_name': 'Scheduled Task',
                'verbose_name_plural': 'Scheduled Tasks',
                'ordering': ['start_time'],
            },
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='StepEquipmentAffinity',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('affinity', models.CharField(choices=[('eligible', 'Eligible'), ('preferred', 'Preferred'), ('dialed_in', 'Dialed in (proven best)')], default='eligible', max_length=10)),
                ('cycle_time_override', models.FloatField(blank=True, help_text='Per-piece cycle on THIS machine, overriding StepTiming (a faster or slower machine for the same step).', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_affinities', to='Tracker.equipments')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.stepequipmentaffinity')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_affinities', to='Tracker.steps')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant')),
            ],
            options={
                'verbose_name': 'Step-Equipment Affinity',
                'verbose_name_plural': 'Step-Equipment Affinities',
            },
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='StepTiming',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('setup_minutes', models.FloatField(default=0, help_text='Internal (machine-stopped) setup / changeover minutes.', validators=[django.core.validators.MinValueValidator(0)])),
                ('cycle_time_minutes', models.FloatField(default=0, help_text='Deterministic per-piece machine cycle time (minutes).', validators=[django.core.validators.MinValueValidator(0)])),
                ('load_unload_per_piece', models.FloatField(default=0, help_text='Operator touch time to load/unload one piece (minutes).', validators=[django.core.validators.MinValueValidator(0)])),
                ('attention_type', models.CharField(choices=[('full', 'Full attention (operator tied to the machine)'), ('load_unload', 'Load/unload only (machine runs unattended between)')], default='full', help_text='Whether the operator is tied to the machine (full) or only loads/unloads (enables multi-machine tending in Layer 2).', max_length=12)),
                ('external_setup_minutes', models.FloatField(default=0, help_text="SMED external setup that can overlap the previous op's run time.", validators=[django.core.validators.MinValueValidator(0)])),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.steptiming')),
                ('step', models.OneToOneField(help_text='The step these timings describe.', on_delete=django.db.models.deletion.CASCADE, related_name='timing', to='Tracker.steps')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant')),
            ],
            options={
                'verbose_name': 'Step Timing',
                'verbose_name_plural': 'Step Timings',
            },
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='WorkCenterChangeover',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('changeover_minutes', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changeovers', to='Tracker.equipments')),
                ('from_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changeovers_from', to='Tracker.steps')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.workcenterchangeover')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant')),
                ('to_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changeovers_to', to='Tracker.steps')),
            ],
            options={
                'verbose_name': 'Work-Center Changeover',
                'verbose_name_plural': 'Work-Center Changeovers',
            },
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='OptimizationConfig',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('shop_rate_per_hour', models.DecimalField(decimal_places=2, default=Decimal('75.00'), help_text='Labor + overhead cost per shop hour (objective input).', max_digits=10)),
                ('overtime_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=4)),
                ('late_penalty_urgent', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=10)),
                ('late_penalty_high', models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=10)),
                ('late_penalty_normal', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10)),
                ('late_penalty_low', models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=10)),
                ('frozen_zone_days', models.PositiveIntegerField(default=2, help_text='Days from now within which tasks are pinned (frozen).')),
                ('slushy_zone_days', models.PositiveIntegerField(default=7, help_text='Days after the frozen zone where moves are discouraged.')),
                ('pfd_allowance_pct', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Personal/fatigue/delay allowance added to attended time (%).', max_digits=5)),
                ('relative_gap_limit', models.FloatField(default=0.02, help_text='CP-SAT relative optimality gap to stop at (e.g. 0.02 = 2%).', validators=[django.core.validators.MinValueValidator(0)])),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.optimizationconfig')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant')),
            ],
            options={
                'verbose_name': 'Optimization Config',
                'verbose_name_plural': 'Optimization Configs',
                'constraints': [models.UniqueConstraint(fields=('tenant',), name='optimization_config_one_per_tenant')],
            },
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='scheduleresult',
            index=models.Index(fields=['is_active', 'is_stale'], name='Tracker_sch_is_acti_aa0a93_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledtask',
            index=models.Index(fields=['schedule', 'start_time'], name='Tracker_sch_schedul_0516b6_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledtask',
            index=models.Index(fields=['machine', 'start_time'], name='Tracker_sch_machine_894f3b_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledtask',
            index=models.Index(fields=['part', 'step'], name='Tracker_sch_part_id_4be0bd_idx'),
        ),
        migrations.AddIndex(
            model_name='stepequipmentaffinity',
            index=models.Index(fields=['equipment', 'affinity'], name='Tracker_ste_equipme_526ec1_idx'),
        ),
        migrations.AddConstraint(
            model_name='stepequipmentaffinity',
            constraint=models.UniqueConstraint(fields=('step', 'equipment'), name='step_equipment_affinity_uniq'),
        ),
        migrations.AddConstraint(
            model_name='workcenterchangeover',
            constraint=models.UniqueConstraint(fields=('equipment', 'from_step', 'to_step'), name='workcenter_changeover_uniq'),
        ),
    ]
