# Generated by Django 5.1.6 on 2026-08-18 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0118_bomline_source_stepedge_tech_continuity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EquipmentUsage',
        ),
    ]
