# Generated by Django 5.1.6 on 2026-08-18 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0119_delete_equipmentusage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stepexecution',
            name='equipment',
        ),
        migrations.AddField(
            model_name='equipments',
            name='is_schedulable',
            field=models.BooleanField(default=False, help_text='Whether the scheduler treats this asset as a finite resource to reserve (CNC, Keyence, CMM). Off for plentiful/handheld equipment (calipers) — those are still tracked on step executions, just never scheduled. Capacity for a type = the count of its schedulable units.'),
        ),
        migrations.CreateModel(
            name='StepExecutionEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PRODUCTION', 'Production machine'), ('FIXTURE', 'Fixture / hold-down'), ('TOOL', 'Cutting / forming tool'), ('GAUGE', 'Inspection gauge / instrument'), ('OTHER', 'Other')], default='PRODUCTION', help_text='What role this equipment played in this step visit.', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_execution_links', to='Tracker.equipments')),
                ('step_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_links', to='Tracker.stepexecution')),
            ],
            options={
                'indexes': [models.Index(fields=['equipment', 'role'], name='stepexec_equipment_role_idx')],
                'constraints': [models.UniqueConstraint(fields=('step_execution', 'equipment', 'role'), name='stepexec_equipment_role_uniq')],
            },
        ),
    ]
