# Generated by Django 5.1.6 on 2026-08-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0120_remove_stepexecution_equipment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='break_windows',
            field=models.JSONField(blank=True, default=list, help_text='Scheduled breaks/lunch within the shift, as a list of {"start": "HH:MM", "end": "HH:MM"}. The scheduler keeps attended (full-attention) work out of these windows; actual clock-out/in is captured separately as TimeEntry BREAK/LUNCH entries.'),
        ),
    ]
