# Generated by Django 5.1.6 on 2026-08-18 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0121_shift_break_windows'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='assigned_operator',
            field=models.ForeignKey(blank=True, help_text='Layer-2 operator assignment; null on an attended task means the dispatcher could not cover it (no qualified operator free).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='requires_operator',
            field=models.BooleanField(default=True, help_text='Whether this task needs an operator (false for unattended runs).'),
        ),
        migrations.AddIndex(
            model_name='scheduledtask',
            index=models.Index(fields=['assigned_operator', 'start_time'], name='Tracker_sch_assigne_e4e917_idx'),
        ),
    ]
