# Generated by Django 5.1.6 on 2026-08-18 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0122_scheduledtask_assigned_operator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_shift',
            field=models.ForeignKey(blank=True, help_text="The shift this operator is rostered to. Layer-2 dispatch only assigns work during this shift's windows; an operator with no shift is not dispatchable.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rostered_operators', to='Tracker.shift'),
        ),
    ]
