# Generated by Django 5.1.6 on 2026-08-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0123_user_default_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationconfig',
            name='staging_buffer_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Minutes between a component WO finishing and its parent assembly WO being allowed to start (move/stage time). Assembly-convergence peg — plan #9.'),
        ),
    ]
