# Generated by Django 5.1.6 on 2026-08-19 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0124_optimizationconfig_staging_buffer_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomline',
            name='consumed_at_step',
            field=models.ForeignKey(blank=True, help_text="The parent-process step that consumes this component (the assembly step). When set, the scheduler gates only that step on the component WO's completion; when null, the whole parent waits. Plan #9.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bom_lines_consumed_here', to='Tracker.steps'),
        ),
    ]
