# Generated by Django 5.1.6 on 2026-08-19 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0125_bomline_consumed_at_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='core',
            field=models.ForeignKey(blank=True, help_text='Reman core being torn down (mutually exclusive with `part`).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tasks', to='Tracker.core'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tasks', to='Tracker.parts'),
        ),
        migrations.AddIndex(
            model_name='scheduledtask',
            index=models.Index(fields=['core', 'step'], name='Tracker_sch_core_id_4550db_idx'),
        ),
        migrations.AddConstraint(
            model_name='scheduledtask',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('core__isnull', True), ('part__isnull', False)), models.Q(('core__isnull', False), ('part__isnull', True)), _connector='OR'), name='scheduledtask_part_xor_core'),
        ),
    ]
