# Generated by Django 5.1.6 on 2026-08-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0126_scheduledtask_core_alter_scheduledtask_part_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleresult',
            name='relaxed_pin_count',
            field=models.PositiveIntegerField(default=0, help_text="Frozen/planner-pinned tasks the solver had to move because the world changed under them (machine down, shift edited). >0 means the freeze couldn't be fully honored — surface for the planner."),
        ),
    ]
