# Generated by Django 5.1.6 on 2026-08-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0127_scheduleresult_relaxed_pin_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleresult',
            name='weighted_lateness',
            field=models.BigIntegerField(default=0, help_text="Priority-weighted lateness only (Σ part late-minutes × the WO's priority penalty) — the objective's lateness term, isolated from makespan and pin penalties. The 'how late, weighted by priority' signal shown in the UI."),
        ),
        migrations.AlterField(
            model_name='scheduleresult',
            name='objective_value_cents',
            field=models.BigIntegerField(default=0, help_text="Raw CP-SAT objective (lateness + makespan + pin-stickiness penalties). NOT money despite the legacy 'cents' name — the pin weights dominate it. Kept for solve-to-solve comparison; surface weighted_lateness to planners instead."),
        ),
    ]
