# Generated by Django 5.1.6 on 2026-08-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0128_scheduleresult_weighted_lateness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationconfig',
            name='job_change_minutes',
            field=models.PositiveIntegerField(default=10, help_text="Setup minutes charged when a resource switches to a different work order on the SAME operation — keeps a job's parts batched together. Kept below operation-change setups by design: staying on the same operation matters more than staying on the same work order."),
        ),
    ]
