# Generated by Django 5.1.6 on 2026-08-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0129_optimizationconfig_job_change_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleresult',
            name='is_draft',
            field=models.BooleanField(db_index=True, default=False, help_text="A proposed 'what-if' schedule the planner reviews against the live one and then commits or discards. A draft never supersedes the active schedule until committed; committing promotes it to is_active."),
        ),
        migrations.AddIndex(
            model_name='scheduleresult',
            index=models.Index(fields=['is_draft'], name='Tracker_sch_is_draf_96b7f9_idx'),
        ),
    ]
