# Generated by Django 5.1.6 on 2026-08-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0130_scheduleresult_is_draft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipments',
            name='runs_unattended',
            field=models.BooleanField(default=True, help_text='Whether this machine can run lights-out (unattended) between staffed shifts. True (default): the Layer-1 scheduler runs it 24/7, gated only by downtime — a lot-operation can span nights/weekends. False: its work is confined to the shift calendar (an operator must be present to run it). Operator presence for the attended portions is handled by Layer-2 dispatch regardless of this flag.'),
        ),
    ]
