# Generated by Django 5.1.6 on 2026-08-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0131_equipments_runs_unattended'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationconfig',
            name='default_labor_model',
            field=models.CharField(choices=[('off', 'Off (no crew constraint)'), ('pool', 'Pool (cap at qualified crew)'), ('named', 'Named (assign a specific operator)')], default='pool', help_text="The labor model applied to steps that don't set their own (`Steps.labor_model`): POOL caps attended work at the qualified crew on shift; OFF drops the crew constraint; NAMED assigns a specific operator in the solve (reserve for specialist bottlenecks).", max_length=10),
        ),
        migrations.AddField(
            model_name='steps',
            name='labor_model',
            field=models.CharField(blank=True, choices=[('off', 'Off (no crew constraint)'), ('pool', 'Pool (cap at qualified crew)'), ('named', 'Named (assign a specific operator)')], help_text="How the scheduler constrains this step's operators. Null inherits the tenant's OptimizationConfig.default_labor_model. POOL caps concurrent attended work at the qualified crew; OFF drops the constraint; NAMED assigns a specific operator in the solve — reserve NAMED for specialist bottlenecks (e.g. a step only one certified operator can run).", max_length=10, null=True),
        ),
    ]
