# Generated by Django 5.1.6 on 2026-08-21 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0132_optimizationconfig_default_labor_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationconfig',
            name='match_operators',
            field=models.BooleanField(default=False, help_text='Two-phase solve: first schedule machines (fast, pooled labor), then re-solve assigning a SPECIFIC operator to every attended op, warm-started from the machine plan. Guarantees a real operator↔operation matching (scarce skills push work late, never silently uncovered) at the cost of a longer solve. Off = single fast machine solve.'),
        ),
    ]
