# Generated by Django 5.1.6 on 2026-08-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0133_optimizationconfig_match_operators'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationconfig',
            name='default_lockstep_batch',
            field=models.BooleanField(default=True, help_text="Default lot cohesion for work orders that don't set their own (`WorkOrder.lockstep_batch`): when on, a WO's cohort must move as one batch — the solver holds the whole WO (won't start the batch) while any member is split off in rework, so the lot always starts together and reconverges (see Parts.rejoined_at) before advancing. Off lets the cohort proceed while a straggler reworks independently."),
        ),
        migrations.AddField(
            model_name='parts',
            name='rejoined_at',
            field=models.DateTimeField(blank=True, help_text="UTC timestamp when a previously-split part rejoined its cohort's flow (via the rejoin_cohort service). split_from_cohort is cleared on rejoin but split_reason/split_at are RETAINED — the split→rejoin pair is an immutable genealogy record of the detour (rework/quarantine) the part took.", null=True),
        ),
        migrations.AddField(
            model_name='scheduleresult',
            name='held_lockstep_count',
            field=models.PositiveIntegerField(default=0, help_text='Lock-step work orders the solver held out of the plan this solve because a cohort member was split off in rework (the whole batch waits to start together). >0 means that many WOs are parked pending re-convergence — surface for the planner.'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='lockstep_batch',
            field=models.BooleanField(blank=True, help_text="Lot cohesion for this WO's cohort. When on, the whole batch must move and start together: the scheduler holds the entire WO out of the plan while any member is split off in rework, so the lot never starts without all its parts and reconverges (Parts.rejoined_at) first. Off lets the cohort proceed while a straggler reworks solo. Null inherits the tenant's OptimizationConfig.default_lockstep_batch.", null=True),
        ),
    ]
