# Generated by Django 5.1.6 on 2026-08-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0135_rename_lot_split_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='lot_split_at',
            field=models.DateTimeField(blank=True, help_text='UTC timestamp when the lot-split happened. Set together with split_from_lot.', null=True),
        ),
        migrations.AlterField(
            model_name='parts',
            name='lot_split_reason',
            field=models.CharField(blank=True, choices=[('quarantine', 'Quarantine'), ('rework', 'Rework'), ('scrap', 'Scrap')], help_text='Reason this part was split off its lot; blank when split_from_lot=False.', max_length=20),
        ),
        migrations.AlterField(
            model_name='parts',
            name='rejoined_at',
            field=models.DateTimeField(blank=True, help_text="UTC timestamp when a previously-split part rejoined its cohort's flow (via the rejoin_part_to_lot service). split_from_lot is cleared on rejoin but lot_split_reason/lot_split_at are RETAINED — the split→rejoin pair is an immutable genealogy record of the detour (rework/quarantine) the part took.", null=True),
        ),
        migrations.AlterField(
            model_name='parts',
            name='split_from_lot',
            field=models.BooleanField(default=False, help_text='True iff this part has been pulled off its WorkOrder cohort and now advances independently. Set via the split_part_from_lot service; cleared by rejoin_part_to_lot when the part re-converges with its siblings.'),
        ),
    ]
