# Generated by Django 5.1.6 on 2026-08-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0136_alter_parts_lot_split_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optimizationconfig',
            name='default_lockstep_batch',
            field=models.BooleanField(default=True, help_text="Default lot-cohesion intent for work orders that don't set their own (`WorkOrder.lockstep_batch`). NOTE: currently informational only — the solver always schedules co-located cohort parts as one cohesive lot and carves a rework straggler into its own lot so the cohort keeps progressing (it does NOT hold the WO); ON and OFF behave identically today. The OFF meaning (allow a large lot to break into transfer batches to pipeline) is reserved for the future transfer-batching work."),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='lockstep_batch',
            field=models.BooleanField(blank=True, help_text="Lot cohesion intent for this WO's cohort. NOTE: currently informational only — the scheduler always schedules co-located cohort parts as one cohesive lot (one occupancy, one start) and carves a rework straggler into its own lot so the cohort keeps progressing; ON and OFF behave identically today. The OFF meaning (let a large lot break into transfer batches to pipeline) is reserved for the future transfer-batching work. Null inherits OptimizationConfig.default_lockstep_batch.", null=True),
        ),
    ]
