# Generated by Django 5.1.6 on 2026-08-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0137_alter_optimizationconfig_default_lockstep_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleresult',
            name='machine_solve_ms',
            field=models.PositiveIntegerField(default=0, help_text='Wall-clock of the machine (Layer-1) phase (ms). Equals solve_time_ms for a single-phase solve (match_operators off).'),
        ),
        migrations.AddField(
            model_name='scheduleresult',
            name='operator_solve_ms',
            field=models.PositiveIntegerField(default=0, help_text='Wall-clock of the named-operator (Layer-2 in-solve) phase (ms); 0 when match_operators is off and operators come from Dispatch.'),
        ),
        migrations.AlterField(
            model_name='scheduleresult',
            name='solve_time_ms',
            field=models.PositiveIntegerField(default=0, help_text='Total CP-SAT wall-clock across all phases (ms).'),
        ),
    ]
