# Generated by Django 5.1.6 on 2026-08-24 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0138_scheduleresult_machine_solve_ms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationconfig',
            name='solver_time_limit_seconds',
            field=models.PositiveIntegerField(default=180, help_text="CP-SAT wall-clock cap per solve (seconds); best-so-far is returned when it elapses. With match_operators on it's split across the machine (~40%) and operator (~60%) phases.", validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
