# Generated by Django 5.1.6 on 2026-08-25 15:11

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0139_optimizationconfig_solver_time_limit_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipments',
            name='operating_shifts',
            field=models.ManyToManyField(blank=True, help_text='Optional per-machine operating calendar: the shifts this machine runs. Empty (default) inherits the tenant-wide shift calendar. Lets a bottleneck run more shifts than the rest of the floor. Applies to attended (runs_unattended=False) machines; lights-out machines run 24/7.', related_name='equipment', to='Tracker.shift'),
        ),
        migrations.CreateModel(
            name='PlantCalendarException',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('HOLIDAY', 'Holiday'), ('SHUTDOWN', 'Plant Shutdown'), ('INVENTORY', 'Inventory / Stock-take'), ('OTHER', 'Other')], default='HOLIDAY', max_length=12)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.plantcalendarexception')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant')),
            ],
            options={
                'verbose_name': 'Plant Calendar Exception',
                'verbose_name_plural': 'Plant Calendar Exceptions',
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['tenant', 'start_time'], name='Tracker_pla_tenant__c66aed_idx')],
            },
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
    ]
