# Generated by Django 5.1.6 on 2026-08-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0140_equipments_operating_shifts_plantcalendarexception'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationconfig',
            name='default_move_minutes',
            field=models.PositiveIntegerField(default=0, help_text="Move/queue time between consecutive operations of a route — the next operation can't start until this many minutes after the prior one finishes (transport + queue). Applied to every intra-route hand-off; 0 = parts flow with no transfer delay. (Distinct from staging_buffer, which is the cross-work-order assembly-convergence gap.)"),
        ),
    ]
