# Generated by Django 5.1.6 on 2026-08-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0141_optimizationconfig_default_move_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='material_shortage',
            field=models.BooleanField(default=False, help_text='A purchased component this operation consumes is short on hand with no known incoming receipt date — the op is scheduled but flagged for the planner (material-constrained scheduling, buy-side).'),
        ),
    ]
