# Generated by Django 5.1.6 on 2026-08-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0142_scheduledtask_material_shortage'),
    ]

    operations = [
        migrations.AddField(
            model_name='processes',
            name='default_scrap_rate',
            field=models.DecimalField(decimal_places=4, default=0, help_text="Default expected scrap fraction (0–1) applied to steps of this process that don't set their own `Steps.scrap_rate`. Used to gross up the started quantity so a work order still finishes the requested number of good parts (release-11-to-ship-10).", max_digits=5),
        ),
        migrations.AddField(
            model_name='steps',
            name='scrap_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="Expected fraction of parts scrapped AT this step (0–1). Null inherits the process default. Today this is an authored estimate; the resolution chain (`services.mes.yield_planning`) is built so a statistically-observed rate from StepExecution history can later take precedence when there's enough data to be confident.", max_digits=5, null=True),
        ),
    ]
