# Generated by Django 5.1.6 on 2026-08-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0143_processes_default_scrap_rate_steps_scrap_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='kind',
            field=models.CharField(choices=[('FIXTURE', 'Fixture'), ('TOOL', 'Cutting tool'), ('DIE', 'Die / mold'), ('PROGRAM', 'NC program'), ('OTHER', 'Other')], default='FIXTURE', help_text='What kind of shared resource this is (categorisation only — the scheduling constraint is identical for all kinds).', max_length=10),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='How many of this resource exist (concurrency limit).'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='steps',
            field=models.ManyToManyField(blank=True, help_text='Steps that require this resource.', related_name='fixtures', to='Tracker.steps'),
        ),
    ]
