# Generated by Django 5.1.6 on 2026-08-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0144_fixture_kind_alter_fixture_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='late_cause',
            field=models.CharField(blank=True, default='', help_text='Heuristic reason this task finishes late — the binding constraint (material / uncovered operator / machine contention / late release / tight lead time). Empty when the task is on time. Set post-solve by services.scheduling.late_cause.', max_length=200),
        ),
    ]
