# Generated by Django 5.1.6 on 2026-08-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0145_scheduledtask_late_cause'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='in_progress',
            field=models.BooleanField(default=False, help_text="This operation was physically running at solve time (open StepExecution) — the solver pinned it at 'now' with only its remaining duration. Distinguishes a running lock from a planner pin on the Gantt."),
        ),
    ]
