# Generated by Django 5.1.6 on 2026-08-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0146_scheduledtask_in_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='material_detail',
            field=models.CharField(blank=True, default='', help_text='Human summary of the material situation for this op — short component(s), shortfall, and any incoming receipt date. Empty when material is on hand. Set post-solve alongside material_shortage.', max_length=300),
        ),
    ]
