# Generated by Django 5.1.6 on 2026-08-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0147_scheduledtask_material_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationconfig',
            name='auto_resolve',
            field=models.CharField(choices=[('off', 'Off (flag stale only; planner re-solves by hand)'), ('live', 'Live (auto re-solve and supersede the schedule)')], default='off', help_text='Automatic rescheduling when the live plan drifts stale. OFF (default): the plan is only flagged for a planner to re-solve by hand — nothing on the floor changes automatically. LIVE: a background beat re-solves and supersedes the live schedule; the frozen zone + planner pins protect committed near-term work, so only the drifted tail moves.', max_length=10),
        ),
        migrations.AddField(
            model_name='optimizationconfig',
            name='auto_resolve_min_interval_minutes',
            field=models.PositiveIntegerField(default=30, help_text="Anti-churn floor for LIVE auto-resolve: don't re-solve a schedule sooner than this many minutes after its last solve, so a burst of changes batches into one re-solve."),
        ),
    ]
