# Generated by Django 5.1.6 on 2026-08-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0148_optimizationconfig_auto_resolve_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='actual_end',
            field=models.DateTimeField(blank=True, help_text='Real completion, stamped from the StepExecution exit. Null while the op is unstarted or still running.', null=True),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='actual_start',
            field=models.DateTimeField(blank=True, help_text="Real start of this operation, stamped from the part/core's StepExecution entry (capture-only; for planned-vs-actual). Null until the unit reaches this step.", null=True),
        ),
    ]
