# Generated by Django 5.1.6 on 2026-08-26 13:42

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0149_scheduledtask_actual_end_scheduledtask_actual_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaborCalendarBlock',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('kind', models.CharField(choices=[('PTO', 'PTO / vacation'), ('SICK', 'Sick'), ('TRAINING', 'Training'), ('MEETING', 'Meeting'), ('BREAK', 'Break'), ('OTHER', 'Other')], default='OTHER', max_length=12)),
                ('recurrence', models.CharField(choices=[('ONCE', 'One-off (dated)'), ('WEEKLY', 'Weekly (recurring)')], default='ONCE', max_length=8)),
                ('start_time', models.DateTimeField(blank=True, help_text='One-off start (recurrence=ONCE).', null=True)),
                ('end_time', models.DateTimeField(blank=True, help_text='One-off end (recurrence=ONCE).', null=True)),
                ('days_of_week', models.CharField(blank=True, default='', help_text="Recurring days as comma-separated numbers (0=Monday..6=Sunday), e.g. '0,2,4' (recurrence=WEEKLY).", max_length=20)),
                ('window_start', models.TimeField(blank=True, help_text='Recurring start time-of-day (recurrence=WEEKLY).', null=True)),
                ('window_end', models.TimeField(blank=True, help_text='Recurring end time-of-day (recurrence=WEEKLY).', null=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.laborcalendarblock')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant')),
                ('user', models.ForeignKey(blank=True, help_text='The operator this block applies to. Null = the whole company (every operator), e.g. an all-hands meeting.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Labor Calendar Block',
                'verbose_name_plural': 'Labor Calendar Blocks',
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['tenant', 'is_active'], name='Tracker_lab_tenant__f9520a_idx'), models.Index(fields=['user', 'start_time'], name='Tracker_lab_user_id_149ff9_idx')],
            },
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
    ]
