# Generated by Django 5.1.6 on 2026-08-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0150_laborcalendarblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantcalendarexception',
            name='recurrence',
            field=models.CharField(choices=[('ONCE', 'One-off (dated)'), ('YEARLY', 'Repeats yearly')], default='ONCE', help_text="YEARLY repeats the closure's month/day span every year (fixed-date holidays like Christmas); the stored year is just the first occurrence.", max_length=8),
        ),
    ]
