# Generated by Django 5.1.6 on 2026-08-26 14:42

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0151_plantcalendarexception_recurrence'),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeWindow',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('recurrence', models.CharField(choices=[('ONCE', 'One-off (dated)'), ('WEEKLY', 'Weekly (recurring)')], default='ONCE', max_length=8)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('days_of_week', models.CharField(blank=True, default='', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.overtimewindow')),
                ('shift', models.ForeignKey(help_text='The shift being run as overtime — supplies the hours and the crew (operators rostered to it).', on_delete=django.db.models.deletion.CASCADE, related_name='overtime_windows', to='Tracker.shift')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant')),
            ],
            options={
                'verbose_name': 'Overtime Window',
                'verbose_name_plural': 'Overtime Windows',
                'ordering': ['start_date'],
                'indexes': [models.Index(fields=['tenant', 'is_active'], name='Tracker_ove_tenant__41de14_idx')],
            },
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
    ]
