# Generated by Django 5.1.6 on 2026-08-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0152_overtimewindow'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='is_makeup',
            field=models.BooleanField(default=False, help_text='This part was created by make-up planning to replace scrapped units and keep the work order on track for its ordered good quantity.'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='target_good_quantity',
            field=models.IntegerField(blank=True, help_text='The number of GOOD parts this work order owes (the ordered quantity, before yield gross-up). `quantity` is what was started to hit it. Make-up planning tops parts back up to this when actual scrap outruns the expected gross-up. Null on legacy WOs (falls back to `quantity`).', null=True),
        ),
    ]
