# Generated by Django 5.1.6 on 2026-08-26 16:24

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0153_parts_is_makeup_workorder_target_good_quantity'),
    ]

    operations = [
        # ---- BOM line: parts (MAKE, component_type) XOR raw materials (BUY, material) ----
        migrations.AlterField(
            model_name='bomline',
            name='component_type',
            field=models.ForeignKey(blank=True, help_text='In-house component (source=MAKE). Mutually exclusive with `material`.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_in_boms', to='Tracker.parttypes'),
        ),
        migrations.AlterField(
            model_name='materiallot',
            name='material_description',
            field=models.CharField(blank=True, help_text='Free-text description for ad-hoc raw materials not in the Material list', max_length=200),
        ),
        # ---- Material: raw materials / consumables (never made in-house) ----
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('part_number', models.CharField(blank=True, help_text='Supplier or internal catalog number/SKU.', max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('unit_of_measure', models.CharField(default='EA', max_length=20)),
                ('purchase_lead_time_days', models.PositiveIntegerField(blank=True, help_text='Days to source this item from a supplier — drives the order-by date in the sourcing report (order-by = need-by − lead time).', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('preferred_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_materials', to='Tracker.companies')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.material')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
                'ordering': ['name'],
            },
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        # ---- PartTypes: make/buy sourcing attributes (a part can be either or both) ----
        migrations.AddField(
            model_name='parttypes',
            name='can_make',
            field=models.BooleanField(default=True, help_text='This part can be produced in-house (has a production process; shortages spawn child work orders).'),
        ),
        migrations.AddField(
            model_name='parttypes',
            name='can_buy',
            field=models.BooleanField(default=False, help_text='This part can be purchased from a supplier. May be True alongside can_make for dual-sourced parts.'),
        ),
        migrations.AddField(
            model_name='parttypes',
            name='purchase_lead_time_days',
            field=models.PositiveIntegerField(blank=True, help_text='Days to source this part from a supplier when bought — drives the order-by date in the sourcing report (order-by = need-by − lead time).', null=True),
        ),
        migrations.AddField(
            model_name='parttypes',
            name='preferred_supplier',
            field=models.ForeignKey(blank=True, help_text='Default supplier when this part is purchased.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_part_types', to='Tracker.companies'),
        ),
        # ---- BOM line + MaterialLot links to the Material model ----
        migrations.AddField(
            model_name='bomline',
            name='material',
            field=models.ForeignKey(blank=True, help_text='Purchased component (source=BUY). Mutually exclusive with `component_type`.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_in_boms', to='Tracker.material'),
        ),
        migrations.AddField(
            model_name='materiallot',
            name='material',
            field=models.ForeignKey(blank=True, help_text='The raw material / consumable this lot is stock of (mutually exclusive with material_type, which is for buyable parts).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='Tracker.material'),
        ),
        # ---- XOR constraints ----
        migrations.AddConstraint(
            model_name='bomline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('component_type__isnull', False), ('material__isnull', True)), models.Q(('component_type__isnull', True), ('material__isnull', False)), _connector='OR'), name='bomline_exactly_one_component'),
        ),
        migrations.AddConstraint(
            model_name='materiallot',
            constraint=models.CheckConstraint(condition=models.Q(('material__isnull', False), ('material_type__isnull', False), _negated=True), name='materiallot_part_xor_material'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['tenant', 'is_active'], name='Tracker_mat_tenant__1fae44_idx'),
        ),
    ]
