# Generated by Django 5.1.6 on 2026-08-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0154_alter_bomline_component_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='lead_time_days',
            field=models.PositiveIntegerField(blank=True, help_text="Days to acquire or produce this tooling if it's short — drives the order-by date in the sourcing report.", null=True),
        ),
    ]
