# Generated by Django 5.1.6 on 2026-08-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0155_fixture_lead_time_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='default_outside_process_turnaround_days',
            field=models.PositiveIntegerField(blank=True, help_text="Default subcontract turnaround (calendar days) when this company is a step's outside-process vendor and the step doesn't specify its own lead time. Used by the scheduler to reserve elapsed vendor time for outside-process operations.", null=True),
        ),
        migrations.AddField(
            model_name='optimizationconfig',
            name='default_outside_process_turnaround_days',
            field=models.PositiveIntegerField(default=7, help_text='Fallback outside-process turnaround (calendar days) when neither the step nor the vendor specifies one — so an OSP step always reserves elapsed time.'),
        ),
        migrations.AddField(
            model_name='steps',
            name='outside_process_lead_days',
            field=models.PositiveIntegerField(blank=True, help_text="Planned vendor turnaround for this outside-process step, in CALENDAR days (ship-out → return). The scheduler reserves this as an elapsed, no-capacity interval that gates downstream ops. Overrides the supplier's default; if unset, the supplier default then the tenant OptimizationConfig default is used. Once a part is actually shipped, its OutsideProcessShipment.promised_return overrides.", null=True),
        ),
    ]
