# Generated by Django 5.1.6 on 2026-08-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0156_companies_default_outside_process_turnaround_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipments',
            name='batch_capacity',
            field=models.PositiveIntegerField(default=1, help_text='How many parts this resource processes at once. 1 (default) = a normal one-at-a-time machine (no-overlap). >1 = a batch/process resource (furnace, plating tank, wash line): the scheduler lets up to this many parts occupy it concurrently, and — for steps with a batch recipe — groups compatible parts into shared load-fire-unload cycles (min/max load).'),
        ),
    ]
