# Generated by Django 5.1.6 on 2026-08-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0157_equipments_batch_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipments',
            name='batch_mode',
            field=models.CharField(choices=[('concurrent', 'Concurrent (parallel jobs)'), ('cycle', 'Cycle (shared load, fixed cycle time)')], default='concurrent', help_text='How a batch resource (batch_capacity>1) behaves. CONCURRENT: up to batch_capacity independent jobs run at once (a bank of wash tanks / parallel stations). CYCLE: a furnace/oven — ONE load at a time of up to batch_capacity parts, and the cycle time is fixed regardless of how full the load is (a job of N parts takes ceil(N / batch_capacity) loads). Ignored when capacity = 1.', max_length=12),
        ),
        migrations.AlterField(
            model_name='equipments',
            name='batch_capacity',
            field=models.PositiveIntegerField(default=1, help_text='How many jobs/parts this resource handles at once. 1 (default) = a normal one-at-a-time machine. >1 = a batch/process resource — see `batch_mode`.'),
        ),
    ]
