# Generated by Django 5.1.6 on 2026-08-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0158_equipments_batch_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='cure_window_violation',
            field=models.BooleanField(default=False, help_text="This op starts later than a max-time-between-operations limit on its incoming edge allows (e.g. a cure/coat/passivation window) — capacity couldn't meet the window, so it's scheduled but flagged: the part will scrap or need rework unless expedited. Set post-solve (soft constraint)."),
        ),
        migrations.AddField(
            model_name='stepedge',
            name='max_minutes',
            field=models.PositiveIntegerField(blank=True, help_text="Scheduling: MAX elapsed minutes allowed between from_step finishing and to_step starting — a process time limit (e.g. 'coat within 4h of clean', passivation dwell, adhesive pot-life). The scheduler treats it as a soft upper bound: it schedules to meet it and FLAGS the op when capacity can't, rather than blocking the whole solve. Null = no limit (the default).", null=True),
        ),
    ]
