# Generated by Django 5.1.6 on 2026-08-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0159_scheduledtask_cure_window_violation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleresult',
            name='relative_gap',
            field=models.FloatField(blank=True, help_text='CP-SAT proven optimality gap: (objective − best_bound) / |objective|. 0.0 = proven OPTIMAL; a small positive value on a FEASIBLE result means the solver proved the schedule is within that fraction of the best possible objective before the time limit. Null when nothing was solved.', null=True),
        ),
    ]
