# Generated by Django 5.1.6 on 2026-09-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0160_scheduleresult_relative_gap'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationconfig',
            name='default_machine_unattended',
            field=models.BooleanField(default=False, help_text="This facility's operating model: whether machines run lights-out (unattended, 24/7) BY DEFAULT. False (default): machines only run on shift unless a specific machine is marked lights-out — the safe choice, since assuming capacity a shop can't staff produces an unexecutable plan. True: an automated shop where machines run overnight by default. Each machine's `runs_unattended` overrides this; a machine left unset inherits it."),
        ),
        migrations.AlterField(
            model_name='equipments',
            name='runs_unattended',
            field=models.BooleanField(blank=True, default=None, help_text='Whether this machine runs lights-out (unattended) between staffed shifts. NULL (default): inherit the facility default (OptimizationConfig.default_machine_unattended). True: the Layer-1 scheduler runs it 24/7, gated only by downtime — a lot-operation can span nights/weekends. False: its work is confined to the shift calendar (an operator must be present). Operator presence for the attended portions is handled by Layer-2 dispatch regardless of this flag.', null=True),
        ),
    ]
