# Generated by Django 5.1.6 on 2026-09-02 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0161_optimizationconfig_default_machine_unattended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationconfig',
            name='release_mode',
            field=models.CharField(choices=[('auto', 'Date-driven (no release step)'), ('manual', 'Planner releases work')], default='auto', help_text='Who decides what the scheduler may plan. AUTO (default): every open work order is schedulable as soon as its dates allow — the plan is date-driven, which is right for a shop where the planner and the scheduler are the same person. MANUAL: a work order is invisible to the solver until a planner RELEASES it, so the board only ever shows authorized work. Manual adds a gate, not a hierarchy — there are no separate planned-order objects to convert; releasing stamps `released_at` on the work order itself.', max_length=6),
        ),
        migrations.AddField(
            model_name='workorder',
            name='release_override_reason',
            field=models.TextField(blank=True, default='', help_text='Recorded justification when a work order was released despite a failing readiness check. Blank when it released clean. The gate is advisory by design — a planner who knows the shortage is covered must be able to proceed, but the override is on the record.'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='released_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When a planner authorized this work order for scheduling. Null = not released. Only gates the solver under release_mode=MANUAL; under AUTO it is recorded when set but never filters.', null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='released_by',
            field=models.ForeignKey(blank=True, help_text='Who released it. Kept for the audit trail even after un-release.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
