# Generated by Django 5.1.6 on 2026-09-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0162_optimizationconfig_release_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationconfig',
            name='horizon_days',
            field=models.PositiveIntegerField(default=30, help_text="How far ahead CP-SAT plans in DETAIL. Work releasing past this window is out of scope for the solve — its capacity is the rough-cut (RCCP) layer's business until the window rolls far enough to reach it. Longer windows plan more but solve slower, and the far end is guesswork anyway: a month out, the routing and the crew are known; a year out they are not."),
        ),
    ]
