# Generated by Django 5.1.6 on 2026-09-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0163_optimizationconfig_horizon_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleresult',
            name='infeasible_reason',
            field=models.TextField(blank=True, default='', help_text="Why the solve produced no plan, in the planner's terms (usually 'more work than the window holds', naming the short resource). CP-SAT reports INFEASIBLE with no explanation, and an empty board with no reason is the worst result the scheduler can give. Blank on any solve that produced a plan."),
        ),
    ]
