# Generated by Django 5.1.6 on 2026-09-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0164_scheduleresult_infeasible_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationconfig',
            name='release_policy',
            field=models.CharField(choices=[('wlc', 'Balance every resource'), ('constraint', 'Pace to the bottleneck')], default='wlc', help_text='Which resources gate release. WORKLOAD balances across every resource — the right default, and what the research favours for shops without a dominant bottleneck. CONSTRAINT paces release to the work centres flagged `is_constraint` and ignores the rest, for a shop whose output is genuinely governed by one resource.', max_length=12),
        ),
        migrations.AddField(
            model_name='optimizationconfig',
            name='workload_norm_pct',
            field=models.PositiveIntegerField(default=100, help_text="Release ceiling per resource, as a percentage of that resource's capacity over the planning window. Orders are released from the pool while no resource they touch would exceed its ceiling. Below 100 keeps deliberate slack for expedites and variability; above 100 admits a queue on purpose. A resource with NO committed work is always fed regardless — a ceiling is a cap on commitment, never a reason to let a resource stand idle."),
        ),
        migrations.AddField(
            model_name='workcenter',
            name='is_constraint',
            field=models.BooleanField(default=False, help_text="This work centre governs the plant's output — the bottleneck. Only consulted when OptimizationConfig.release_policy is CONSTRAINT, where order release is paced to these centres and the rest are ignored. Declared by a planner rather than inferred: a resource can look loaded for a month without being the real constraint, and acting on a mis-identified one starves the shop."),
        ),
    ]
