# Generated by Django 5.1.6 on 2026-09-03 14:21

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0165_optimizationconfig_release_policy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialStaging',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('staged_at', models.DateTimeField(blank=True, help_text='When the material was put at the bench. Null = not staged.', null=True)),
                ('note', models.TextField(blank=True, default='', help_text='Anything the next person needs: part-picked, substituted lot, left on the blue cart.')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.materialstaging')),
                ('staged_by', models.ForeignKey(blank=True, help_text="Who staged it — the shift-handover question is 'who has this'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_stagings', to=settings.AUTH_USER_MODEL)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_stagings', to='Tracker.steps')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_stagings', to='Tracker.workorder')),
            ],
            options={
                'verbose_name': 'Material Staging',
                'verbose_name_plural': 'Material Stagings',
                'ordering': ['-staged_at'],
                'indexes': [models.Index(fields=['tenant', 'staged_at'], name='Tracker_mat_tenant__e95f12_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'work_order', 'step'), name='unique_material_staging_per_job_step')],
            },
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
    ]
