# Generated by Django 5.1.6 on 2026-09-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0166_materialstaging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steptiming',
            name='attention_type',
            field=models.CharField(choices=[('full', 'Full attention (operator tied to the machine)'), ('load_unload', 'Load/unload only (machine runs unattended between)'), ('unattended', 'Unattended (robot/cobot fed — setup only)')], default='full', help_text='Whether the operator is tied to the machine (full) or only loads/unloads (enables multi-machine tending in Layer 2).', max_length=12),
        ),
    ]
