# Generated by Django 5.1.6 on 2026-09-08 17:35

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0167_attention_type_unattended'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialStagingLine',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('qty_required', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('qty_picked', models.DecimalField(decimal_places=4, default=0, help_text='What was physically pulled. Reserves stock until issued.', max_digits=12)),
                ('picked_lots', models.JSONField(blank=True, default=list)),
                ('issued_at', models.DateTimeField(blank=True, help_text='When consumption drew this line down. Null = picked but not yet consumed, i.e. still reserved against on-hand.', null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staging_lines', to='Tracker.material')),
                ('picked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staging_lines_picked', to=settings.AUTH_USER_MODEL)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.materialstagingline')),
                ('staging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='Tracker.materialstaging')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant')),
            ],
            options={
                'verbose_name': 'Material Staging Line',
                'verbose_name_plural': 'Material Staging Lines',
                'ordering': ['material__name'],
                'indexes': [models.Index(fields=['tenant', 'issued_at'], name='Tracker_mat_tenant__544f4e_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'staging', 'material'), name='unique_staging_line_per_material')],
            },
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
    ]
