# Generated by Django 5.1.6 on 2026-09-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0168_material_staging_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationconfig',
            name='active_run_kind',
            field=models.CharField(blank=True, default='', help_text="What's running: 'solve', 'draft' or 'dispatch'.", max_length=16),
        ),
        migrations.AddField(
            model_name='optimizationconfig',
            name='active_run_started_at',
            field=models.DateTimeField(blank=True, help_text='When it was QUEUED (not when a worker picked it up). Combined with the time limit this bounds the wait — CP-SAT runs to a cap, so the end is known rather than guessed. Also how a dead run is detected: past the cap plus a grace period with no result means the worker died, and the board must stop claiming a solve is running.', null=True),
        ),
        migrations.AddField(
            model_name='optimizationconfig',
            name='active_run_task_id',
            field=models.CharField(blank=True, default='', help_text='Celery id of the solve/dispatch currently in flight, or blank.', max_length=64),
        ),
    ]
