# Generated by Django 5.1.6 on 2026-09-08 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0169_active_run_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='safety_stock',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Buffer held back from planning. Coverage nets against on-hand MINUS this, so the material lane warns while there is still stock to react with instead of at the last unit. Does not block issuing — a picker can always draw the physical stock.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='materiallot',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_lots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='materiallot',
            name='received_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materiallot',
            name='status',
            field=models.CharField(choices=[('ON_ORDER', 'On Order'), ('RECEIVED', 'Received'), ('AWAITING_INSPECTION', 'Awaiting Inspection'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('IN_USE', 'In Use'), ('CONSUMED', 'Consumed'), ('SCRAPPED', 'Scrapped'), ('QUARANTINE', 'Quarantine')], default='RECEIVED', max_length=20),
        ),
    ]
