# Generated by Django 5.1.6 on 2026-09-08 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0170_on_order_lots_and_safety_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomline',
            name='component_type',
            field=models.ForeignKey(blank=True, help_text="A part (not a raw material). With source=MAKE it spawns a child work order; with source=BUY it is purchased instead, which requires the part type's can_buy flag. Mutually exclusive with `material`.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_in_boms', to='Tracker.parttypes'),
        ),
        migrations.AlterField(
            model_name='bomline',
            name='material',
            field=models.ForeignKey(blank=True, help_text='Purchased raw material / consumable (source=BUY) — something never produced in-house. Mutually exclusive with `component_type`.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_in_boms', to='Tracker.material'),
        ),
    ]
