# Generated by Django 5.1.6 on 2026-09-09 20:36

from django.db import migrations, models


def _seed_critical_from_constraint(apps, schema_editor):
    """A declared bottleneck is by definition worth watching, so seed the new flag
    from it rather than making every existing planner re-declare the one centre they
    already told us about. Seed only — the two fields are independent afterwards."""
    WorkCenter = apps.get_model('Tracker', 'WorkCenter')
    # `_base_manager` because a historical model has no `SecureManager`, and because a
    # migration is deliberately cross-tenant: every tenant's bottleneck gets seeded.
    WorkCenter._base_manager.filter(is_constraint=True).update(is_critical=True)


def _noop(apps, schema_editor):
    """Reverse is a no-op: the column is dropped by the AddField reversal anyway."""


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0171_bomline_buy_parttype_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcenter',
            name='is_critical',
            field=models.BooleanField(default=False, help_text='Watch this centre on the rough-cut capacity plan. RCCP is defined as capacity planning over CRITICAL resources only — a plant with forty work centres has maybe six whose load anyone can act on, and showing all forty buries them. Presentation only: the flag filters the heatmap, it never changes how load or capacity is computed, and it is independent of `is_constraint`, which gates order release.'),
        ),
        migrations.RunPython(_seed_critical_from_constraint, _noop),
    ]
