# Generated by Django 5.1.6 on 2026-09-15 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0174_docchunk_drop_duplicate_doc_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='substepcompletion',
            options={'ordering': ['-completed_at'], 'permissions': [('void_substepcompletion', 'Can void an erroneous substep completion')]},
        ),
    ]
