# Generated by Django 5.1.6 on 2026-09-21 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0175_alter_substepcompletion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialstagingline',
            options={'ordering': ['material__name', 'material_type__name'], 'verbose_name': 'Material Staging Line', 'verbose_name_plural': 'Material Staging Lines'},
        ),
        migrations.RemoveConstraint(
            model_name='materialstagingline',
            name='unique_staging_line_per_material',
        ),
        migrations.AddField(
            model_name='materialstagingline',
            name='material_type',
            field=models.ForeignKey(blank=True, help_text='Buyable part being kitted (mutually exclusive with material).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staging_lines', to='Tracker.parttypes'),
        ),
        migrations.AlterField(
            model_name='materialstagingline',
            name='material',
            field=models.ForeignKey(blank=True, help_text='Raw material / consumable being kitted (mutually exclusive with material_type, which is for buyable parts).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staging_lines', to='Tracker.material'),
        ),
        migrations.AddConstraint(
            model_name='materialstagingline',
            constraint=models.UniqueConstraint(condition=models.Q(('material__isnull', False)), fields=('tenant', 'staging', 'material'), name='unique_staging_line_per_material'),
        ),
        migrations.AddConstraint(
            model_name='materialstagingline',
            constraint=models.UniqueConstraint(condition=models.Q(('material_type__isnull', False)), fields=('tenant', 'staging', 'material_type'), name='unique_staging_line_per_part'),
        ),
        migrations.AddConstraint(
            model_name='materialstagingline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('material__isnull', False), ('material_type__isnull', True)), models.Q(('material__isnull', True), ('material_type__isnull', False)), _connector='OR'), name='stagingline_material_xor_part'),
        ),
    ]
