# Generated by Django 5.1.6 on 2026-09-21 15:35

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0176_stagingline_buyable_parts'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('line_number', models.PositiveIntegerField(help_text="Position on the order, as the customer's paperwork numbers it.")),
                ('quantity', models.PositiveIntegerField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='Tracker.orders')),
                ('part_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='Tracker.parttypes')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.orderline')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant')),
            ],
            options={
                'verbose_name': 'Order Line',
                'verbose_name_plural': 'Order Lines',
                'ordering': ['order', 'line_number'],
            },
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='workorder',
            name='order_line',
            field=models.ForeignKey(blank=True, help_text='The demand line this job satisfies. Narrower than `related_order`: an order says which customer, a line says which of their requests and how many of it are still unplanned.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='Tracker.orderline'),
        ),
        migrations.AddIndex(
            model_name='orderline',
            index=models.Index(fields=['tenant', 'status', 'due_date'], name='Tracker_ord_tenant__a536f4_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.UniqueConstraint(fields=('tenant', 'order', 'line_number'), name='unique_order_line_number'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='orderline_quantity_positive'),
        ),
    ]
