# Generated by Django 5.1.6 on 2026-09-21 17:34

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0178_backfill_order_lines'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEdit',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('kind', models.CharField(help_text="What the planner did — move, batch-move, reassign. Shown in the undo affordance so it reads as 'Undo move' rather than 'Undo'.", max_length=32)),
                ('payload', models.JSONField(default=list)),
                ('undone_at', models.DateTimeField(blank=True, help_text='Set when this edit is reversed. An undone edit stays on the record rather than being deleted — what someone tried is part of the history — and cannot be undone a second time.', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_edits', to=settings.AUTH_USER_MODEL)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.scheduleedit')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='Tracker.scheduleresult')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant')),
            ],
            options={
                'verbose_name': 'Schedule Edit',
                'verbose_name_plural': 'Schedule Edits',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'schedule', '-created_at'], name='Tracker_sch_tenant__f61be7_idx')],
            },
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
    ]
