# Generated by Django 5.1.6 on 2026-09-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0179_schedule_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='default_timezone',
            field=models.CharField(default='UTC', help_text="The shop floor's clock (IANA, e.g. 'America/New_York'). Shift, break and overtime windows are wall-clock time — 'we start at six' means six on the wall — so they are resolved against THIS zone, not the server's. Per tenant because a multi-tenant product has shops in different zones and one settings.TIME_ZONE can only suit one.", max_length=50),
        ),
    ]
