# Generated by Django 5.1.6 on 2026-09-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0180_drop_duplicate_plant_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='core',
            name='fulfilment_mode',
            field=models.CharField(choices=[('EXCHANGE', 'Exchange — customer gets a unit from stock'), ('REPAIR_RETURN', 'Repair & return — this unit goes back to them')], default='EXCHANGE', help_text="Whether this exact unit goes back to the customer, or they receive one from stock. Not the same question as source_type, which records where the core came from. Drives three things: whether the rebuilt unit must keep this core's identity, whether a scope change needs the customer's authorisation before work proceeds, and whether components harvested from OTHER cores may be built into it.", max_length=20),
        ),
    ]
