# Generated by Django 5.1.6 on 2026-09-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0181_core_fulfilment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='default_core_fulfilment_mode',
            field=models.CharField(blank=True, choices=[('EXCHANGE', 'Exchange — customer gets a unit from stock'), ('REPAIR_RETURN', 'Repair & return — this unit goes back to them')], help_text="This customer's standing arrangement for cores they send in: do they get their own unit back, or one from stock? An exchange programme is a contract, not a per-unit decision, so receiving inherits it rather than asking a clerk to guess. Blank means nobody has recorded an arrangement — distinct from 'exchange', because the receipt screen can then say so and prompt for it instead of implying a decision that was never made.", max_length=20, null=True),
        ),
    ]
