# Generated by Django 5.1.6 on 2026-09-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0182_company_default_fulfilment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core',
            name='core_number',
            field=models.CharField(blank=True, help_text="Our handle for this unit (unique per tenant). Auto-generated as CORE-YYYY-#### when left blank — every other business identifier here is (orders, shipments, approvals, quality reports, dispositions, qualifications), and cores arrive in batches where hand-typing forty unique numbers is both slow and the obvious place for a duplicate to creep in. Still writable, for a shop with its own tagging scheme. The CUSTOMER's references live elsewhere: `source_reference` for an RMA or PO, `serial_number` for the OEM serial.", max_length=100),
        ),
    ]
