# Generated by Django 5.1.6 on 2026-09-21 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0183_core_number_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='reserved_for_core',
            field=models.ForeignKey(blank=True, help_text="Set when this part was harvested from a core whose own unit goes back to the customer. The part is that customer's property, not stock: it may only be consumed by work on the core it came from.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reserved_parts', to='Tracker.core'),
        ),
    ]
