# Generated by Django 5.1.6 on 2026-09-23 14:40

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0186_alter_repaircode_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='RebuildSlotOverride',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('position', models.CharField(blank=True, help_text='Which slot on that line — blank for an unpositioned one. Blank rather than null on purpose: a unique constraint over a nullable column stops preventing anything in Postgres.', max_length=50)),
                ('resolution', models.CharField(choices=[('REUSE', 'Reuse as-is — the recovered component is serviceable'), ('RECONDITION', 'Recondition — work it before it goes back'), ('REPLACE_POOL', 'Replace from recovered stock'), ('REPLACE_BUY', 'Replace with a purchase')], help_text='What the planner decided instead.', max_length=20)),
                ('reason', models.TextField(help_text='Why the proposal was wrong. Required — an override without one cannot be told from a misclick later, and this is the row that answers why a unit was built the way it was.')),
                ('bom_line', models.ForeignKey(help_text='The assembly BOM line the slot came from.', on_delete=django.db.models.deletion.CASCADE, related_name='rebuild_slot_overrides', to='Tracker.bomline')),
                ('core', models.ForeignKey(help_text='The core whose rebuild plan this overrides.', on_delete=django.db.models.deletion.CASCADE, related_name='slot_overrides', to='Tracker.core')),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rebuild_slot_overrides', to=settings.AUTH_USER_MODEL)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.rebuildslotoverride')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant')),
            ],
            options={
                'verbose_name': 'Rebuild Slot Override',
                'verbose_name_plural': 'Rebuild Slot Overrides',
                'ordering': ['core', 'bom_line', 'position'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'core', 'bom_line', 'position'), name='rebuildslotoverride_one_per_slot')],
            },
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
    ]
