# Generated by Django 5.1.6 on 2026-09-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0187_rebuildslotoverride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('IN_DISASSEMBLY', 'In Disassembly'), ('DISASSEMBLED', 'Disassembled'), ('IN_REBUILD', 'In Rebuild'), ('REBUILT', 'Rebuilt — ready to return'), ('HARVESTED', 'Harvested to inventory'), ('SCRAPPED', 'Scrapped')], default='RECEIVED', max_length=20),
        ),
    ]
