# Generated by Django 5.1.6 on 2026-09-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0188_alter_core_status'),
    ]

    def _clear_default_true(apps, schema_editor):
        """Existing `allow_harvested=True` rows are the DEFAULT, not a decision.

        The field used to default True on every line, including raw-material lines
        where recovery is impossible — so leaving them True would carry a flag nobody
        set into its new life as an explicit override, and keep the bug. Null means
        "follow the item master", which is what those rows always meant.
        """
        # `_default_manager`, not `.objects`: historical models in a migration do not
        # carry custom managers (SecureManager is not use_in_migrations), so `.objects`
        # is simply absent.
        BOMLine = apps.get_model('Tracker', 'BOMLine')
        BOMLine._default_manager.filter(allow_harvested=True).update(allow_harvested=None)

    def _noop(apps, schema_editor):
        pass

    operations = [
        migrations.AddField(
            model_name='parttypes',
            name='can_recover',
            field=models.BooleanField(default=False, help_text='Whether a used one of these can be recovered from a torn-down core and put back into service. The MRO classification — rotable and repairable items can; expendables (seals, gaskets, lockwire, most springs) are fitted once and discarded.'),
        ),
        migrations.AlterField(
            model_name='bomline',
            name='allow_harvested',
            field=models.BooleanField(blank=True, help_text="Per-use OVERRIDE of the component type's `can_recover`. Leave blank to follow the item master, which is the right answer almost always. Set False for the exception: a safety-critical position or a customer contract that forbids reuse even of a normally recoverable item.", null=True),
        ),
        migrations.RunPython(_clear_default_true, _noop),
    ]
