# Generated by Django 5.1.6 on 2026-09-23 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0189_recoverability_on_item_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblyusage',
            name='assembly_core',
            field=models.ForeignKey(blank=True, help_text='The core this component was installed into, for a repair-and-return rebuild where the unit IS the core rather than a Parts row.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='component_usages', to='Tracker.core'),
        ),
        migrations.AddField(
            model_name='assemblyusage',
            name='component_harvested',
            field=models.ForeignKey(blank=True, help_text="The harvested component installed — the customer's own part going back into their own unit, which never became a Parts row.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='installed_in', to='Tracker.harvestedcomponent'),
        ),
        migrations.AddField(
            model_name='core',
            name='return_reference',
            field=models.CharField(blank=True, help_text='Consignment note, tracking number or whatever the shop can trace it by in the system that actually shipped it.', max_length=100),
        ),
        migrations.AddField(
            model_name='core',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='core',
            name='returned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_cores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assemblyusage',
            name='assembly',
            field=models.ForeignKey(blank=True, help_text='The parent assembly this component was installed into. Null for a core rebuild, where the parent is `assembly_core`.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='component_usages', to='Tracker.parts'),
        ),
        migrations.AlterField(
            model_name='assemblyusage',
            name='component',
            field=models.ForeignKey(blank=True, help_text='The component part installed. Null when the thing installed is a harvested component that never became stock.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='installed_in', to='Tracker.parts'),
        ),
        migrations.AlterField(
            model_name='core',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('IN_DISASSEMBLY', 'In Disassembly'), ('DISASSEMBLED', 'Disassembled'), ('IN_REBUILD', 'In Rebuild'), ('REBUILT', 'Rebuilt — ready to return'), ('RETURNED', 'Returned to customer'), ('AWAITING_AUTHORISATION', 'Awaiting customer authorisation'), ('DECLINED', 'Scope declined — to be returned unrepaired'), ('RETURNED_UNREPAIRED', 'Returned unrepaired'), ('HARVESTED', 'Harvested to inventory'), ('SCRAPPED', 'Scrapped')], default='RECEIVED', max_length=30),
        ),
        migrations.AddIndex(
            model_name='assemblyusage',
            index=models.Index(fields=['assembly_core'], name='Tracker_ass_assembl_0e5f9c_idx'),
        ),
        migrations.AddConstraint(
            model_name='assemblyusage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('assembly__isnull', False), ('assembly_core__isnull', True)), models.Q(('assembly__isnull', True), ('assembly_core__isnull', False)), _connector='OR'), name='assemblyusage_one_parent'),
        ),
        migrations.AddConstraint(
            model_name='assemblyusage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('component__isnull', False), ('component_harvested__isnull', True)), models.Q(('component__isnull', True), ('component_harvested__isnull', False)), _connector='OR'), name='assemblyusage_one_component'),
        ),
    ]
