# Generated by Django 5.1.6 on 2026-09-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0190_rebuild_return_and_asbuilt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='part_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('AT_OUTSIDE_PROCESS', 'At Outside Process'), ('AWAITING_QA', 'Awaiting QA'), ('READY_FOR_NEXT_STEP', 'Ready for next step'), ('COMPLETED', 'Completed'), ('QUARANTINED', 'Quarantined'), ('REWORK_NEEDED', 'Rework Needed'), ('REWORK_IN_PROGRESS', 'Rework In Progress'), ('ON_HOLD', 'On Hold'), ('SCRAPPED', 'Scrapped'), ('CANCELLED', 'Cancelled'), ('SHIPPED', 'Shipped'), ('IN_STOCK', 'In Stock'), ('AWAITING_PICKUP', 'Awaiting Pickup'), ('CORE_BANKED', 'Core Banked'), ('RMA_CLOSED', 'RMA Closed'), ('DISMANTLED', 'Dismantled')], default='PENDING', max_length=50),
        ),
    ]
