# Generated by Django 5.1.6 on 2026-09-24 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0191_parts_on_hold_dismantled'),
    ]

    operations = [
        migrations.AddField(
            model_name='core',
            name='part',
            field=models.OneToOneField(blank=True, help_text='The part this core is. Its part_status is derived from `status`.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_role', to='Tracker.parts'),
        ),
    ]
