# Generated by Django 5.1.6 on 2026-09-24 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0193_core_part_backfill'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assemblyusage',
            name='assemblyusage_one_parent',
        ),
        migrations.RemoveConstraint(
            model_name='scheduledtask',
            name='scheduledtask_part_xor_core',
        ),
        migrations.RemoveConstraint(
            model_name='stepexecution',
            name='step_execution_one_subject',
        ),
        migrations.RemoveConstraint(
            model_name='steptransitionlog',
            name='step_transition_log_one_subject',
        ),
        migrations.RemoveIndex(
            model_name='assemblyusage',
            name='Tracker_ass_assembl_0e5f9c_idx',
        ),
        migrations.RemoveIndex(
            model_name='scheduledtask',
            name='Tracker_sch_core_id_4550db_idx',
        ),
        migrations.RemoveIndex(
            model_name='stepexecution',
            name='Tracker_ste_core_id_a340d0_idx',
        ),
        migrations.RemoveField(
            model_name='assemblyusage',
            name='assembly_core',
        ),
        migrations.RemoveField(
            model_name='core',
            name='step',
        ),
        migrations.RemoveField(
            model_name='core',
            name='work_order',
        ),
        migrations.RemoveField(
            model_name='scheduledtask',
            name='core',
        ),
        migrations.RemoveField(
            model_name='stepexecution',
            name='core',
        ),
        migrations.RemoveField(
            model_name='steptransitionlog',
            name='core',
        ),
        migrations.AlterField(
            model_name='assemblyusage',
            name='assembly',
            field=models.ForeignKey(blank=True, help_text="The parent this component was installed into — for a core rebuild, the core's part.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='component_usages', to='Tracker.parts'),
        ),
        migrations.AlterField(
            model_name='core',
            name='part',
            field=models.OneToOneField(help_text='The part this core is. Its part_status is derived from `status`.', on_delete=django.db.models.deletion.PROTECT, related_name='core_role', to='Tracker.parts'),
        ),
        migrations.AlterField(
            model_name='stepexecution',
            name='part',
            field=models.ForeignKey(blank=True, help_text='The part being tracked through this step. A reman core is a part too; its role is `part.core_role`.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step_executions', to='Tracker.parts'),
        ),
        migrations.AlterField(
            model_name='steptransitionlog',
            name='part',
            field=models.ForeignKey(blank=True, help_text='The part that transitioned to the step. A reman core is a part too.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tracker.parts'),
        ),
        migrations.AddConstraint(
            model_name='assemblyusage',
            constraint=models.CheckConstraint(condition=models.Q(('assembly__isnull', False)), name='assemblyusage_has_parent'),
        ),
        migrations.AddConstraint(
            model_name='scheduledtask',
            constraint=models.CheckConstraint(condition=models.Q(('part__isnull', False)), name='scheduledtask_has_part'),
        ),
    ]
