# Generated by Django 5.1.6 on 2026-09-24 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0195_substep_response_component_install'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='received_in_lot',
            field=models.ForeignKey(blank=True, help_text='The bulk receipt this unit was given its identity from, if any.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='identified_units', to='Tracker.materiallot'),
        ),
    ]
