# Generated by Django 5.1.6 on 2026-09-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0196_parts_received_in_lot'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiallot',
            name='holds_cores',
            field=models.BooleanField(default=False, help_text='Cores received in bulk (units to be identified), not stock of the part.'),
        ),
    ]
