# Generated by Django 5.1.6 on 2026-09-24 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0197_materiallot_holds_cores'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestedcomponent',
            name='proposed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='harvestedcomponent',
            name='proposed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_component_findings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='harvestedcomponent',
            name='proposed_finding',
            field=models.TextField(blank=True, help_text="What was found, in the operator's words."),
        ),
        migrations.AddField(
            model_name='harvestedcomponent',
            name='proposed_grade',
            field=models.CharField(blank=True, choices=[('A', 'Grade A - Excellent'), ('B', 'Grade B - Good'), ('C', 'Grade C - Fair'), ('SCRAP', 'Scrap - Not Usable')], help_text="A re-grade raised after teardown, awaiting a lead's decision.", max_length=10),
        ),
        migrations.AlterField(
            model_name='substepresponse',
            name='kind',
            field=models.CharField(choices=[('text', 'Text input'), ('choice', 'Choice (radio / select)'), ('photo', 'Photo capture'), ('video', 'Video capture'), ('scan', 'Barcode / QR scan'), ('file', 'File upload'), ('timer', 'Timer (countdown / stopwatch)'), ('computed', 'Computed value (formula)'), ('attestation', 'Attestation (confirm / signature)'), ('status', 'Quality status (PASS / FAIL / PENDING)'), ('equipment_roles', 'Equipment + roles'), ('personnel_roles', 'Personnel + roles'), ('signatures', 'Inspection signatures (detected / verified)'), ('defects', 'Defect findings'), ('annotation', 'Part annotation (3D)'), ('harvested_components', 'Harvested components (teardown)'), ('component_install', 'Components installed (rebuild)'), ('rebuild_finding', 'Finding raised during rebuild')], help_text='Which kind of capture node produced this response.', max_length=20),
        ),
    ]
