# Generated by Django 5.1.6 on 2026-09-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0198_rebuild_findings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('IN_DISASSEMBLY', 'In Disassembly'), ('DISASSEMBLED', 'Disassembled'), ('IN_REBUILD', 'In Rebuild'), ('REBUILT', 'Rebuilt — ready to return'), ('RETURNED', 'Returned to customer'), ('REBUILT_TO_STOCK', 'Rebuilt to stock'), ('AWAITING_AUTHORISATION', 'Awaiting customer authorisation'), ('DECLINED', 'Scope declined — to be returned unrepaired'), ('RETURNED_UNREPAIRED', 'Returned unrepaired'), ('HARVESTED', 'Harvested to inventory'), ('SCRAPPED', 'Scrapped')], default='RECEIVED', max_length=30),
        ),
    ]
