# Generated by Django 5.1.6 on 2026-09-29 22:33

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0199_core_rebuilt_to_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiallot',
            name='source_reference',
            field=models.CharField(blank=True, help_text='For migrated stock: where its certificate / traceability record lives.', max_length=255),
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='source_reference',
            field=models.CharField(blank=True, help_text="Where the original record lives, for migrated history (e.g. 'HR system, cert #4471').", max_length=255),
        ),
        migrations.CreateModel(
            name='MigrationBatch',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('kind', models.CharField(choices=[('TRAINING_RECORDS', 'Training records'), ('MATERIAL_LOTS', 'Material lots')], max_length=20)),
                ('source_system', models.CharField(help_text="The system this history came from (e.g. 'Legacy HR — Workday').", max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='migration_batches', to=settings.AUTH_USER_MODEL)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.migrationbatch')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant')),
                ('verified_by', models.ForeignKey(blank=True, help_text='Who checked the load against the source (quantities against the go-live count, a sample of records against the originals). Not the loader.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_migration_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Migration batch',
                'verbose_name_plural': 'Migration batches',
                'ordering': ['-created_at'],
            },
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='materiallot',
            name='migration_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_lots', to='Tracker.migrationbatch'),
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='migration_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_records', to='Tracker.migrationbatch'),
        ),
    ]
