# Generated by Django 5.1.6 on 2026-09-29 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0200_migration_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiallot',
            name='migration_batch',
        ),
        migrations.RemoveField(
            model_name='trainingrecord',
            name='migration_batch',
        ),
        migrations.RemoveField(
            model_name='materiallot',
            name='source_reference',
        ),
        migrations.RemoveField(
            model_name='trainingrecord',
            name='source_reference',
        ),
        migrations.DeleteModel(
            name='MigrationBatch',
        ),
    ]
