# Generated by Django 5.1.6 on 2026-09-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0201_remove_migration_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiallot',
            name='ordered_quantity',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='What was on order, when the delivery was short of it.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='materiallot',
            name='short_receipt',
            field=models.CharField(blank=True, choices=[('BACKORDERED', 'More coming'), ('CLOSED', "That's all")], default='', help_text='For a short delivery: the remainder stays on order (BACKORDERED) or the order closed at what arrived (CLOSED).', max_length=12),
        ),
    ]
