# Generated by Django 5.1.6 on 2026-09-30 20:17

from django.db import migrations
from django.db.models import Q


def carry_to_definition(apps, schema_editor):
    """A balloon number names the drawing feature, so it lives on MeasurementDefinition.
    Before the step requirement's duplicate goes, copy any value it holds onto its
    definition where the definition has none — never over a different one."""
    Requirement = apps.get_model('Tracker', 'StepMeasurementRequirement')
    Definition = apps.get_model('Tracker', 'MeasurementDefinition')
    # Migration: runs outside any tenant context, over every tenant's rows.
    for req in Requirement.objects.exclude(characteristic_number='').only('measurement_id', 'characteristic_number'):
        # The definition's field is nullable, so "none" is NULL or blank.
        Definition.objects.filter(pk=req.measurement_id).filter(
            Q(characteristic_number__isnull=True) | Q(characteristic_number='')
        ).update(characteristic_number=req.characteristic_number)


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0202_material_lot_short_receipt'),
    ]

    operations = [
        migrations.RunPython(carry_to_definition, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='stepmeasurementrequirement',
            name='characteristic_number',
        ),
    ]
