# Generated by Django 5.1.6 on 2026-09-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0203_drop_smr_characteristic_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiallot',
            name='erp_po_line',
            field=models.CharField(blank=True, help_text='Line on the ERP purchase order.', max_length=20),
        ),
    ]
