# Generated by Django 5.1.6 on 2026-09-30 21:40

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0204_material_lot_erp_po_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='purchase_unit',
            field=models.CharField(choices=[('STOCK', 'Stock unit'), ('BOX', 'Box'), ('LB', 'Pound')], default='STOCK', help_text='How this item is bought and counted at receiving.', max_length=10),
        ),
        migrations.AddField(
            model_name='material',
            name='requires_coc',
            field=models.BooleanField(default=False, help_text='Hold each received lot until its certificate of conformance is uploaded.'),
        ),
        migrations.AddField(
            model_name='material',
            name='requires_heat_number',
            field=models.BooleanField(default=False, help_text='Hold each received lot until its heat / melt number is entered.'),
        ),
        migrations.AddField(
            model_name='material',
            name='units_per_purchase_unit',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Stock units in one purchase unit — pieces per box, or pieces per pound. Unused when the purchase unit is the stock unit.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='materiallot',
            name='heat_number',
            field=models.CharField(blank=True, help_text='Heat / melt number from the mill certificate.', max_length=64),
        ),
        migrations.AddField(
            model_name='materiallot',
            name='received_as_quantity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='materiallot',
            name='received_as_unit',
            field=models.CharField(blank=True, choices=[('STOCK', 'Stock unit'), ('BOX', 'Box'), ('LB', 'Pound')], max_length=10),
        ),
        migrations.AddField(
            model_name='materiallot',
            name='source_type',
            field=models.CharField(blank=True, choices=[('MANUFACTURER', 'Manufacturer'), ('AUTHORIZED_DISTRIBUTOR', 'Authorized distributor'), ('INDEPENDENT_DISTRIBUTOR', 'Independent distributor')], help_text='Bought from the manufacturer, an authorized distributor, or an independent one.', max_length=30),
        ),
        migrations.AddField(
            model_name='parttypes',
            name='purchase_unit',
            field=models.CharField(choices=[('STOCK', 'Stock unit'), ('BOX', 'Box'), ('LB', 'Pound')], default='STOCK', help_text='How this part is bought and counted at receiving.', max_length=10),
        ),
        migrations.AddField(
            model_name='parttypes',
            name='requires_coc',
            field=models.BooleanField(default=False, help_text='Hold each received lot until its certificate of conformance is uploaded.'),
        ),
        migrations.AddField(
            model_name='parttypes',
            name='requires_heat_number',
            field=models.BooleanField(default=False, help_text='Hold each received lot until its heat / melt number is entered.'),
        ),
        migrations.AddField(
            model_name='parttypes',
            name='units_per_purchase_unit',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Stock units in one purchase unit — pieces per box, or pieces per pound. Unused when the purchase unit is the stock unit.', max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.storagelocation')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant')),
            ],
            options={
                'verbose_name': 'Storage Location',
                'verbose_name_plural': 'Storage Locations',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'name'), name='storage_location_unique_per_tenant')],
            },
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
    ]
