# Generated by Django 5.1.6 on 2026-09-30 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0205_receiving_dock_controls'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='commodity',
            field=models.CharField(blank=True, help_text="The commodity a supplier is qualified for when they supply this, e.g. 'Elastomer seals'. Matches a commodity-scope supplier qualification.", max_length=100),
        ),
        migrations.AddField(
            model_name='material',
            name='requires_supplier_qualification',
            field=models.BooleanField(default=False, help_text="Hold received lots from a supplier with no active qualification for this material's commodity (or none at all, when no commodity is set)."),
        ),
        migrations.AddField(
            model_name='steps',
            name='material',
            field=models.ForeignKey(blank=True, help_text='For a Receiving Inspection Plan of a raw material (bulk stock): the material it inspects. Only a RECEIVING step may carry one.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receiving_plans', to='Tracker.material'),
        ),
        migrations.AddField(
            model_name='substep',
            name='once_per_lot',
            field=models.BooleanField(default=False, help_text='Receiving inspection only: ask this once for the lot, not on every sampled unit. A variables (Z1.9) plan walks the substeps once per sampled unit; a lot-level check — is the CoC present and correct? — belongs on the first pass only. Distinct from BATCH scope, which is a work-order batch sharing one BatchExecution.'),
        ),
        migrations.AddField(
            model_name='supplierqualification',
            name='certification_type',
            field=models.CharField(blank=True, choices=[('ISO9001', 'ISO 9001'), ('IATF16949', 'IATF 16949'), ('AS9100', 'AS9100'), ('NADCAP', 'Nadcap'), ('OTHER', 'Other')], help_text='Which certificate, when the basis is Certification.', max_length=12),
        ),
        migrations.AlterField(
            model_name='samplingruleset',
            name='part_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tracker.parttypes'),
        ),
        migrations.AlterField(
            model_name='steps',
            name='part_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='steps', to='Tracker.parttypes'),
        ),
        migrations.AlterField(
            model_name='supplierqualification',
            name='basis',
            field=models.CharField(blank=True, choices=[('AUDIT', 'Audit'), ('PPAP', 'PPAP'), ('FAI', 'First Article'), ('SURVEY', 'Survey'), ('HISTORICAL', 'Historical'), ('CERTIFICATION', 'Certification')], max_length=15),
        ),
        migrations.AddConstraint(
            model_name='steps',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('part_type__isnull', False), ('material__isnull', True)), models.Q(('part_type__isnull', True), ('material__isnull', False), ('step_type', 'RECEIVING')), _connector='OR'), name='step_part_type_xor_receiving_material'),
        ),
    ]
