# Generated by Django 5.1.6 on 2026-10-01 01:35

import django.db.models.deletion
from django.db import migrations, models


def link_existing_lot_dispositions(apps, schema_editor):
    """Dispositions opened on a rejected lot before this migration reached it only
    through the inspection report. Give each its lot (and the lot's quantity) so a
    rejection made before it can still be shipped back, scrapped or accepted."""
    Disposition = apps.get_model("Tracker", "QuarantineDisposition")
    for d in (Disposition._base_manager.filter(part__isnull=True, material_lot__isnull=True)
              .prefetch_related("quality_reports")):
        report = next((r for r in d.quality_reports.all() if r.material_lot_id), None)
        if report is None:
            continue
        d.material_lot_id = report.material_lot_id
        d.quantity = report.material_lot.quantity
        d.save(update_fields=["material_lot", "quantity"])


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0206_receiving_inspection_for_materials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materiallot',
            options={'ordering': ['-received_date'], 'permissions': [('reject_whole_lot', 'Can reject a whole lot back to the vendor')], 'verbose_name': 'Material Lot', 'verbose_name_plural': 'Material Lots'},
        ),
        migrations.AddField(
            model_name='quarantinedisposition',
            name='material_lot',
            field=models.ForeignKey(blank=True, help_text='The rejected material lot this disposition decides.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispositions', to='Tracker.materiallot'),
        ),
        migrations.AddField(
            model_name='quarantinedisposition',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="How much is dispositioned, in the lot's stock unit.", max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='materiallot',
            name='status',
            field=models.CharField(choices=[('ON_ORDER', 'On Order'), ('RECEIVED', 'Received'), ('AWAITING_INSPECTION', 'Awaiting Inspection'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('IN_USE', 'In Use'), ('CONSUMED', 'Consumed'), ('SCRAPPED', 'Scrapped'), ('QUARANTINE', 'Quarantine'), ('RETURNED', 'Returned to supplier')], default='RECEIVED', max_length=20),
        ),
        migrations.RunPython(link_existing_lot_dispositions, migrations.RunPython.noop),
    ]
