# Generated by Django 5.1.6 on 2026-10-01 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0207_lot_dispositions_and_returns'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='address',
            field=models.TextField(blank=True, help_text='Postal address — printed on SCARs and return-to-vendor sheets.'),
        ),
        migrations.AddField(
            model_name='companies',
            name='is_customer',
            field=models.BooleanField(default=True, help_text='Buys from us.'),
        ),
        migrations.AddField(
            model_name='companies',
            name='is_supplier',
            field=models.BooleanField(default=True, help_text='Sells to us.'),
        ),
        migrations.AddField(
            model_name='materiallot',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The customer this stock belongs to, when it is theirs, not ours.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_lots', to='Tracker.companies'),
        ),
        migrations.AddField(
            model_name='user',
            name='contact_role',
            field=models.CharField(blank=True, choices=[('QUALITY', 'Quality'), ('EXPEDITING', 'Deliveries / expediting'), ('GENERAL', 'General')], help_text='For an outside contact: what to come to them about.', max_length=12),
        ),
    ]
