# Generated by Django 5.1.6 on 2026-10-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0208_companies_contacts_customer_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiallot',
            name='status',
            field=models.CharField(choices=[('ON_ORDER', 'On Order'), ('RECEIVED', 'Received'), ('AWAITING_INSPECTION', 'Awaiting Inspection'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('IN_USE', 'In Use'), ('CONSUMED', 'Consumed'), ('SCRAPPED', 'Scrapped'), ('QUARANTINE', 'Quarantine'), ('RETURNED', 'Returned to supplier'), ('CANCELLED', 'Cancelled')], default='RECEIVED', max_length=20),
        ),
    ]
