# Generated by Django 5.1.6 on 2026-10-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0209_material_lot_cancelled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parttypes',
            options={'permissions': [('change_parttype_sourcing', "Can change a part type's sourcing (preferred supplier, lead time, safety stock)")], 'verbose_name': 'Part Type', 'verbose_name_plural': 'Part Types'},
        ),
        migrations.AddField(
            model_name='parttypes',
            name='safety_stock',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Buffer held back from planning, as on Material: coverage nets against on-hand MINUS this, so the sourcing report warns while there is still stock to react with. Does not block issuing.', max_digits=12, null=True),
        ),
    ]
