# Generated by Django 5.1.6 on 2026-10-05 14:31

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0210_part_type_safety_stock_sourcing'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='requires_coc_on_shipment',
            field=models.BooleanField(default=False, help_text='Print a Certificate of Conformance with every shipment to this customer.'),
        ),
        migrations.CreateModel(
            name='CustomerShipment',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('is_voided', models.BooleanField(default=False, help_text='Whether this record has been voided')),
                ('voided_at', models.DateTimeField(blank=True, help_text='When this record was voided', null=True)),
                ('void_reason', models.TextField(blank=True, help_text='Reason for voiding this record')),
                ('shipment_number', models.CharField(blank=True, help_text='Auto-generated, tenant-unique (SHP-YYYY-######).', max_length=100)),
                ('shipped_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('carrier', models.CharField(blank=True, max_length=120)),
                ('tracking_number', models.CharField(blank=True, max_length=120)),
                ('reference', models.CharField(blank=True, help_text="The ERP's shipper or packing-slip number, so the two can be matched.", max_length=120)),
                ('expected_delivery', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(help_text='Who the units went to.', on_delete=django.db.models.deletion.PROTECT, related_name='customer_shipments', to='Tracker.companies')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.customershipment')),
                ('shipped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_shipments_sent', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant')),
                ('voided_by', models.ForeignKey(blank=True, help_text='User who voided this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Shipment',
                'verbose_name_plural': 'Customer Shipments',
                'ordering': ['-shipped_at'],
            },
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='parts',
            name='customer_shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='Tracker.customershipment'),
        ),
        migrations.AddIndex(
            model_name='customershipment',
            index=models.Index(fields=['customer', 'shipped_at'], name='Tracker_cus_custome_520190_idx'),
        ),
        migrations.AddConstraint(
            model_name='customershipment',
            constraint=models.UniqueConstraint(condition=models.Q(('shipment_number__isnull', False), models.Q(('shipment_number', ''), _negated=True)), fields=('tenant', 'shipment_number'), name='customer_shipment_tenant_number_uniq'),
        ),
    ]
