# Generated by Django 5.1.6 on 2026-10-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0211_customer_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='storage_location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
