# Generated by Django 5.1.6 on 2026-10-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0212_part_storage_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiallot',
            name='chase_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='materiallot',
            name='chased_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materiallot',
            name='original_promised_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
