# Generated by Django 5.1.6 on 2026-10-05 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0214_material_lot_erp_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiallot',
            name='customer_shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_lots', to='Tracker.customershipment'),
        ),
        migrations.AddField(
            model_name='materiallot',
            name='replaces',
            field=models.ForeignKey(blank=True, help_text='The returned lot this delivery replaces.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacements', to='Tracker.materiallot'),
        ),
        migrations.AddField(
            model_name='materiallot',
            name='rma_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='materiallot',
            name='status',
            field=models.CharField(choices=[('ON_ORDER', 'On Order'), ('RECEIVED', 'Received'), ('AWAITING_INSPECTION', 'Awaiting Inspection'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('IN_USE', 'In Use'), ('CONSUMED', 'Consumed'), ('SCRAPPED', 'Scrapped'), ('QUARANTINE', 'Quarantine'), ('RETURNED', 'Returned to supplier'), ('CANCELLED', 'Cancelled'), ('SHIPPED', 'Shipped to customer')], default='RECEIVED', max_length=20),
        ),
    ]
