# Generated by Django 5.1.6 on 2026-10-05 16:32

from django.db import migrations, models


def backfill(apps, schema_editor):
    """Each held lot's one reason becomes its list of one."""
    MaterialLot = apps.get_model("Tracker", "MaterialLot")
    for lot in MaterialLot._base_manager.exclude(hold_reason="").only("id", "hold_reason"):
        MaterialLot._base_manager.filter(pk=lot.pk).update(hold_reasons=[lot.hold_reason])


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0215_lot_shipping_rma'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiallot',
            name='hold_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
