# Generated by Django 5.1.6 on 2026-10-05 16:39

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0216_lot_hold_reasons'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleCount',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External system identifier for integration sync', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('count_number', models.CharField(blank=True, max_length=40)),
                ('location', models.CharField(max_length=100)),
                ('blind', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('OPEN', 'Counting'), ('SUBMITTED', 'Submitted'), ('APPLIED', 'Applied')], default='OPEN', max_length=20)),
                ('lines', models.JSONField(blank=True, default=list)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='Tracker.cyclecount')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='Tracker.tenant')),
            ],
            options={
                'verbose_name': 'Cycle Count',
                'verbose_name_plural': 'Cycle Counts',
                'ordering': ['-created_at'],
                'permissions': [('apply_cyclecount', 'Can apply a submitted cycle count to stock')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('count_number__isnull', False), models.Q(('count_number', ''), _negated=True)), fields=('tenant', 'count_number'), name='cycle_count_tenant_number_uniq')],
            },
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
    ]
