# Generated by Django 5.1.6 on 2026-10-06 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0220_storage_location_drop_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityreports',
            name='capa_decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qualityreports',
            name='capa_decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capa_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qualityreports',
            name='capa_decision',
            field=models.CharField(blank=True, choices=[('PROMOTED', 'CAPA raised'), ('NOT_REQUIRED', 'No CAPA needed'), ('DEFERRED', 'Deferred')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='qualityreports',
            name='capa_decision_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
