# Generated by Django 5.1.6 on 2026-10-07 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0221_qualityreport_capa_decision'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stepoverride',
            options={'ordering': ['-requested_at'], 'permissions': [('approve_stepoverride', 'Can approve or reject step override requests')], 'verbose_name': 'Step Override', 'verbose_name_plural': 'Step Overrides'},
        ),
    ]
