# Generated by Django 5.1.6 on 2026-10-07 13:48
"""RCA self-verification, made whole (2026-10-07).

1. `verification_notes` keeps the justification approve_rca demands for a
   self-verification; it was validated and then discarded.
2. `conducted_by` is backfilled on RCAs created before it was set. No create path set it,
   so every RCA made in the app had a null author and the independence rule could never
   apply to it. The author is the actor on django-auditlog's create entry for the row;
   where there is no entry or no actor, the row stays null rather than being guessed at.
"""
from django.db import migrations, models

AUDITLOG_CREATE = 0  # auditlog.models.LogEntry.Action.CREATE


def backfill_conducted_by(apps, schema_editor):
    RcaRecord = apps.get_model("Tracker", "RcaRecord")
    LogEntry = apps.get_model("auditlog", "LogEntry")
    ContentType = apps.get_model("contenttypes", "ContentType")
    ct = ContentType.objects.filter(app_label="Tracker", model="rcarecord").first()
    if ct is None:
        return
    # tenant-safe: data migration runs outside any request; rows are updated by pk.
    for pk in RcaRecord._base_manager.filter(conducted_by__isnull=True).values_list("pk", flat=True):
        actor_id = (LogEntry.objects
                    .filter(content_type=ct, object_pk=str(pk), action=AUDITLOG_CREATE,
                            actor__isnull=False)
                    .order_by("timestamp")
                    .values_list("actor_id", flat=True)
                    .first())
        if actor_id is not None:
            RcaRecord._base_manager.filter(pk=pk).update(conducted_by_id=actor_id)


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0222_stepoverride_approve_permission'),
        ('auditlog', '0017_add_actor_email'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rcarecord',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Notes given at verification; the justification for a self-verification'),
        ),
        # Not reversible in content: which nulls were filled isn't recorded, and blanking
        # authors the audit log supports would lose them. Reversing leaves them set.
        migrations.RunPython(backfill_conducted_by, migrations.RunPython.noop),
    ]
