# Generated by Django 5.1.6 on 2026-10-07 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0223_rca_verification_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarantinedisposition',
            name='containment_performed_by',
            field=models.ForeignKey(blank=True, help_text='Who carried out the containment, if not the person recording it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quarantinedisposition',
            name='resolution_performed_by',
            field=models.ForeignKey(blank=True, help_text='Who carried out the resolution (rework, repair, scrap), if not the person closing it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
