"""
Django settings for PartsTracker project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv, dotenv_values

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file from project root (one level up from PartsTracker/)
load_dotenv(dotenv_path=BASE_DIR.parent / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "dev-secret-key-CHANGE-ME")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', True)

# ALLOWED_HOSTS = ["192.168.99.1", "localhost", "127.0.0.1"]
ALLOWED_HOSTS = ["*"]
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.admindocs',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.microsoft",
    'Tracker',
    "tailwind",
    "theme",
    "django_browser_reload",
    "formtools",
    'auditlog',
    'widget_tweaks',

    "rest_framework",
    "rest_framework.authtoken",
    "dj_rest_auth",
    "dj_rest_auth.registration",
    "corsheaders",
    "drf_spectacular",
    'django_crontab',
]

MIDDLEWARE = [
    'auditlog.middleware.AuditlogMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "allauth.account.middleware.AccountMiddleware",
    "django_browser_reload.middleware.BrowserReloadMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
]

ROOT_URLCONF = 'PartsTrackerApp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'PartsTrackerApp.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'tracker_AMBAC'),
        'USER': os.environ.get('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', "Annoy1ng"),
        'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#### Non boilerplate starts here ####

AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
)

AUTH_USER_MODEL = 'Tracker.User'

STATICFILES_DIRS = (
    BASE_DIR / 'Tracker/static',
)

SITE_ID = 1

SOCIALACCOUNT_PROVIDERS = {
    "microsoft": {
        "APP": {
            "client_id": "YOUR_CLIENT_ID",
            "secret": "YOUR_CLIENT_SECRET",
            "key": "",
        },
        "SCOPE": ["email", "profile"],
        "AUTH_PARAMS": {"response_type": "code"},
    }
}

ACCOUNT_LOGIN_METHODS = ["email"]
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",  # for browser session login
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",  # default gate
        'rest_framework.permissions.DjangoModelPermissions',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": 25,
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend',
                                'rest_framework.filters.OrderingFilter', ],
}

SPECTACULAR_SETTINGS = {
    # —————————————————————————————————————————————————————————————————————————————————
    # Basic API metadata (shows up in the generated Swagger/OpenAPI UI)
    # —————————————————————————————————————————————————————————————————————————————————
    "TITLE":        "My Project API",
    "DESCRIPTION":  "REST endpoints for our tracker system",
    "VERSION":      "1.0.0",

    "SKIP_READ_ONLY_FIELDS": True,
    "SKIP_WRITE_ONLY_FIELDS": True,
    "COMPONENT_SPLIT_REQUEST": True,
    "ENUM_NAME_OVERRIDES": {
        # "Tracker.models.Orders.order_status": "OrderStatusEnum",
        # "Tracker.models.Parts.part_status": "PartStatusEnum",
        # "Tracker.models.WorkOrder.workorder_status": "WorkOrderStatusEnum",
    },
}
CORS_ALLOWED_ORIGINS = os.getenv("CORS_ALLOWED_ORIGINS", "http://localhost:5173").split(",")
CSRF_TRUSTED_ORIGINS = os.getenv("CSRF_TRUSTED_ORIGINS", "http://localhost:5173").split(",")
CORS_ALLOW_CREDENTIALS = os.getenv("CORS_ALLOW_CREDENTIALS", "false").lower() == "true"

DJANGO_DEBUG = os.environ.get('DJANGO_DEBUG', True)

LOGIN_REDIRECT_URL = '/tracker'

LOGOUT_REDIRECT_URL = '/tracker'

HUBSPOT_API_KEY = os.environ.get("HUBSPOT_API_KEY")

HUBSPOT_SYNC_ORDER_NAMES = ["Test Order Sync", "Production Alpha"]

TAILWIND_APP_NAME = 'theme'

INTERNAL_IPS = [
    "127.0.0.1",
]

CRONJOBS = [
    # Tuesday at 3:00 PM - send weekly customer emails
    ('0 15 * * 2', 'django.core.management.call_command', ['send_weekly_emails']),
]

X_FRAME_OPTIONS = 'SAMEORIGIN'

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

NPM_BIN_PATH = os.environ.get("NPM_BIN_PATH")

AUDITLOG_INCLUDE_ALL_MODELS = True

HUBSPOT_DEBUG = True

if DEBUG:
    PASSWORD_RESET_DOMAIN = 'localhost:5173'
    PASSWORD_RESET_PROTOCOL = 'http'
else:
    PASSWORD_RESET_DOMAIN = os.environ.get("FRONTEND_URL", "")
    PASSWORD_RESET_PROTOCOL = 'https'

REST_AUTH = {
    'PASSWORD_RESET_SERIALIZER': 'Tracker.serializer.PasswordResetSerializer',  # Replace 'your_app'
    'PASSWORD_RESET_CONFIRM_URL': 'http://localhost:5173/reset-password/{uid}/{token}/',
    'PASSWORD_RESET_USE_SITES_DOMAIN': False,
}

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
# EMAIL_HOST = "smtp.your-email-provider.com"
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = "your-email@example.com"
# EMAIL_HOST_PASSWORD = "your-password"
DEFAULT_FROM_EMAIL = "webmaster@new_exampl.com"
