// SPC Report template.
//
// Context: Tracker/reports/adapters/spc.py → SpcReportContext
//
// Layout:
//   1. Title block — measurement label + chart mode badge
//   2. Header grid (process / step / window / generator)
//   3. Specification limits
//   4. Active baseline (only when present)
//   5. Descriptive statistics
//   6. Process capability (Cp/Cpk/Pp/Ppk + interpretation)
//   7. Data points table (capped at 500 rows; flag when truncated)

#import "_common/page-setup.typ": *

#let data = json.decode(sys.inputs.at("data"))

// ----------------------------------------------------------------------------
// Helpers
// ----------------------------------------------------------------------------

#let badge(label, fg, bg) = box(
  fill: bg, inset: (x: 6pt, y: 2pt), radius: 3pt,
  text(size: 8.5pt, weight: "semibold", fill: fg, font: sans-font)[#label],
)

#let mode-badge(m) = {
  if m == "xbar-r"      { badge("X̄-R", accent, rgb("#dbeafe")) }
  else if m == "xbar-s" { badge("X̄-S", accent, rgb("#dbeafe")) }
  else if m == "i-mr"   { badge("I-MR", accent, rgb("#dbeafe")) }
  else                  { badge(m,      muted,  rgb("#e2e8f0")) }
}

#let kv(label, value) = grid(
  columns: (auto, 1fr),
  column-gutter: 10pt,
  text(fill: muted, font: sans-font, size: 9pt)[*#label*],
  if value == none or value == "" [
    #text(fill: muted, style: "italic")[—]
  ] else [
    #value
  ],
)

#let divider() = {
  v(6pt); line(length: 100%, stroke: 0.4pt + rule); v(6pt)
}

// Format optional numeric values (none → em-dash)
#let fmt-num(v, digits: 3, suffix: "") = {
  if v == none [ #text(fill: muted, style: "italic")[—] ]
  else [ #str(calc.round(v, digits: digits))#suffix ]
}

#let fmt-int(v) = if v == none [ #text(fill: muted, style: "italic")[—] ] else [ #str(v) ]

#let fmt-date(d) = if d == none or d == "" [ #text(fill: muted, style: "italic")[—] ] else [ #d ]

// ----------------------------------------------------------------------------
// Document
// ----------------------------------------------------------------------------

#show: page-setup.with(
  title: "SPC Report",
  doc-id: data.measurement_label,
  classification: "Controlled Document — Quality Management System",
)

// ── Title block ───────────────────────────────────────────────────────────────

#align(center)[
  #text(size: 9pt, fill: muted, tracking: 2pt, font: sans-font)[
    STATISTICAL PROCESS CONTROL REPORT
  ]
  #v(2pt)
  #text(size: 20pt, weight: "bold", font: sans-font)[#data.measurement_label]
  #v(-4pt)
  #text(size: 10pt, fill: muted)[#data.tenant_name]
  #v(6pt)
  #mode-badge(data.chart_mode)
]

#v(12pt)

// ── Header ───────────────────────────────────────────────────────────────────

= Header

#grid(
  columns: (1fr, 1fr),
  column-gutter: 16pt,
  row-gutter: 6pt,

  kv("Process",     data.process_name),
  kv("Step",        data.step_name),

  kv("Window",      [#str(data.window_days) days]),
  kv("Subgroup Size", str(data.subgroup_size)),

  kv("Window Start", fmt-date(data.window_start)),
  kv("Window End",   fmt-date(data.window_end)),

  kv("Generated By", data.generated_by),
  kv("Generated At", fmt-date(data.generated_at)),
)

#divider()

// ── Specification ────────────────────────────────────────────────────────────

= Specification

#grid(
  columns: (1fr, 1fr, 1fr),
  column-gutter: 16pt,
  row-gutter: 6pt,

  kv("Nominal", fmt-num(data.spec.nominal, digits: 4, suffix: " " + data.spec.unit)),
  kv("Upper Tol", fmt-num(data.spec.upper_tol, digits: 4)),
  kv("Lower Tol", fmt-num(data.spec.lower_tol, digits: 4)),

  kv("USL", fmt-num(data.spec.usl, digits: 4, suffix: " " + data.spec.unit)),
  kv("LSL", fmt-num(data.spec.lsl, digits: 4, suffix: " " + data.spec.unit)),
  kv("Unit", data.spec.unit),
)

#divider()

// ── Active Baseline ──────────────────────────────────────────────────────────

#if data.baseline != none [
  = Active Baseline

  #grid(
    columns: (1fr, 1fr),
    column-gutter: 16pt,
    row-gutter: 6pt,

    kv("Chart Type",     data.baseline.chart_type),
    kv("Subgroup Size",  str(data.baseline.subgroup_size)),

    kv("Frozen By",      data.baseline.frozen_by),
    kv("Frozen At",      fmt-date(data.baseline.frozen_at)),

    kv("Sample Count",   str(data.baseline.sample_count)),
    kv("Notes",          data.baseline.notes),
  )

  #v(6pt)
  #text(weight: "semibold", font: sans-font, size: 10pt)[Frozen Limits]
  #v(4pt)

  #table(
    columns: (1fr, 1fr, 1fr, 1fr),
    align: (left, right, right, right),
    stroke: 0.4pt + rule,
    inset: 6pt,
    table.header(
      [*Series*], [*UCL*], [*CL*], [*LCL*],
    ),
    [X̄],         fmt-num(data.baseline.xbar_ucl, digits: 4),
                 fmt-num(data.baseline.xbar_cl,  digits: 4),
                 fmt-num(data.baseline.xbar_lcl, digits: 4),
    [Range],     fmt-num(data.baseline.range_ucl, digits: 4),
                 fmt-num(data.baseline.range_cl,  digits: 4),
                 fmt-num(data.baseline.range_lcl, digits: 4),
    [Individual], fmt-num(data.baseline.individual_ucl, digits: 4),
                  fmt-num(data.baseline.individual_cl,  digits: 4),
                  fmt-num(data.baseline.individual_lcl, digits: 4),
    [MR],        fmt-num(data.baseline.mr_ucl, digits: 4),
                 fmt-num(data.baseline.mr_cl,  digits: 4),
                 [—],
  )

  #divider()
]

// ── Statistics ───────────────────────────────────────────────────────────────

= Descriptive Statistics

#grid(
  columns: (1fr, 1fr, 1fr, 1fr),
  column-gutter: 16pt,
  row-gutter: 6pt,

  kv("Count",   fmt-int(data.statistics.count)),
  kv("Mean",    fmt-num(data.statistics.mean,    digits: 4)),
  kv("Std Dev", fmt-num(data.statistics.std_dev, digits: 4)),
  kv("Range",   if data.statistics.min == none or data.statistics.max == none [
    #text(fill: muted, style: "italic")[—]
  ] else [
    #str(calc.round(data.statistics.min, digits: 4))#sym.dash.en
    #str(calc.round(data.statistics.max, digits: 4))
  ]),

  kv("In Spec",     fmt-int(data.statistics.within_spec_count)),
  kv("Out of Spec", fmt-int(data.statistics.out_of_spec_count)),
  kv("", none),
  kv("", none),
)

#divider()

// ── Capability ───────────────────────────────────────────────────────────────

= Process Capability

#grid(
  columns: (1fr, 1fr, 1fr, 1fr),
  column-gutter: 16pt,
  row-gutter: 6pt,

  kv("Cp",  fmt-num(data.capability.cp,  digits: 3)),
  kv("Cpk", fmt-num(data.capability.cpk, digits: 3)),
  kv("Pp",  fmt-num(data.capability.pp,  digits: 3)),
  kv("Ppk", fmt-num(data.capability.ppk, digits: 3)),

  kv("σ within",  fmt-num(data.capability.std_dev_within,  digits: 4)),
  kv("σ overall", fmt-num(data.capability.std_dev_overall, digits: 4)),
  kv("Subgroups", fmt-int(data.capability.num_subgroups)),
  kv("Sample",    fmt-int(data.capability.sample_size)),
)

#v(6pt)
#text(fill: muted, font: sans-font, size: 9pt)[*Interpretation*]
#v(2pt)
#if data.capability.interpretation == "" [
  #text(fill: muted, style: "italic")[—]
] else [
  #data.capability.interpretation
]

#divider()

// ── Data points ──────────────────────────────────────────────────────────────

= Measurements

#if data.data_points.len() == 0 [
  #text(fill: muted, style: "italic")[No data in window.]
] else [
  #if data.data_truncated [
    #v(2pt)
    #text(size: 9pt, fill: warn, font: sans-font)[
      Showing first #str(data.data_points.len()) of more than #str(data.data_points.len()) measurements.
    ]
    #v(4pt)
  ]

  #table(
    columns: (auto, 1fr, auto, auto, auto),
    align: (left, left, right, center, left),
    stroke: 0.4pt + rule,
    inset: 5pt,
    table.header(
      [*Timestamp*], [*Part*], [*Value*], [*Spec*], [*Operator*],
    ),
    ..for p in data.data_points {
      (
        text(size: 9pt)[#p.timestamp],
        text(size: 9pt)[#p.part_erp_id],
        text(size: 9pt, font: mono-font)[#str(calc.round(p.value, digits: 4))],
        if p.is_within_spec {
          text(size: 9pt, fill: ok)[OK]
        } else {
          text(size: 9pt, fill: bad, weight: "semibold")[OOS]
        },
        text(size: 9pt)[#if p.operator == none [—] else [#p.operator]],
      )
    }
  )
]
