# Generated by Django 5.1.6 on 2026-03-17 18:36

import django.db.models.deletion
import django.utils.timezone
import encrypted_model_fields.fields
import uuid_utils._uuid_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tracker', '0016_tenantllmprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('id', models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('hubspot', 'HubSpot CRM'), ('salesforce', 'Salesforce CRM'), ('quickbooks', 'QuickBooks Online'), ('xero', 'Xero')], max_length=30)),
                ('display_name', models.CharField(blank=True, help_text="Optional custom label (e.g. 'Production HubSpot')", max_length=100)),
                ('is_enabled', models.BooleanField(default=False, help_text='Disabled until credentials are entered and verified')),
                ('sync_status', models.CharField(choices=[('IDLE', 'Idle'), ('SYNCING', 'Syncing'), ('ERROR', 'Error')], default='IDLE', max_length=10)),
                ('api_key', encrypted_model_fields.fields.EncryptedCharField(blank=True, default='')),
                ('oauth_refresh_token', encrypted_model_fields.fields.EncryptedCharField(blank=True, default='')),
                ('oauth_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('webhook_secret', encrypted_model_fields.fields.EncryptedCharField(blank=True, default='')),
                ('api_url', models.URLField(blank=True, default='')),
                ('config', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_error', models.TextField(blank=True, null=True)),
                ('last_sync_stats', models.JSONField(blank=True, default=dict, help_text='Last sync result: created, updated, errors, duration')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='Tracker.tenant')),
            ],
            options={
                'db_table': 'integrations_config',
                'ordering': ['provider'],
            },
        ),
        migrations.CreateModel(
            name='HubSpotPipelineStage',
            fields=[
                ('id', models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False)),
                ('stage_name', models.CharField(max_length=100)),
                ('api_id', models.CharField(max_length=50)),
                ('pipeline_id', models.CharField(blank=True, max_length=50, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('include_in_progress', models.BooleanField(default=False, help_text='Include in customer-facing pipeline progress tracking')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hubspot_pipeline_stages', to='integrations.integrationconfig')),
            ],
            options={
                'db_table': 'integrations_hubspot_pipeline_stage',
                'ordering': ['pipeline_id', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='HubSpotOrderLink',
            fields=[
                ('id', models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False)),
                ('deal_id', models.CharField(max_length=60)),
                ('last_synced_stage_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hubspot_link', to='Tracker.orders')),
                ('current_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_orders', to='integrations.hubspotpipelinestage')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hubspot_order_links', to='integrations.integrationconfig')),
            ],
            options={
                'db_table': 'integrations_hubspot_order_link',
            },
        ),
        migrations.CreateModel(
            name='HubSpotCompanyLink',
            fields=[
                ('id', models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False)),
                ('hubspot_company_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hubspot_links', to='Tracker.companies')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hubspot_company_links', to='integrations.integrationconfig')),
            ],
            options={
                'db_table': 'integrations_hubspot_company_link',
            },
        ),
        migrations.CreateModel(
            name='IntegrationSyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False)),
                ('sync_type', models.CharField(choices=[('FULL', 'Full Sync'), ('INCREMENTAL', 'Incremental Sync'), ('SINGLE', 'Single Record Sync'), ('PUSH', 'Outbound Push')], default='FULL', max_length=20)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='RUNNING', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('records_processed', models.IntegerField(default=0)),
                ('records_created', models.IntegerField(default=0)),
                ('records_updated', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Provider-specific details (e.g. pipeline stages synced, contacts created)')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='integrations.integrationconfig')),
            ],
            options={
                'db_table': 'integrations_sync_log',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessedWebhook',
            fields=[
                ('id', models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False)),
                ('external_event_id', models.CharField(max_length=200)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.integrationconfig')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tracker.tenant')),
            ],
            options={
                'db_table': 'integrations_processed_webhook',
            },
        ),
        migrations.AddConstraint(
            model_name='integrationconfig',
            constraint=models.UniqueConstraint(fields=('tenant', 'provider'), name='integrations_config_tenant_provider_uniq'),
        ),
        migrations.AddConstraint(
            model_name='hubspotpipelinestage',
            constraint=models.UniqueConstraint(fields=('integration', 'api_id'), name='hubspot_stage_integration_apiid_uniq'),
        ),
        migrations.AddConstraint(
            model_name='hubspotorderlink',
            constraint=models.UniqueConstraint(fields=('integration', 'deal_id'), name='hubspot_order_link_integration_dealid_uniq'),
        ),
        migrations.AddConstraint(
            model_name='hubspotcompanylink',
            constraint=models.UniqueConstraint(fields=('integration', 'hubspot_company_id'), name='hubspot_company_link_integration_companyid_uniq'),
        ),
        migrations.AddIndex(
            model_name='integrationsynclog',
            index=models.Index(fields=['-started_at'], name='integration_started_4f5f05_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationsynclog',
            index=models.Index(fields=['integration', 'status'], name='integration_integra_c9f0ec_idx'),
        ),
        migrations.AddConstraint(
            model_name='processedwebhook',
            constraint=models.UniqueConstraint(fields=('integration', 'external_event_id'), name='integrations_webhook_idempotency'),
        ),
    ]
