# Generated by Django 5.1.6 on 2026-03-17 18:43

import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hubspotcompanylink',
            name='id',
            field=models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hubspotorderlink',
            name='id',
            field=models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hubspotpipelinestage',
            name='id',
            field=models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='integrationconfig',
            name='id',
            field=models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='integrationsynclog',
            name='id',
            field=models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='processedwebhook',
            name='id',
            field=models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False),
        ),
    ]
