# Generated by Django 5.1.6 on 2026-03-17 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0017_milestone_orders_current_milestone_milestonetemplate_and_more'),
        ('integrations', '0002_alter_hubspotcompanylink_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubspotpipelinestage',
            name='mapped_milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hubspot_stages', to='Tracker.milestone'),
        ),
    ]
