# Generated by Django 5.1.6 on 2025-10-31 22:49
#
# NOTE: This migration has been neutralized. Group permissions are now managed by:
#   - Tracker/permissions.py (declarative permission structure)
#   - Tracker/services/permission_service.py (applies permissions post-migrate)
#
# Groups are still created here, but permissions are assigned by the post_migrate signal.

from django.db import migrations


def create_user_groups(apps, schema_editor):
    """Create the 7 standard user groups for RBAC.

    NOTE: Permission assignment has been moved to post_migrate signal.
    This migration now only creates groups (without permissions).
    """
    Group = apps.get_model('auth', 'Group')

    group_names = [
        'Admin',
        'QA_Manager',
        'QA_Inspector',
        'Production_Manager',
        'Production_Operator',
        'Document_Controller',
        'Customer',
    ]

    for group_name in group_names:
        group, created = Group.objects.get_or_create(name=group_name)
        if created:
            print(f"Created group: {group_name}")
        else:
            print(f"Group already exists: {group_name}")

    print("NOTE: Permissions will be assigned by post_migrate signal")


def reverse_create_user_groups(apps, schema_editor):
    """Remove the user groups if migration is reversed"""
    Group = apps.get_model('auth', 'Group')

    group_names = ['Admin', 'QA_Manager', 'QA_Inspector', 'Production_Manager',
                   'Production_Operator', 'Document_Controller', 'Customer']

    for group_name in group_names:
        Group.objects.filter(name=group_name).delete()
        print(f"Deleted group: {group_name}")


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0001_initial'),
        ('auth', '__latest__'),
        ('contenttypes', '__latest__'),  # Needed for ContentType
    ]

    operations = [
        migrations.RunPython(create_user_groups, reverse_create_user_groups),
    ]
