# Generated by Django 5.1.6 on 2025-11-01 01:58
#
# NOTE: This migration has been neutralized. Group permissions are now managed by:
#   - Tracker/permissions.py (declarative permission structure)
#   - Tracker/services/permission_service.py (applies permissions post-migrate)

from django.db import migrations


def noop(apps, schema_editor):
    """No-op: Permission assignment moved to post_migrate signal."""
    print("Skipped: Permission assignment now handled by post_migrate signal")


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0003_alter_documents_options_alter_qualityreports_options_and_more'),
        ('auth', '__latest__'),
    ]

    operations = [
        migrations.RunPython(noop, noop),
    ]
