"""
Security-audit verification: cross-tenant FK write path.

Hypothesis (from the audit): `SecureModel` sets `default_manager_name =
'unscoped'`, so DRF `ModelSerializer` auto-generates relational fields whose
lookup queryset is the UNSCOPED manager. A writable FK that isn't explicitly
declared as `TenantScopedPrimaryKeyRelatedField` therefore resolves PKs across
ALL tenants — letting a tenant-A request body reference a tenant-B row.

These tests prove the hypothesis at the serializer-validation layer (the point
where the foreign PK is accepted), and contrast it against a field that uses
the scoped variant on the SAME target model.

Result interpretation:
  * test_VULN_* PASSING = the leak is real (a tenant-A serializer resolved a
    tenant-B PK). It documents current behaviour.
  * test_scoped_field_* PASSING = the existing mitigation works where applied.
"""

from rest_framework import serializers as drf_serializers

from Tracker.tests.base import TenantTestCase
from Tracker.serializers.fields import TenantScopedPrimaryKeyRelatedField


class CrossTenantFKWritePathTests(TenantTestCase):
    def setUp(self):
        super().setUp()
        from Tracker.models import PartTypes

        # Victim row in tenant B. setUp leaves the ContextVar pointed at
        # tenant_a, so every serializer below validates "as tenant A".
        self.victim_part_type = self.create_for_tenant(
            PartTypes, self.tenant_b, name="B-SECRET-PARTTYPE"
        )

    def test_secured_serializer_autogenerates_scoped_fk(self):
        """StepsSerializer now inherits SecureModelMixin (which sets
        serializer_related_field), so its AUTO-generated part_type FK is the
        scoped variant and rejects a tenant-B PartTypes PK. This is the
        former leak, now closed by the SecureModelMixin base."""
        from Tracker.serializers.mes_lite import StepsSerializer

        field = StepsSerializer().fields["part_type"]
        # The fix: auto-generated FK is now the scoped variant.
        self.assertIsInstance(field, TenantScopedPrimaryKeyRelatedField)

        with self.assertRaises(drf_serializers.ValidationError):
            field.run_validation(str(self.victim_part_type.pk))

    def test_scoped_field_rejects_foreign_tenant_pk(self):
        """Contrast: PartsSerializer.part_type uses the scoped field on the
        SAME target model and correctly rejects the foreign PK."""
        from Tracker.serializers.mes_lite import PartsSerializer

        field = PartsSerializer().fields["part_type"]
        self.assertIsInstance(field, TenantScopedPrimaryKeyRelatedField)

        with self.assertRaises(drf_serializers.ValidationError):
            field.run_validation(str(self.victim_part_type.pk))

    def test_CONFIRM_serializer_related_field_scopes_autogenerated_fk(self):
        """Confirm the fix mechanism: setting `serializer_related_field` on a
        ModelSerializer makes DRF AUTO-BUILD relational fields as the scoped
        variant, which then rejects a foreign-tenant PK."""
        from rest_framework import serializers
        from Tracker.models import Steps

        class _Probe(serializers.ModelSerializer):
            serializer_related_field = TenantScopedPrimaryKeyRelatedField

            class Meta:
                model = Steps
                fields = ["id", "name", "part_type"]

        field = _Probe().fields["part_type"]
        self.assertIsInstance(field, TenantScopedPrimaryKeyRelatedField)
        with self.assertRaises(drf_serializers.ValidationError):
            field.run_validation(str(self.victim_part_type.pk))

    def test_scoped_field_accepts_own_tenant_pk(self):
        """Sanity: the scoped field still resolves a same-tenant PK."""
        from Tracker.models import PartTypes
        from Tracker.serializers.mes_lite import PartsSerializer

        own = self.create_for_tenant(PartTypes, self.tenant_a, name="A-PARTTYPE")
        field = PartsSerializer().fields["part_type"]
        self.assertEqual(field.run_validation(str(own.pk)), own)
