/**
 * Strict TypeScript types for API response models.
 *
 * Generated by `openapi-typescript` from PartsTracker/schema.yaml — see
 * `bun run generate-types`. Re-exported here as friendly aliases so call
 * sites can `import type { Parts } from "@/lib/api/types"` instead of
 * digging through `components["schemas"]["Parts"]`.
 *
 * Pair these with `createColumnHelper<T>()` (in ModelEditorPage) to get
 * type-checked column renderers without the API client's permissive
 * passthrough zod schemas leaking into the UI layer.
 *
 * Add new aliases below as pages need them.
 */
import type { components } from "./generated-types";

type S = components["schemas"];

export type Parts = S["Parts"];
export type PartsStatusEnum = S["PartsStatusEnum"];

export type Orders = S["Orders"];
export type WorkOrder = S["WorkOrder"];
export type Processes = S["Processes"];
export type PartTypes = S["PartTypes"];
export type Steps = S["Steps"];

export type CAPA = S["CAPA"];
export type QualityReports = S["QualityReports"];
export type QuarantineDisposition = S["QuarantineDisposition"];

export type CalibrationRecord = S["CalibrationRecord"];
export type TrainingRecord = S["TrainingRecord"];
export type Equipments = S["Equipments"];
export type EquipmentType = S["EquipmentType"];

export type Company = S["Company"];
export type User = S["User"];