#!/bin/bash
#
# Ambac Tracker - On-Premise Installation Script
# Usage: ./install.sh [--airgapped]
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

echo "=========================================="
echo "  Ambac Tracker Installation"
echo "=========================================="
echo ""

# -----------------------------------------------------------------------------
# Prerequisites Check
# -----------------------------------------------------------------------------
echo -e "${YELLOW}Checking prerequisites...${NC}"

# Check Docker
if ! command -v docker &> /dev/null; then
    echo -e "${RED}Error: Docker is not installed.${NC}"
    echo "Please install Docker: https://docs.docker.com/get-docker/"
    exit 1
fi
echo -e "  ${GREEN}✓${NC} Docker installed ($(docker --version | cut -d' ' -f3 | tr -d ','))"

# Check Docker Compose
if ! docker compose version &> /dev/null; then
    echo -e "${RED}Error: Docker Compose is not installed.${NC}"
    echo "Please install Docker Compose: https://docs.docker.com/compose/install/"
    exit 1
fi
echo -e "  ${GREEN}✓${NC} Docker Compose installed"

# Check if Docker is running
if ! docker info &> /dev/null; then
    echo -e "${RED}Error: Docker is not running.${NC}"
    echo "Please start Docker and try again."
    exit 1
fi
echo -e "  ${GREEN}✓${NC} Docker is running"

echo ""

# -----------------------------------------------------------------------------
# Airgapped Mode - Load Images
# -----------------------------------------------------------------------------
if [[ "$1" == "--airgapped" ]] || [[ -d "$PROJECT_DIR/images" ]]; then
    echo -e "${YELLOW}Airgapped mode: Loading Docker images...${NC}"

    if [[ -d "$PROJECT_DIR/images" ]]; then
        for image in "$PROJECT_DIR/images"/*.tar; do
            if [[ -f "$image" ]]; then
                echo "  Loading $(basename "$image")..."
                docker load -i "$image"
            fi
        done
        echo -e "  ${GREEN}✓${NC} Images loaded"
    else
        echo -e "  ${YELLOW}!${NC} No images/ directory found. Will pull from registry."
    fi
    echo ""
fi

# -----------------------------------------------------------------------------
# Create Docker Network
# -----------------------------------------------------------------------------
echo -e "${YELLOW}Setting up Docker network...${NC}"
if docker network inspect ambactracker-network &> /dev/null; then
    echo -e "  ${GREEN}✓${NC} Network 'ambactracker-network' already exists"
else
    docker network create ambactracker-network
    echo -e "  ${GREEN}✓${NC} Network 'ambactracker-network' created"
fi
echo ""

# -----------------------------------------------------------------------------
# Environment Configuration
# -----------------------------------------------------------------------------
cd "$PROJECT_DIR"

if [[ ! -f ".env" ]]; then
    echo -e "${YELLOW}Creating environment configuration...${NC}"

    if [[ -f ".env.example" ]]; then
        cp .env.example .env
    else
        # Create minimal .env
        cat > .env << 'EOF'
# Ambac Tracker Configuration
# Generated by install.sh

# Database
POSTGRES_PASSWORD=CHANGE_ME_$(openssl rand -hex 16)
POSTGRES_DB=tracker_AMBAC
POSTGRES_USER=postgres

# Django
DJANGO_SECRET_KEY=$(openssl rand -hex 32)
DJANGO_DEBUG=false
ALLOWED_HOSTS=localhost,127.0.0.1

# Deployment Mode
DEPLOYMENT_MODE=dedicated

# Optional: AI Features (Ollama)
# OLLAMA_URL=http://ollama:11434
# AI_EMBED_ENABLED=true

# Optional: Email
# EMAIL_HOST=smtp.example.com
# EMAIL_PORT=587
# EMAIL_HOST_USER=
# EMAIL_HOST_PASSWORD=
# EMAIL_USE_TLS=true
EOF
    fi

    # Generate secrets
    POSTGRES_PW=$(openssl rand -hex 16)
    DJANGO_SECRET=$(openssl rand -hex 32)

    # Replace placeholders (works on both Linux and macOS)
    if [[ "$OSTYPE" == "darwin"* ]]; then
        sed -i '' "s/CHANGE_ME_.*$/CHANGE_ME_${POSTGRES_PW}/" .env
        sed -i '' "s/DJANGO_SECRET_KEY=.*/DJANGO_SECRET_KEY=${DJANGO_SECRET}/" .env
    else
        sed -i "s/CHANGE_ME_.*$/CHANGE_ME_${POSTGRES_PW}/" .env
        sed -i "s/DJANGO_SECRET_KEY=.*/DJANGO_SECRET_KEY=${DJANGO_SECRET}/" .env
    fi

    echo -e "  ${GREEN}✓${NC} Created .env with generated secrets"
    echo ""
    echo -e "${YELLOW}IMPORTANT: Review and edit .env before continuing:${NC}"
    echo "  - Set ALLOWED_HOSTS to your domain"
    echo "  - Configure email settings if needed"
    echo "  - Review database password"
    echo ""
    read -p "Press Enter to continue after reviewing .env, or Ctrl+C to abort..."
else
    echo -e "${GREEN}✓${NC} Using existing .env file"
fi
echo ""

# -----------------------------------------------------------------------------
# Create Required Directories
# -----------------------------------------------------------------------------
echo -e "${YELLOW}Creating directories...${NC}"
mkdir -p "$PROJECT_DIR/backups"
mkdir -p "$PROJECT_DIR/PartsTracker/media"
mkdir -p "$PROJECT_DIR/certs"
echo -e "  ${GREEN}✓${NC} Directories created"
echo ""

# -----------------------------------------------------------------------------
# Pull/Build Images (if not airgapped)
# -----------------------------------------------------------------------------
if [[ "$1" != "--airgapped" ]] && [[ ! -d "$PROJECT_DIR/images" ]]; then
    echo -e "${YELLOW}Pulling Docker images...${NC}"
    docker compose pull postgres redis || true
    echo -e "${YELLOW}Building application images...${NC}"
    docker compose build
    echo -e "  ${GREEN}✓${NC} Images ready"
    echo ""
fi

# -----------------------------------------------------------------------------
# Start Services
# -----------------------------------------------------------------------------
echo -e "${YELLOW}Starting services...${NC}"
docker compose --profile local up -d

echo ""
echo -e "${YELLOW}Waiting for database to be ready...${NC}"
sleep 10

# Wait for backend health check
MAX_ATTEMPTS=30
ATTEMPT=0
while [[ $ATTEMPT -lt $MAX_ATTEMPTS ]]; do
    if docker compose exec -T backend curl -sf http://localhost:8000/health/ > /dev/null 2>&1; then
        echo -e "  ${GREEN}✓${NC} Backend is healthy"
        break
    fi
    ATTEMPT=$((ATTEMPT + 1))
    echo "  Waiting for backend... ($ATTEMPT/$MAX_ATTEMPTS)"
    sleep 5
done

if [[ $ATTEMPT -eq $MAX_ATTEMPTS ]]; then
    echo -e "${YELLOW}Warning: Backend health check timed out. Check logs with: docker compose logs backend${NC}"
fi

echo ""

# -----------------------------------------------------------------------------
# Summary
# -----------------------------------------------------------------------------
echo "=========================================="
echo -e "  ${GREEN}Installation Complete!${NC}"
echo "=========================================="
echo ""
echo "Access the application at:"
echo "  https://localhost (if using Caddy with TLS)"
echo "  http://localhost:8000 (backend directly)"
echo ""
echo "Default admin credentials:"
echo "  Check output of: docker compose logs backend | grep -i admin"
echo ""
echo "Useful commands:"
echo "  docker compose logs -f          # View logs"
echo "  docker compose ps               # Check status"
echo "  docker compose down             # Stop services"
echo "  docker compose up -d            # Start services"
echo "  ./scripts/backup.sh             # Backup database"
echo ""
echo "For production, configure TLS certificates in ./certs/"
echo ""
