name: Deploy Frontend to Azure Static Web App

on:
  push:
    branches:
      - master
    paths:
      - 'ambac-tracker-ui/**'
      - '.github/workflows/deploy-frontend.yml'
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Frontend
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AMBACTRACKER }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "./ambac-tracker-ui"
          api_location: ""
          output_location: "dist"
        env:
          VITE_API_TARGET: "https://parts-tracker-django-gqfygdhsejamauh3.centralus-01.azurewebsites.net"
